// ---------------------------------------------------------------------------
// cuttlefish-env.d.ts — Virtual module declaration for '@typecad/board'
//
// Auto-generated by the cuttlefish transpiler. Do not edit manually.
// To change the board, update cuttlefish.config.ts and re-run the transpiler.
//
// Board: @typecad/board-xiao-nrf52840
// ---------------------------------------------------------------------------

declare global {
  type Owned<T = unknown> = T;
  type Shared<T = unknown> = T;
  type Mutable<T = unknown> = T;

  // C-style explicit number types recognized by the transpiler
  type uint8_t = number;
  type int8_t = number;
  type uint16_t = number;
  type int16_t = number;
  type uint32_t = number;
  type int32_t = number;
  type size_t = number;
  type float = number;
  type double = number;

  // console — declared here (not pulled from lib.dom) so a project does not
  // need "dom" in tsconfig lib just to type console.log. Avoiding lib.dom
  // also keeps DOM global type names (Node, Element, Event, Document, ...)
  // out of scope, so a user class named e.g. `Node` is not shadowed by the
  // DOM global of the same name. Platforms may declaration-merge extra
  // members onto this interface via ambientTypeDeclarations().
  interface Console {
    log(...args: unknown[]): void;
    info(...args: unknown[]): void;
    debug(...args: unknown[]): void;
    warn(...args: unknown[]): void;
    error(...args: unknown[]): void;
  }
  const console: Console;

  // Convenience helper for volatile variables in TypeCAD programs.
  // The transpiler detects calls to volatile() and emits the C++ volatile qualifier.
  declare function volatile<T>(value: T): T;

  // JS-style timers (NOTE: timer ops are unsupported on Zephyr in this release —
  // these are declared so user code type-checks; transpilation emits a diagnostic.)
  declare function setInterval(handler: () => void, timeout?: number): number;
  declare function setTimeout(handler: () => void, timeout?: number): number;
  declare function clearInterval(id: number): void;
  declare function clearTimeout(id: number): void;

  // Timing utilities (transpiled to k_msleep / k_uptime_get_32 / k_busy_wait)
  const Timing: {
    millis(): number;
    micros(): number;
    delay(ms: number): void;
    delayMicroseconds(us: number): void;
  };

  // Watchdog timer (transpiled to wdt_install_timeout / wdt_feed / wdt_disable)
  const WDT: {
    enable(timeout?: '15ms' | '30ms' | '60ms' | '120ms' | '250ms' | '500ms' | '1s' | '2s' | '4s' | '8s'): void;
    reset(): void;
    disable(): void;
  };
}
declare module '@typecad/board' {
  export type Owned<T = any> = T;
  export type Shared<T = any> = T;
  export type Mutable<T = any> = T;
}
declare global {
  export type Owned<T = any> = T;
  export type Shared<T = any> = T;
  export type Mutable<T = any> = T;
}
declare global {
}

declare module '@typecad/board' {
  export * from '@typecad/board-xiao-nrf52840';
  export type Owned<T = any> = T;
  export type Shared<T = any> = T;
  export type Mutable<T = any> = T;
}

export {};
