import type { Adafruit_GFX } from "./Adafruit_GFX";

export declare class Adafruit_SPITFT extends Adafruit_GFX {
  constructor(w: number, h: number, cs: number, dc: number, mosi: number, sck: number, rst: number, miso: number);
  constructor(w: number, h: number, cs: number, dc: number, rst: number);
  constructor(w: number, h: number, spiClass: number, cs: number, dc: number, rst: number);
  constructor(w: number, h: number, busWidth: any, d0: number, wr: number, dc: number, cs: number, rst: number, rd: number);
  constructor();
  initSPI(freq: number, spiMode: number): void;
  setSPISpeed(freq: number): void;
  startWrite(): void;
  endWrite(): void;
  sendCommand(commandByte: number, dataBytes: number, numDataBytes: number): void;
  sendCommand(commandByte: number, dataBytes: number, numDataBytes: number): void;
  sendCommand16(commandWord: number, dataBytes: number, numDataBytes: number): void;
  readcommand8(commandByte: number, index: number): number;
  readcommand16(addr: number): number;
  writePixel(x: number, y: number, color: number): void;
  writePixels(colors: number, len: number, block: boolean, bigEndian: boolean): void;
  writeColor(color: number, len: number): void;
  writeFillRect(x: number, y: number, w: number, h: number, color: number): void;
  writeFastHLine(x: number, y: number, w: number, color: number): void;
  writeFastVLine(x: number, y: number, h: number, color: number): void;
  writeFillRectPreclipped(x: number, y: number, w: number, h: number, color: number): void;
  dmaWait(): void;
  dmaBusy(): boolean;
  swapBytes(src: number, len: number, dest: number): void;
  drawPixel(x: number, y: number, color: number): void;
  fillRect(x: number, y: number, w: number, h: number, color: number): void;
  drawFastHLine(x: number, y: number, w: number, color: number): void;
  drawFastVLine(x: number, y: number, h: number, color: number): void;
  pushColor(color: number): void;
  drawRGBBitmap(x: number, y: number, pcolors: number, w: number, h: number): void;
  invertDisplay(i: boolean): void;
  color565(r: number, g: number, b: number): number;
  spiWrite(b: number): void;
  writeCommand(cmd: number): void;
  spiRead(): number;
  write16(w: number): void;
  writeCommand16(cmd: number): void;
  read16(): number;
  SPI_WRITE16(w: number): void;
  SPI_WRITE32(l: number): void;
  SPI_CS_HIGH(): void;
  SPI_CS_LOW(): void;
  SPI_DC_HIGH(): void;
  SPI_DC_LOW(): void;
}
