// Auto-generated by typecad-hal (UI lowering). Do not edit.
import type { TextElement, ButtonElement, ViewElement, CheckElement, SelectElement, RadioElement, ProgressElement, RangeElement, InputElement, CanvasElement } from "@typecad/ui";
interface FeaturesScreenGroup {
  pgA: ViewElement;
  barA: ViewElement;
  barATitle: TextElement;
  logoImg: TextElement;
  progRow: ViewElement;
  featProgress: ProgressElement;
  echoRow: ViewElement;
  pressEcho: TextElement;
  hintRow: ViewElement;
  hintA: TextElement;
  pgB: ViewElement;
  barB: ViewElement;
  barBTitle: TextElement;
  gradRow: ViewElement;
  gradImg: TextElement;
  featSel: SelectElement;
  featList: TextElement;
  featToast: TextElement;
  featDialog: TextElement;
  dlgTitle: TextElement;
  dlgBody: TextElement;
  pageEchoWrap: ViewElement;
  pageEcho: TextElement;
}
interface NavScreenGroup {
  navBar: ViewElement;
  navTitle: TextElement;
  navBody: ViewElement;
  navHint: TextElement;
  navHome: ButtonElement;
}
interface ScreenGroups {
  features: FeaturesScreenGroup;
  nav: NavScreenGroup;
}
export interface ScreenTree {
  features: ViewElement;
  pgA: ViewElement;
  barA: ViewElement;
  barATitle: TextElement;
  logoImg: TextElement;
  progRow: ViewElement;
  featProgress: ProgressElement;
  echoRow: ViewElement;
  pressEcho: TextElement;
  hintRow: ViewElement;
  hintA: TextElement;
  pgB: ViewElement;
  barB: ViewElement;
  barBTitle: TextElement;
  gradRow: ViewElement;
  gradImg: TextElement;
  featSel: SelectElement;
  featList: TextElement;
  featToast: TextElement;
  featDialog: TextElement;
  dlgTitle: TextElement;
  dlgBody: TextElement;
  pageEchoWrap: ViewElement;
  pageEcho: TextElement;
  nav: ViewElement;
  navBar: ViewElement;
  navTitle: TextElement;
  navBody: ViewElement;
  navHint: TextElement;
  navHome: ButtonElement;
  groups: ScreenGroups;
}
export const screen: ScreenTree;