// ---------------------------------------------------------------------------
// AVR native SSD1309 display adapter — 1-bit monochrome OLED over TWI (I2C).
//
// Drives the panel through AVR's native _twi_* register helpers (already
// emitted by NativeAVRStrategy.shimLines()). No vendor GFX library, no
// Arduino <Wire.h>.
//
// ──── BSD-3-Clause attribution ────────────────────────────────────────────
// The SSD1306/SSD1309 panel init command table emitted by this adapter is
// transcribed from Adafruit's Adafruit_SSD1306 library:
//
//   Adafruit_SSD1306.cpp ssd1306_128x64_i2c_init[]
//   Copyright (c) 2013 Adafruit Industries. All rights reserved.
//   Licensed under BSD-3-Clause.
//   Upstream: https://github.com/adafruit/Adafruit_SSD1306
//
// The init bytes themselves are manufacturer (Solomon Systech) reference
// code from the SSD1306/SSD1309 datasheet; equivalent sequences appear
// across many OLED libraries. The transcription here is from Adafruit's
// published source.
// ──── End BSD-3-Clause attribution ────────────────────────────────────────
//
// Memory model: page-buffered. 128x64 mono panel = 128 * 64 / 8 = 1024 bytes,
// which fits comfortably in ATmega328P's 2KB RAM. The buffer is the backing
// store; draws go into it, then display_partial_refresh flushes it to the
// panel over I2C.
//
// Address: 7-bit 0x3C, sent on the wire as 0x78 (write). The TWI helper
// _twi_begin_transmission takes the 7-bit address and shifts internally.
//
// SSD1306 and SSD1309 share the same command set for our purposes.
// ---------------------------------------------------------------------------

import type { DisplayAdapterGenerator } from "@typecad/cuttlefish/api/shared";

export const avrSsd1309Adapter: DisplayAdapterGenerator = (display) => {
  const w = display.width;
  const h = display.height;
  const address = display._mountAddress ?? 0x3c;
  const rotation = display.rotation ?? 0;
  const addrHex = "0x" + address.toString(16);
  const bufferSize = (w * h) / 8;  // 128*64/8 = 1024

  return {
    includes: [
      `// --- AVR SSD1309 driver (1-bit mono, I2C via _twi_* primitives) ---`,
      `// No vendor GFX library, no Arduino Wire header. Panel driven by AVR's native TWI registers.`,
      `#define CuttlefishDisplayTarget CuttlefishGFX`,
      `#define CuttlefishCanvas16 CuttlefishCanvas16`,
    ].join("\n"),

    declaration: [
      `// Panel state — addressed over TWI at ${addrHex}.`,
      `struct __AvrSsd1309Ctx {`,
      `  uint8_t addr;        // 7-bit I2C address`,
      `  int16_t width;`,
      `  int16_t height;`,
      `};`,
      `static __AvrSsd1309Ctx __avr_ssd1309 = { ${addrHex}, ${w}, ${h} };`,
      `// 1KB page buffer for ${w}x${h} mono panel (1 bit per pixel).`,
      `static uint8_t __ssd1309_buffer[${bufferSize}];`,
      `// Offscreen mono canvas (subclass of CuttlefishGFX) — provides`,
      `// drawPixel/fillRect/etc. against __ssd1309_buffer. The CuttlefishGFX`,
      `// panel ops below target this same buffer.`,
      `static CuttlefishCanvasMono __avr_ssd1309_canvas(${w}, ${h});`,
    ].join("\n"),

    functions: [
      `// --- AVR SSD1309 adapter functions ---`,
      ``,
      `// Send a command byte over TWI: control byte 0x00 (Co=0, D/C=0).`,
      `static inline void __avr_ssd1309_cmd(uint8_t c) {`,
      `  _twi_begin_transmission(${addrHex});`,
      `  _twi_write_byte(0x00);  // control byte: command`,
      `  _twi_write_byte(c);`,
      `  _twi_end_transmission(1);  // send STOP`,
      `}`,
      ``,
      `// Send a sequence of command bytes (each in its own transmission so the`,
      `// SSD1306's command-stream decode stays simple on AVR — buffers are tiny).`,
      `static inline void __avr_ssd1309_cmds(const uint8_t* cmds, uint8_t n) {`,
      `  for (uint8_t i = 0; i < n; i++) __avr_ssd1309_cmd(cmds[i]);`,
      `}`,
      ``,
      `// ── Panel-ops (function-pointer struct consumed by CuttlefishGFX) ───────`,
      `// All ops target __ssd1309_buffer; display_partial_refresh publishes it.`,
      `// The buffer is indexed as page * (w/8... actually w bytes per page) + x;`,
      `// see SSD1306 datasheet: each byte is 8 vertical pixels in one column.`,
      ``,
      `static void __avr_ssd1309_op_startWrite(void* /*ctx*/) { /* no bus lock needed for buffer ops */ }`,
      `static void __avr_ssd1309_op_endWrite(void* /*ctx*/) { /* nothing */ }`,
      `static void __avr_ssd1309_op_setAddrWindow(void* /*ctx*/, int16_t x, int16_t y, int16_t w, int16_t h) {`,
      `  (void)x; (void)y; (void)w; (void)h;`,
      `  // Page-buffered: addr window is virtual; writePixel handles placement.`,
      `}`,
      `static void __avr_ssd1309_op_writePixels(void* /*ctx*/, const uint16_t* px, uint32_t n) {`,
      `  // Mono snap: write into the buffer at the current cursor. The runtime`,
      `  // uses this rarely (mostly direct drawPixel into the buffer); here we`,
      `  // simply drop pixels beyond what's tracked. SSD1309 is page-buffered so`,
      `  // there is no concept of a linear pixel stream — display writes go via`,
      `  // drawPixel against the buffer.`,
      `  (void)px; (void)n;`,
      `}`,
      `static void __avr_ssd1309_op_writePixel(void* /*ctx*/, int16_t x, int16_t y, uint16_t c) {`,
      `  if (x < 0 || y < 0 || x >= ${w} || y >= ${h}) return;`,
      `  // SSD1306 buffer layout: page = y / 8, byte at page * w + x, bit = y % 8.`,
      `  uint16_t page = static_cast<uint16_t>(y >> 3);`,
      `  uint8_t mask = static_cast<uint8_t>(1u << (y & 7));`,
      `  uint16_t idx = static_cast<uint16_t>(page * ${w} + x);`,
      `  if (c) __ssd1309_buffer[idx] |= mask;`,
      `  else   __ssd1309_buffer[idx] &= ~mask;`,
      `}`,
      `static void __avr_ssd1309_op_fillRect(void* ctx, int16_t x, int16_t y, int16_t w, int16_t h, uint16_t c) {`,
      `  // Fast path: delegate to writePixel loop. For SSD1309 the page layout`,
      `  // makes an optimized byte-fill awkward (rows must align to 8); the loop`,
      `  // is small enough at 128x64 to be fast on AVR.`,
      `  for (int16_t j = y; j < y + h; j++) {`,
      `    for (int16_t i = x; i < x + w; i++) {`,
      `      __avr_ssd1309_op_writePixel(ctx, i, j, c);`,
      `    }`,
      `  }`,
      `}`,
      `static int16_t __avr_ssd1309_op_width(void* ctx) {`,
      `  return ((__AvrSsd1309Ctx*)ctx)->width;`,
      `}`,
      `static int16_t __avr_ssd1309_op_height(void* ctx) {`,
      `  return ((__AvrSsd1309Ctx*)ctx)->height;`,
      `}`,
      `static void __avr_ssd1309_op_flush(void* /*ctx*/, int16_t x, int16_t y, int16_t w, int16_t h) {`,
      `  // SSD1306 has no true partial refresh — display_partial_refresh wraps this.`,
      `  // Set column + page range then stream the buffer. For simplicity flush`,
      `  // the full buffer; runtime dirty-rect tracking minimizes draws INTO it.`,
      `  (void)x; (void)y; (void)w; (void)h;`,
      `  __avr_ssd1309_cmd(0x21);  // column address range`,
      `  __avr_ssd1309_cmd(0x00);  // start = 0`,
      `  __avr_ssd1309_cmd(${w - 1} & 0xFF);  // end`,
      `  __avr_ssd1309_cmd(0x22);  // page address range`,
      `  __avr_ssd1309_cmd(0x00);  // start = 0`,
      `  __avr_ssd1309_cmd(${(h - 1) / 8} & 0xFF);  // end page`,
      `  for (uint16_t i = 0; i < ${bufferSize}; i++) {`,
      `    _twi_begin_transmission(${addrHex});`,
      `    _twi_write_byte(0x40);  // control byte: data`,
      `    _twi_write_byte(__ssd1309_buffer[i]);`,
      `    _twi_end_transmission(1);`,
      `  }`,
      `}`,
      ``,
      `static const CuttlefishPanelOps __avr_ssd1309_ops = {`,
      `  __avr_ssd1309_op_startWrite,`,
      `  __avr_ssd1309_op_endWrite,`,
      `  __avr_ssd1309_op_setAddrWindow,`,
      `  __avr_ssd1309_op_writePixels,`,
      `  __avr_ssd1309_op_writePixel,`,
      `  __avr_ssd1309_op_fillRect,`,
      `  __avr_ssd1309_op_width,`,
      `  __avr_ssd1309_op_height,`,
      `  __avr_ssd1309_op_flush,`,
      `};`,
      ``,
      `// __tc_display is the CuttlefishGFX instance the runtime targets.`,
      `// Backed by __avr_ssd1309_ops + __avr_ssd1309 state.`,
      `CuttlefishGFX __tc_display(&__avr_ssd1309_ops, &__avr_ssd1309);`,
      ``,
      `// ── display_* adapter surface (consumed by ui_display_* shim layer) ────`,
      ``,
      `static inline void display_init() {`,
      `  _twi_init();`,
      `  _twi_set_clock(400000);`,
      `  // SSD1306 init sequence — transcribed from Adafruit_SSD1306.cpp`,
      `  // ssd1306_128x64_i2c_init[] (verbatim).`,
      `  static const uint8_t init_cmds[] = {`,
      `    0xAE,          // display off`,
      `    0xD5, 0x80,    // clock divide ratio 0x80`,
      `    0xA8, 0x3F,    // multiplex = height-1 = 63`,
      `    0xD3, 0x00,    // display offset = 0`,
      `    0x40,          // start line = 0`,
      `    0x8D, 0x14,    // charge pump enable (0x14 = on)`,
      `    0x20, 0x00,    // memory addressing mode = horizontal`,
      `    0xA1,          // seg remap (column 127 = segment 0)`,
      `    0xC8,          // comscandec (scan from COM[N-1] to COM0)`,
      `    0xDA, 0x12,    // compins: sequential, alternating`,
      `    0x81, 0xCF,    // contrast = 0xCF`,
      `    0xD9, 0xF1,    // precharge = 0xF1`,
      `    0xDB, 0x40,    // vcomdeselect = 0x40`,
      `    0xA4,          // display resume to RAM content`,
      `    0xA6,          // normal display (not inverted)`,
      `    0xAF,          // display on`,
      `  };`,
      `  __avr_ssd1309_cmds(init_cmds, sizeof(init_cmds));`,
      `  memset(__ssd1309_buffer, 0, ${bufferSize});`,
      `  // Apply rotation by re-emitting seg/com remap based on rotation parity.`,
      `  if (${rotation} & 1) { __avr_ssd1309_cmd(0xA0); __avr_ssd1309_cmd(0xC0); }`,
      `}`,
      ``,
      `static inline void display_fillScreen(UI_COLOR_T color) {`,
      `  memset(__ssd1309_buffer, color ? 0xFF : 0x00, ${bufferSize});`,
      `}`,
      `static inline CuttlefishDisplayTarget* display_defaultTarget() { return &__tc_display; }`,
      `static inline int16_t display_width() { return ${w}; }`,
      `static inline int16_t display_height() { return ${h}; }`,
      `static inline void display_startWrite() { __tc_display; /* no-op for buffer */ }`,
      `static inline void display_endWrite() {}`,
      `static inline void display_setAddrWindow(int16_t x, int16_t y, int16_t w, int16_t h) {`,
      `  __avr_ssd1309_op_setAddrWindow(&__avr_ssd1309, x, y, w, h);`,
      `}`,
      `static inline void display_writePixels(UI_COLOR_T* pixels, uint32_t count) {`,
      `  __avr_ssd1309_op_writePixels(&__avr_ssd1309, pixels, count);`,
      `}`,
      ``,
      `// SSD1306 has no true partial refresh; display() flushes the full page`,
      `// buffer. Runtime dirty-rect tracking still minimizes draw calls INTO the`,
      `// buffer. Called once per frame after the dirty-rect union is drawn.`,
      `static inline void display_partial_refresh(int16_t x, int16_t y, int16_t w, int16_t h) {`,
      `  __avr_ssd1309_op_flush(&__avr_ssd1309, x, y, w, h);`,
      `}`,
      ``,
      `// ── Canvas (offscreen GFXcanvas16 for AA text / scroll compositing) ──`,
      `// On SSD1309 the panel IS a mono canvas; for AA text and scroll repair`,
      `// we still expose a 16-bit canvas (RGB565) and snap to mono at compositetime.`,
      `static inline uint16_t ssd_mono(uint16_t c);`,
      `static inline CuttlefishCanvas16* display_createCanvas(int16_t cw, int16_t ch) { return new CuttlefishCanvas16(cw, ch); }`,
      `static inline CuttlefishCanvas16* display_createCanvasPsram(int16_t cw, int16_t ch) {`,
      `  (void)cw; (void)ch;`,
      `  return nullptr;  // No PSRAM on AVR.`,
      `}`,
      `static inline void display_deleteCanvas(CuttlefishCanvas16* canvas) { delete canvas; }`,
      `static inline int16_t display_canvasWidth(CuttlefishCanvas16* c) { return c->width(); }`,
      `static inline int16_t display_canvasHeight(CuttlefishCanvas16* c) { return c->height(); }`,
      `static inline uint16_t* display_canvasBuffer(CuttlefishCanvas16* c) { return c->getBuffer(); }`,
      `static inline uint16_t display_canvasGetPixel(CuttlefishCanvas16* c, int16_t x, int16_t y) { return c->getPixel(x, y); }`,
      `static inline void display_canvasFillScreen(CuttlefishCanvas16* c, UI_COLOR_T color) { c->fillScreen(static_cast<uint16_t>(color)); }`,
      `static inline void display_canvasFillRect(CuttlefishCanvas16* c, int16_t x, int16_t y, int16_t w, int16_t h, UI_COLOR_T color) {`,
      `  c->fillRect(x, y, w, h, static_cast<uint16_t>(color));`,
      `}`,
      ``,
      `// ── Color snap (runtime uses 0xffff/0x0000; mono snap to 1/0) ─────────`,
      `static inline uint16_t ssd_mono(uint16_t c) { return c ? 0xFFFFu : 0x0000u; }`,
      ``,
      `// ── Target-polymorphic draw (panel + canvas share CuttlefishDisplayTarget*) ──`,
      `static inline void display_targetDrawPixel(CuttlefishDisplayTarget* t, int16_t x, int16_t y, UI_COLOR_T color) { t->drawPixel(x, y, ssd_mono(static_cast<uint16_t>(color))); }`,
      `static inline int16_t display_targetWidth(CuttlefishDisplayTarget* t) { return t->width(); }`,
      `static inline int16_t display_targetHeight(CuttlefishDisplayTarget* t) { return t->height(); }`,
      `static inline void display_targetDrawRGBBitmap(CuttlefishDisplayTarget* t, int16_t x, int16_t y, const UI_COLOR_T* b, int16_t bw, int16_t bh) {`,
      `  if (!b || bw <= 0 || bh <= 0) return;`,
      `  for (int16_t yy = 0; yy < bh; yy++) {`,
      `    for (int16_t xx = 0; xx < bw; xx++) {`,
      `      t->drawPixel(static_cast<int16_t>(x + xx), static_cast<int16_t>(y + yy), ssd_mono(static_cast<uint16_t>(b[static_cast<int32_t>(yy) * bw + xx])));`,
      `    }`,
      `  }`,
      `}`,
      `static inline void display_targetFillRect(CuttlefishDisplayTarget* t, int16_t x, int16_t y, int16_t w, int16_t h, UI_COLOR_T color) { t->fillRect(x, y, w, h, ssd_mono(static_cast<uint16_t>(color))); }`,
      `static inline void display_targetDrawFastHLine(CuttlefishDisplayTarget* t, int16_t x, int16_t y, int16_t w, UI_COLOR_T color) { t->drawFastHLine(x, y, w, ssd_mono(static_cast<uint16_t>(color))); }`,
      `static inline void display_targetDrawFastVLine(CuttlefishDisplayTarget* t, int16_t x, int16_t y, int16_t h, UI_COLOR_T color) { t->drawFastVLine(x, y, h, ssd_mono(static_cast<uint16_t>(color))); }`,
      `static inline void display_targetFillRoundRect(CuttlefishDisplayTarget* t, int16_t x, int16_t y, int16_t w, int16_t h, int16_t r, UI_COLOR_T color) { t->fillRoundRect(x, y, w, h, r, ssd_mono(static_cast<uint16_t>(color))); }`,
      `static inline void display_targetDrawRect(CuttlefishDisplayTarget* t, int16_t x, int16_t y, int16_t w, int16_t h, UI_COLOR_T color) { t->drawRect(x, y, w, h, ssd_mono(static_cast<uint16_t>(color))); }`,
      `static inline void display_targetDrawRoundRect(CuttlefishDisplayTarget* t, int16_t x, int16_t y, int16_t w, int16_t h, int16_t r, UI_COLOR_T color) { t->drawRoundRect(x, y, w, h, r, ssd_mono(static_cast<uint16_t>(color))); }`,
      `static inline void display_targetDrawLine(CuttlefishDisplayTarget* t, int16_t x0, int16_t y0, int16_t x1, int16_t y1, UI_COLOR_T color) { t->drawLine(x0, y0, x1, y1, ssd_mono(static_cast<uint16_t>(color))); }`,
      `static inline void display_targetFillCircle(CuttlefishDisplayTarget* t, int16_t x, int16_t y, int16_t r, UI_COLOR_T color) { t->fillCircle(x, y, r, ssd_mono(static_cast<uint16_t>(color))); }`,
      `static inline void display_targetDrawCircle(CuttlefishDisplayTarget* t, int16_t x, int16_t y, int16_t r, UI_COLOR_T color) { t->drawCircle(x, y, r, ssd_mono(static_cast<uint16_t>(color))); }`,
      `static inline void display_targetSetCursor(CuttlefishDisplayTarget* t, int16_t x, int16_t y) { t->setCursor(x, y); }`,
      `static inline void display_targetSetTextColor(CuttlefishDisplayTarget* t, UI_COLOR_T fg) { t->setTextColor(ssd_mono(static_cast<uint16_t>(fg))); }`,
      `static inline void display_targetSetTextColorBg(CuttlefishDisplayTarget* t, UI_COLOR_T fg, UI_COLOR_T bg) { t->setTextColor(ssd_mono(static_cast<uint16_t>(fg)), ssd_mono(static_cast<uint16_t>(bg))); }`,
      `static inline void display_targetSetTextSize(CuttlefishDisplayTarget* t, uint8_t s) { t->setTextSize(s); }`,
      `static inline void display_targetSetTextWrap(CuttlefishDisplayTarget* t, bool wp) { t->setTextWrap(wp); }`,
      `static inline void display_targetPrint(CuttlefishDisplayTarget* t, const char* s) { t->print(s); }`,
    ].join("\n"),
  };
};
