// The transpiler owns the out dir's git hygiene: an ignore-all .gitignore
// inside the resolved outDir keeps generated output (and the target's build
// tree) out of `git add .` no matter what the user named the dir — the
// scaffold's root .gitignore only covers the default `out/` name.

import { describe, it, expect } from "vitest";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { transpileFile } from "../../../packages/cuttlefish/src/transpile";

describe("outDir .gitignore (generated output stays untracked, any dir name)", () => {
  const PROJECT = "const limit: number = 10;\nlet out: number = 0;\nout = limit + 1;\n";
  const IGNORED = ["# Generated by cuttlefish on build — do not edit or commit.", "*", "!.gitignore", ""].join("\n");

  it("writes an ignore-all .gitignore at the dedicated outDir's root", async () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), "cf-gitignore-out-"));
    fs.writeFileSync(path.join(dir, "main.ts"), PROJECT);
    try {
      await transpileFile({
        inputFile: path.join(dir, "main.ts"),
        outDir: path.join(dir, "gen-out"),
        emitMode: "cpp",
        frameworkPackage: "@typecad/framework-native",
        emitMaps: false,
      });
      const gi = path.join(dir, "gen-out", ".gitignore");
      expect(fs.existsSync(gi)).toBe(true);
      expect(fs.readFileSync(gi, "utf8")).toBe(IGNORED);
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });

  it("in in-source emit mode ignores only the strategy's generated subdir, never the sources", async () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), "cf-gitignore-insrc-"));
    fs.writeFileSync(path.join(dir, "main.ts"), PROJECT);
    try {
      await transpileFile({
        inputFile: path.join(dir, "main.ts"),
        emitMode: "cpp",
        frameworkPackage: "@typecad/framework-native",
        emitMaps: false,
      });
      // Native emits to <sourceDir>/.build — the ignore lives there.
      expect(fs.existsSync(path.join(dir, ".build", ".gitignore"))).toBe(true);
      // The user's source dir itself carries no ignore-all.
      expect(fs.existsSync(path.join(dir, ".gitignore"))).toBe(false);
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });
});
