// ---------------------------------------------------------------------------
// cuttlefish-env.d.ts — Global type declarations
//
// Auto-generated by 'cuttlefish create'. Do not edit manually.
// ---------------------------------------------------------------------------

declare global {
  type Owned<T = any> = T;
  type Shared<T = any> = T;
  type Mutable<T = any> = T;

  type uint8_t = number;
  type int8_t = number;
  type uint16_t = number;
  type int16_t = number;
  type uint32_t = number;
  type int32_t = number;
  type size_t = number;
  type float = number;
  type double = number;
}

export {};
