// Auto-generated by typecad-hal (UI lowering). Do not edit.
import type { TextElement, ButtonElement, ViewElement, CheckElement, SelectElement, RadioElement, ProgressElement, RangeElement, InputElement, CanvasElement } from "@typecad/ui";
export interface ScreenTree {
  titlebar: ViewElement;
  title: TextElement;
  row2: ViewElement;
  uptime: TextElement;
  row3: ViewElement;
  sweep: ProgressElement;
  sweepPct: TextElement;
  row4: ViewElement;
  invert: ButtonElement;
  row5: ViewElement;
  alt: TextElement;
}
export const screen: ScreenTree;