// Auto-generated by typecad-hal (UI lowering). Do not edit.
import type { TextElement, ButtonElement, ViewElement, CheckElement, SelectElement, RadioElement, ProgressElement, RangeElement, InputElement, CanvasElement } from "@typecad/ui";
export interface ScreenTree {
  lvline: ViewElement;
  lvtxt: TextElement;
  ourline: ViewElement;
  ourtxt: TextElement;
  row2: ViewElement;
  uptime: TextElement;
  row4: ViewElement;
  invert: ButtonElement;
}
export const screen: ScreenTree;