// ---------------------------------------------------------------------------
// cuttlefish-env.d.ts — Virtual module declaration for '@typecad/board'
//
// Auto-generated by the cuttlefish transpiler. Do not edit manually.
// To change the board, update cuttlefish.config.ts and re-run the transpiler.
//
// Board: esp32_devkitc/esp32/procpu
// ---------------------------------------------------------------------------

declare global {
  type Owned<T = unknown> = T;
  type Shared<T = unknown> = T;
  type Mutable<T = unknown> = T;

  // C-style explicit number types recognized by the transpiler
  type uint8_t = number;
  type int8_t = number;
  type uint16_t = number;
  type int16_t = number;
  type uint32_t = number;
  type int32_t = number;
  type size_t = number;
  type float = number;
  type double = number;

  // Convenience helper for volatile variables in TypeCAD programs.
  // The transpiler detects calls to volatile() and emits the C++ volatile qualifier.
  declare function volatile<T>(value: T): T;


  // framework-esp32 ambient types:
  // - Timing: lowered via __tc_Timing (esp_timer_get_time, vTaskDelay).
  // - WDT: lowered via __tc_WDT (esp_task_wdt_*).
  // - Preferences: lowered via __tc_prefs (native NVS: nvs_open/set/get).
  // - EEPROM: not lowered (use Preferences / NVS instead).
  const Timing: {
    millis(): number;
    micros(): number;
    delay(ms: number): void;
    delayMicroseconds(us: number): void;
    freeHeap(): number;
  };

  const WDT: {
    enable(timeout?: number | string): void;
    reset(): void;
    disable(): void;
  };

  // Preferences: native NVS-backed key/value store (lowered via __tc_prefs).
  const Preferences: {
    begin(name: string, readOnly?: boolean): boolean;
    putInt(key: string, value: number): boolean;
    getInt(key: string, defaultValue?: number): number;
    putUInt(key: string, value: number): boolean;
    getUInt(key: string, defaultValue?: number): number;
    putFloat(key: string, value: number): boolean;
    getFloat(key: string, defaultValue?: number): number;
    putString(key: string, value: string): boolean;
    getString(key: string, defaultValue?: string): string;
    putBool(key: string, value: boolean): boolean;
    getBool(key: string, defaultValue?: boolean): boolean;
    remove(key: string): boolean;
    clear(): boolean;
    end(): void;
  };

}

declare module '@typecad/board' {
  export * from './board.js';
  export type Owned<T = any> = T;
  export type Shared<T = any> = T;
  export type Mutable<T = any> = T;
}

export {};
