// Auto-generated by cuttlefish (UI lowering). Do not edit.
import type { TextElement, ButtonElement, ViewElement, CheckElement } from "@typecad/ui";
export interface ScreenTree {
  header: ViewElement;
  title: TextElement;
  subtitle: TextElement;
  body: ViewElement;
  counter: TextElement;
  btn: ButtonElement;
  led: CheckElement;
  modeRow: ViewElement;
  mode: SelectElement;
  speedRow: ViewElement;
  speedSlow: RadioElement;
  speedFast: RadioElement;
  progress: ProgressElement;
  rangeRow: ViewElement;
  points: RangeElement;
  item1: TextElement;
  item2: TextElement;
  item3: TextElement;
  item4: TextElement;
  item5: TextElement;
  item6: TextElement;
  item7: TextElement;
  item8: TextElement;
  footer: ViewElement;
  hint: TextElement;
}
export const screen: ScreenTree;