// Auto-generated by cuttlefish (UI lowering). Do not edit.
import type { TextElement, ButtonElement, ViewElement } from "@typecad/ui";
export interface ScreenTree {
  // Index signature satisfies Record<string, ...>-typed mount() params.
  [id: string]: TextElement | ButtonElement | ViewElement;
  greeting: TextElement;
  btn: ButtonElement;
}
export const screen: ScreenTree;