// Auto-generated by cuttlefish (UI lowering). Do not edit.
import type { TextElement, ButtonElement, ViewElement, CheckElement, SelectElement, RadioElement, ProgressElement, RangeElement, InputElement } from "@typecad/ui";
export interface ScreenTree {
  home: ViewElement;
  navBody: ViewElement;
  navTitle: TextElement;
  linkSettings: TextElement;
  linkAbout: TextElement;
  navCounter: TextElement;
  settings: ViewElement;
  settingsBody: ViewElement;
  settingsTitle: TextElement;
  settingsHint: TextElement;
  backFromSettings: TextElement;
  about: ViewElement;
  aboutBody: ViewElement;
  aboutTitle: TextElement;
  aboutText: TextElement;
  backFromAbout: TextElement;
}
export const screen: ScreenTree;