// Auto-generated by cuttlefish (UI lowering). Do not edit.
import type { TextElement, ButtonElement, ViewElement, CheckElement, SelectElement, RadioElement, ProgressElement, RangeElement, InputElement, CanvasElement } from "@typecad/ui";
export interface ScreenTree {
  home: ViewElement;
  homeHeader: ViewElement;
  homeTitle: TextElement;
  homeSubtitle: TextElement;
  homeNav: ViewElement;
  homeFooter: ViewElement;
  homeHint: TextElement;
  homeNativeText: TextElement;
}
export const screen: ScreenTree;