// Auto-generated by cuttlefish (UI lowering). Do not edit.
import type { TextElement, ButtonElement, ViewElement, CheckElement, SelectElement, RadioElement, ProgressElement, RangeElement, InputElement, CanvasElement } from "@typecad/ui";
export interface ScreenTree {
  home: ViewElement;
  homeHeader: ViewElement;
  homeTitle: TextElement;
  homeSubtitle: TextElement;
  homeNav: ViewElement;
  homeFooter: ViewElement;
  homeHint: TextElement;
  homeNativeText: TextElement;
  typography: ViewElement;
  typeHeadings: ViewElement;
  typeStyle: ViewElement;
  typeSpacing: ViewElement;
  typeWrap: ViewElement;
  typeFont: ViewElement;
  typeArticle: ViewElement;
  typeAside: ViewElement;
  box: ViewElement;
  boxSize: ViewElement;
  boxFixed: ViewElement;
  boxMin: ViewElement;
  boxPadMargin: ViewElement;
  boxPadded: ViewElement;
  boxMargin: ViewElement;
  boxBorder: ViewElement;
  boxBordered: ViewElement;
  boxRadius: ViewElement;
  boxPerSide: ViewElement;
  boxShadowSec: ViewElement;
  boxShadowed: ViewElement;
  boxOutlined: ViewElement;
  boxAspect: ViewElement;
  boxAspectWide: ViewElement;
  boxAspectSquare: ViewElement;
}
export const screen: ScreenTree;