// Auto-generated by cuttlefish (UI lowering). Do not edit.
import type { TextElement, ButtonElement, ViewElement, CheckElement, SelectElement, RadioElement, ProgressElement, RangeElement, InputElement, CanvasElement } from "@typecad/ui";
interface HomeScreenGroup {
  homeHeader: ViewElement;
  homeTitle: TextElement;
  homeSubtitle: TextElement;
  homeNav: ViewElement;
  homeFooter: ViewElement;
  homeHint: TextElement;
  homeNativeText: TextElement;
}
interface TypographyScreenGroup {
  typeHeadings: ViewElement;
  typeStyle: ViewElement;
  typeSpacing: ViewElement;
  typeWrap: ViewElement;
  typeFont: ViewElement;
  typeArticle: ViewElement;
  typeAside: ViewElement;
  typeView: ViewElement;
}
interface RichtextScreenGroup {
  richMixed: ViewElement;
  richBreak: ViewElement;
  richNested: ViewElement;
}
interface BoxScreenGroup {
  boxSize: ViewElement;
  boxFixed: ViewElement;
  boxMin: ViewElement;
  boxMax: ViewElement;
  boxSizing: ViewElement;
  boxPadMargin: ViewElement;
  boxPadded: ViewElement;
  boxMargin: ViewElement;
  boxBorder: ViewElement;
  boxBordered: ViewElement;
  boxRadius: ViewElement;
  boxPerSide: ViewElement;
  boxBorderLong: ViewElement;
  boxShadowSec: ViewElement;
  boxShadowed: ViewElement;
  boxOutlined: ViewElement;
  boxAspect: ViewElement;
  boxAspectWide: ViewElement;
  boxAspectSquare: ViewElement;
}
interface LayoutScreenGroup {
  layerDemo: ViewElement;
  layerStage: ViewElement;
  layerBack: ViewElement;
  layerFront: ViewElement;
  layerCorner: ViewElement;
  visibilityDemo: ViewElement;
  visStack: ViewElement;
  visBefore: ViewElement;
  visHiddenAttr: ViewElement;
  visAfter1: ViewElement;
  visBefore2: ViewElement;
  visDisplayNone: ViewElement;
  visAfter2: ViewElement;
  visBefore3: ViewElement;
  visCollapsed: ViewElement;
  visAfter3: ViewElement;
  opacityDemo: ViewElement;
  opacityRow: ViewElement;
  opaqFull: ViewElement;
  opaqHalf: ViewElement;
  opaqFaint: ViewElement;
}
interface FlexScreenGroup {
  flexJustify: ViewElement;
  flexAlign: ViewElement;
  flexGrow: ViewElement;
  flexOrder: ViewElement;
}
interface TransformsScreenGroup {
  transformDemo: ViewElement;
  dotTranslate: ViewElement;
  dotScale: ViewElement;
  dotOrigin: ViewElement;
  dotRotate: ViewElement;
  dotPulse: ViewElement;
  transitionDemo: ViewElement;
  transitionBtn: ButtonElement;
}
interface FormsScreenGroup {
  formButton: ViewElement;
  formBtn: ButtonElement;
  formBtnCount: TextElement;
  formCheck: ViewElement;
  formCheck1: CheckElement;
  formSelect: ViewElement;
  formSelect1: SelectElement;
  formRadio: ViewElement;
  formRadio1: RadioElement;
  formRadio2: RadioElement;
  formProgress: ViewElement;
  formProg: ProgressElement;
  formRange: ViewElement;
  formRange1: RangeElement;
  formInput: ViewElement;
  formName: InputElement;
  formAge: InputElement;
  formDisabled: ViewElement;
  formDisabledBtn: ButtonElement;
}
interface MediaScreenGroup {
  imgFit: ViewElement;
  imgContain: TextElement;
  imgCover: TextElement;
  imgFill: TextElement;
  imgTransform: ViewElement;
  imgLogo: TextElement;
  canvasDemo: ViewElement;
  demoCanvas: CanvasElement;
}
interface ListsScreenGroup {
  demoList: TextElement;
}
interface KeyboardScreenGroup {
  kbInput: InputElement;
}
interface ScreenGroups {
  home: HomeScreenGroup;
  typography: TypographyScreenGroup;
  richtext: RichtextScreenGroup;
  box: BoxScreenGroup;
  layout: LayoutScreenGroup;
  flex: FlexScreenGroup;
  transforms: TransformsScreenGroup;
  forms: FormsScreenGroup;
  media: MediaScreenGroup;
  lists: ListsScreenGroup;
  keyboard: KeyboardScreenGroup;
}
export interface ScreenTree {
  home: ViewElement;
  homeHeader: ViewElement;
  homeTitle: TextElement;
  homeSubtitle: TextElement;
  homeNav: ViewElement;
  homeFooter: ViewElement;
  homeHint: TextElement;
  homeNativeText: TextElement;
  typography: ViewElement;
  typeHeadings: ViewElement;
  typeStyle: ViewElement;
  typeSpacing: ViewElement;
  typeWrap: ViewElement;
  typeFont: ViewElement;
  typeArticle: ViewElement;
  typeAside: ViewElement;
  typeView: ViewElement;
  richtext: ViewElement;
  richMixed: ViewElement;
  richBreak: ViewElement;
  richNested: ViewElement;
  box: ViewElement;
  boxSize: ViewElement;
  boxFixed: ViewElement;
  boxMin: ViewElement;
  boxMax: ViewElement;
  boxSizing: ViewElement;
  boxPadMargin: ViewElement;
  boxPadded: ViewElement;
  boxMargin: ViewElement;
  boxBorder: ViewElement;
  boxBordered: ViewElement;
  boxRadius: ViewElement;
  boxPerSide: ViewElement;
  boxBorderLong: ViewElement;
  boxShadowSec: ViewElement;
  boxShadowed: ViewElement;
  boxOutlined: ViewElement;
  boxAspect: ViewElement;
  boxAspectWide: ViewElement;
  boxAspectSquare: ViewElement;
  layout: ViewElement;
  layerDemo: ViewElement;
  layerStage: ViewElement;
  layerBack: ViewElement;
  layerFront: ViewElement;
  layerCorner: ViewElement;
  visibilityDemo: ViewElement;
  visStack: ViewElement;
  visBefore: ViewElement;
  visHiddenAttr: ViewElement;
  visAfter1: ViewElement;
  visBefore2: ViewElement;
  visDisplayNone: ViewElement;
  visAfter2: ViewElement;
  visBefore3: ViewElement;
  visCollapsed: ViewElement;
  visAfter3: ViewElement;
  opacityDemo: ViewElement;
  opacityRow: ViewElement;
  opaqFull: ViewElement;
  opaqHalf: ViewElement;
  opaqFaint: ViewElement;
  flex: ViewElement;
  flexJustify: ViewElement;
  flexAlign: ViewElement;
  flexGrow: ViewElement;
  flexOrder: ViewElement;
  transforms: ViewElement;
  transformDemo: ViewElement;
  dotTranslate: ViewElement;
  dotScale: ViewElement;
  dotOrigin: ViewElement;
  dotRotate: ViewElement;
  dotPulse: ViewElement;
  transitionDemo: ViewElement;
  transitionBtn: ButtonElement;
  forms: ViewElement;
  formButton: ViewElement;
  formBtn: ButtonElement;
  formBtnCount: TextElement;
  formCheck: ViewElement;
  formCheck1: CheckElement;
  formSelect: ViewElement;
  formSelect1: SelectElement;
  formRadio: ViewElement;
  formRadio1: RadioElement;
  formRadio2: RadioElement;
  formProgress: ViewElement;
  formProg: ProgressElement;
  formRange: ViewElement;
  formRange1: RangeElement;
  formInput: ViewElement;
  formName: InputElement;
  formAge: InputElement;
  formDisabled: ViewElement;
  formDisabledBtn: ButtonElement;
  media: ViewElement;
  imgFit: ViewElement;
  imgContain: TextElement;
  imgCover: TextElement;
  imgFill: TextElement;
  imgTransform: ViewElement;
  imgLogo: TextElement;
  canvasDemo: ViewElement;
  demoCanvas: CanvasElement;
  lists: ViewElement;
  demoList: TextElement;
  keyboard: ViewElement;
  kbInput: InputElement;
  groups: ScreenGroups;
}
export const screen: ScreenTree;