// ---------------------------------------------------------------------------
// cuttlefish-env.d.ts — Virtual module declaration for '@typecad/board'
//
// Auto-generated by the cuttlefish transpiler. Do not edit manually.
// To change the board, update cuttlefish.config.ts and re-run the transpiler.
//
// Board: @typecad/board-esp32-devkit
// ---------------------------------------------------------------------------

declare global {
  type Owned<T = unknown> = T;
  type Shared<T = unknown> = T;
  type Mutable<T = unknown> = T;

  // C-style explicit number types recognized by the transpiler
  type uint8_t = number;
  type int8_t = number;
  type uint16_t = number;
  type int16_t = number;
  type uint32_t = number;
  type int32_t = number;
  type size_t = number;
  type float = number;
  type double = number;

  // console — declared here (not pulled from lib.dom) so a project does not
  // need "dom" in tsconfig lib just to type console.log. Avoiding lib.dom
  // also keeps DOM global type names (Node, Element, Event, Document, ...)
  // out of scope, so a user class named e.g. `Node` is not shadowed by the
  // DOM global of the same name. Platforms may declaration-merge extra
  // members onto this interface via ambientTypeDeclarations().
  interface Console {
    log(...args: unknown[]): void;
    info(...args: unknown[]): void;
    debug(...args: unknown[]): void;
    warn(...args: unknown[]): void;
    error(...args: unknown[]): void;
  }
  const console: Console;

  // Convenience helper for volatile variables in TypeCAD programs.
  // The transpiler detects calls to volatile() and emits the C++ volatile qualifier.
  declare function volatile<T>(value: T): T;

  // JS-style timers
  declare function setInterval(handler: () => void, timeout?: number): number;
  declare function setTimeout(handler: () => void, timeout?: number): number;
  declare function clearInterval(id: number): void;
  declare function clearTimeout(id: number): void;

  // Persistent key/value store (ZMS-backed Zephyr settings — see
  // src/lowering/preferences.ts). begin/end carry the namespace prefix;
  // typed put/get round-trip through an in-RAM cache + settings_save_one.
  const Preferences: {
    begin(name: string, readOnly?: boolean): void;
    end(): void;
    clear(): void;
    putInt(key: string, value: number): void;
    getInt(key: string, defaultValue: number): number;
    putUInt(key: string, value: number): void;
    getUInt(key: string, defaultValue: number): number;
    putBool(key: string, value: boolean): void;
    getBool(key: string, defaultValue: boolean): boolean;
    putFloat(key: string, value: number): void;
    getFloat(key: string, defaultValue: number): number;
    putString(key: string, value: string): void;
    getString(key: string, defaultValue: string): string;
    remove(key: string): void;
  };
}

declare module '@typecad/board' {
  export * from '@typecad/board-esp32-devkit';
  export type Owned<T = any> = T;
  export type Shared<T = any> = T;
  export type Mutable<T = any> = T;
}

export {};
