// ---------------------------------------------------------------------------
// Board namespace facade
// Generated by TypeCode Board Wizard
// ---------------------------------------------------------------------------

import type {
  IDigitalPin,
  IPWMPin,
  IAnalogInput,
  IInterruptPin,
  II2CBus,
  ISPIBus,
  ISerialPort,
  BoardDefinition,
} from '@typecode/core';

import {
  D0,
  D1,
  D2,
  D3,
  D4,
  D5,
  D6,
  D7,
  D8,
  D9,
  D10,
  D11,
  D12,
  D13,
  A0,
  A1,
  A2,
  A3,
  A4,
  A5,
} from './pins';

import { I2C0, SPI0, UART0 } from './peripherals';
import { ArduinoNano } from './index';

// ---------------------------------------------------------------------------
// Type-safe pin collections
// ---------------------------------------------------------------------------

export interface DigitalPins {
  D0: IDigitalPin;
  D1: IDigitalPin;
  D2: IDigitalPin & IInterruptPin;
  D3: IDigitalPin & IInterruptPin;
  D4: IDigitalPin;
  D5: IDigitalPin;
  D6: IDigitalPin;
  D7: IDigitalPin;
  D8: IDigitalPin;
  D9: IDigitalPin;
  D10: IDigitalPin;
  D11: IDigitalPin;
  D12: IDigitalPin;
  D13: IDigitalPin;
  A0: IDigitalPin;
  A1: IDigitalPin;
  A2: IDigitalPin;
  A3: IDigitalPin;
  A4: IDigitalPin;
  A5: IDigitalPin;
}

export interface AnalogPins {
  A0: IAnalogInput;
  A1: IAnalogInput;
  A2: IAnalogInput;
  A3: IAnalogInput;
  A4: IAnalogInput;
  A5: IAnalogInput;
}

// ---------------------------------------------------------------------------
// Board facade
// ---------------------------------------------------------------------------

export interface IBoard {
  /** Board definition manifest (read-only metadata). */
  readonly definition: BoardDefinition;

  // ---- Individual pins ---------------------------------------------------
  readonly D0: IDigitalPin;
  readonly D1: IDigitalPin;
  readonly D2: IDigitalPin & IInterruptPin;
  readonly D3: IDigitalPin & IInterruptPin;
  readonly D4: IDigitalPin;
  readonly D5: IDigitalPin;
  readonly D6: IDigitalPin;
  readonly D7: IDigitalPin;
  readonly D8: IDigitalPin;
  readonly D9: IDigitalPin;
  readonly D10: IDigitalPin;
  readonly D11: IDigitalPin;
  readonly D12: IDigitalPin;
  readonly D13: IDigitalPin;
  readonly A0: IDigitalPin & IAnalogInput;
  readonly A1: IDigitalPin & IAnalogInput;
  readonly A2: IDigitalPin & IAnalogInput;
  readonly A3: IDigitalPin & IAnalogInput;
  readonly A4: IDigitalPin & IAnalogInput;
  readonly A5: IDigitalPin & IAnalogInput;

  // ---- Peripherals -------------------------------------------------------
  readonly I2C0: II2CBus;
  readonly SPI0: ISPIBus;
  readonly UART0: ISerialPort;

  // ---- Pin collections ---------------------------------------------------
  readonly digital: DigitalPins;
  readonly analog: AnalogPins;
}

// ---------------------------------------------------------------------------
// Singleton board instance
// ---------------------------------------------------------------------------

/**
 * `Board` — the Arduino Nano expressed as a fully-typed namespace.
 */
export const Board: IBoard = {
  definition: ArduinoNano,

  // Pins
  D0,
  D1,
  D2,
  D3,
  D4,
  D5,
  D6,
  D7,
  D8,
  D9,
  D10,
  D11,
  D12,
  D13,
  A0,
  A1,
  A2,
  A3,
  A4,
  A5,

  // Peripherals
  I2C0,
  SPI0,
  UART0,

  // Collections
  digital: { D0, D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11, D12, D13, A0, A1, A2, A3, A4, A5 },
  analog: { A0, A1, A2, A3, A4, A5 },
} as IBoard;

export default Board;
