// ---------------------------------------------------------------------------
// @typecode/board-arduino-nano — Board definition manifest
// Generated by TypeCode Board Wizard
// ---------------------------------------------------------------------------

import type { BoardDefinition } from '@typecode/core';

// Re-export the platform strategy so the CLI can resolve it automatically
export { BoardStrategy } from './strategy';

// ---------------------------------------------------------------------------
// Default capability flags
// ---------------------------------------------------------------------------

const NO  = false as const;
const YES = true  as const;

// ---------------------------------------------------------------------------
// Board definition
// ---------------------------------------------------------------------------

export const ArduinoNano: BoardDefinition = {
  id: 'arduino-nano',
  name: 'Arduino Nano',
  vendor: 'Arduino',
  description: 'Arduino Nano — ATmega328P',
  architecture: 'avr',
  mcu: 'ATmega328P',
  clockSpeed: 16000000,

  // ----- Memory ------------------------------------------------------------
  memory: {
    flash:  32768,
    sram:   2048,
    eeprom: 1024,
  },

  // ----- Pins --------------------------------------------------------------
  pins: {
    all: [
  { number: 0, gpio: 0, name: 'D0', capabilities: {
      digitalInput: true, digitalOutput: true,
      analogInput: false, analogOutput: false,
      pwm: false, interrupt: false,
      pullUp: true, pullDown: false,
      touch: false, openDrain: false,
    }, functions: [{ type: 'uart', instance: 0, role: 'rx' }], aliases: ['RX'] },
  { number: 1, gpio: 1, name: 'D1', capabilities: {
      digitalInput: true, digitalOutput: true,
      analogInput: false, analogOutput: false,
      pwm: false, interrupt: false,
      pullUp: true, pullDown: false,
      touch: false, openDrain: false,
    }, functions: [{ type: 'uart', instance: 0, role: 'tx' }], aliases: ['TX'] },
  { number: 2, gpio: 2, name: 'D2', capabilities: {
      digitalInput: true, digitalOutput: true,
      analogInput: false, analogOutput: false,
      pwm: false, interrupt: true,
      pullUp: true, pullDown: false,
      touch: false, openDrain: false,
    } },
  { number: 3, gpio: 3, name: 'D3', capabilities: {
      digitalInput: true, digitalOutput: true,
      analogInput: false, analogOutput: false,
      pwm: false, interrupt: true,
      pullUp: true, pullDown: false,
      touch: false, openDrain: false,
    } },
  { number: 4, gpio: 4, name: 'D4', capabilities: {
      digitalInput: true, digitalOutput: true,
      analogInput: false, analogOutput: false,
      pwm: false, interrupt: false,
      pullUp: true, pullDown: false,
      touch: false, openDrain: false,
    } },
  { number: 5, gpio: 5, name: 'D5', capabilities: {
      digitalInput: true, digitalOutput: true,
      analogInput: false, analogOutput: false,
      pwm: false, interrupt: false,
      pullUp: true, pullDown: false,
      touch: false, openDrain: false,
    } },
  { number: 6, gpio: 6, name: 'D6', capabilities: {
      digitalInput: true, digitalOutput: true,
      analogInput: false, analogOutput: false,
      pwm: false, interrupt: false,
      pullUp: true, pullDown: false,
      touch: false, openDrain: false,
    } },
  { number: 7, gpio: 7, name: 'D7', capabilities: {
      digitalInput: true, digitalOutput: true,
      analogInput: false, analogOutput: false,
      pwm: false, interrupt: false,
      pullUp: true, pullDown: false,
      touch: false, openDrain: false,
    } },
  { number: 8, gpio: 8, name: 'D8', capabilities: {
      digitalInput: true, digitalOutput: true,
      analogInput: false, analogOutput: false,
      pwm: false, interrupt: false,
      pullUp: true, pullDown: false,
      touch: false, openDrain: false,
    } },
  { number: 9, gpio: 9, name: 'D9', capabilities: {
      digitalInput: true, digitalOutput: true,
      analogInput: false, analogOutput: false,
      pwm: false, interrupt: false,
      pullUp: true, pullDown: false,
      touch: false, openDrain: false,
    } },
  { number: 10, gpio: 10, name: 'D10', capabilities: {
      digitalInput: true, digitalOutput: true,
      analogInput: false, analogOutput: false,
      pwm: false, interrupt: false,
      pullUp: true, pullDown: false,
      touch: false, openDrain: false,
    }, functions: [{ type: 'spi', instance: 0, role: 'ss' }], aliases: ['SS'] },
  { number: 11, gpio: 11, name: 'D11', capabilities: {
      digitalInput: true, digitalOutput: true,
      analogInput: false, analogOutput: false,
      pwm: false, interrupt: false,
      pullUp: true, pullDown: false,
      touch: false, openDrain: false,
    }, functions: [{ type: 'spi', instance: 0, role: 'mosi' }], aliases: ['MOSI'] },
  { number: 12, gpio: 12, name: 'D12', capabilities: {
      digitalInput: true, digitalOutput: true,
      analogInput: false, analogOutput: false,
      pwm: false, interrupt: false,
      pullUp: true, pullDown: false,
      touch: false, openDrain: false,
    }, functions: [{ type: 'spi', instance: 0, role: 'miso' }], aliases: ['MISO'] },
  { number: 13, gpio: 13, name: 'D13', capabilities: {
      digitalInput: true, digitalOutput: true,
      analogInput: false, analogOutput: false,
      pwm: false, interrupt: false,
      pullUp: true, pullDown: false,
      touch: false, openDrain: false,
    }, functions: [{ type: 'spi', instance: 0, role: 'sck' }], aliases: ['LED', 'SCK'], onboardLed: true },
  { number: 14, gpio: 14, name: 'A0', capabilities: {
      digitalInput: true, digitalOutput: true,
      analogInput: true, analogOutput: false,
      pwm: false, interrupt: false,
      pullUp: true, pullDown: false,
      touch: false, openDrain: false,
    } },
  { number: 15, gpio: 15, name: 'A1', capabilities: {
      digitalInput: true, digitalOutput: true,
      analogInput: true, analogOutput: false,
      pwm: false, interrupt: false,
      pullUp: true, pullDown: false,
      touch: false, openDrain: false,
    } },
  { number: 16, gpio: 16, name: 'A2', capabilities: {
      digitalInput: true, digitalOutput: true,
      analogInput: true, analogOutput: false,
      pwm: false, interrupt: false,
      pullUp: true, pullDown: false,
      touch: false, openDrain: false,
    } },
  { number: 17, gpio: 17, name: 'A3', capabilities: {
      digitalInput: true, digitalOutput: true,
      analogInput: true, analogOutput: false,
      pwm: false, interrupt: false,
      pullUp: true, pullDown: false,
      touch: false, openDrain: false,
    } },
  { number: 18, gpio: 18, name: 'A4', capabilities: {
      digitalInput: true, digitalOutput: true,
      analogInput: true, analogOutput: false,
      pwm: false, interrupt: false,
      pullUp: true, pullDown: false,
      touch: false, openDrain: false,
    }, functions: [{ type: 'i2c', instance: 0, role: 'sda' }], aliases: ['SDA'] },
  { number: 19, gpio: 19, name: 'A5', capabilities: {
      digitalInput: true, digitalOutput: true,
      analogInput: true, analogOutput: false,
      pwm: false, interrupt: false,
      pullUp: true, pullDown: false,
      touch: false, openDrain: false,
    }, functions: [{ type: 'i2c', instance: 0, role: 'scl' }], aliases: ['SCL'] },
    ],

    digital: ['D0', 'D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13', 'A0', 'A1', 'A2', 'A3', 'A4', 'A5'],
    analog: ['A0', 'A1', 'A2', 'A3', 'A4', 'A5'],
    pwm: [],

    i2c: {
      0: { sda: 'A4', scl: 'A5' },
    },
    spi: {
      0: { mosi: 'D11', miso: 'D12', sck: 'D13', cs: 'D10' },
    },
    uart: {
      0: { tx: 'D1', rx: 'D0' },
    },

    led: 'D13',
  },

  // ----- Peripherals -------------------------------------------------------
  peripherals: {
    i2c: [{ instance: 0, defaultPins: { sda: 'A4', scl: 'A5' } }],
    spi: [{ instance: 0, defaultPins: { mosi: 'D11', miso: 'D12', sck: 'D13', cs: 'D10' } }],
    uart: [{ instance: 0, defaultPins: { tx: 'D1', rx: 'D0' } }],
    adc: [{ instance: 0, channels: 6, resolution: 10, referenceVoltage: 3.3 }],
    pwm: { channels: 6, resolution: 8, maxFrequency: 1000 },
  },

  // ----- Features ----------------------------------------------------------
  features: {
    multicore: false,
    coreCount: 1,
    deepSleep: false,
    watchdog: true,
    externalInterrupts: true,
    hardwareRng: false,
    fpu: false,
  },

  // ----- Build config ------------------------------------------------------
  build: {
    arduino: 'arduino:avr:nano',
    extraFlags: [],
    defines: {
      F_CPU: '16000000UL',
      ARDUINO: '10819',
    },
  },
};

export default ArduinoNano;

// ---------------------------------------------------------------------------
// Re-exports — convenience barrel
// ---------------------------------------------------------------------------

// Typed pins
export { D0, D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11, D12, D13, A0, A1, A2, A3, A4, A5 } from './pins';

// Re-export HIGH/LOW constants from core
export { HIGH, LOW } from '@typecode/core';

// Peripheral bus instances
export { I2C0, SPI0, UART0 } from './peripherals';

// Timing / utility functions
export { delay, millis, micros, delayMicroseconds, map, constrain } from './timing';

// Analog helpers
export { AnalogReference, analogReference } from './analog';

// Interrupt helpers
export { noInterrupts, interrupts, attachInterrupt, detachInterrupt } from './interrupts';

// Board namespace (single-import convenience)
export { Board } from './board';
export type { IBoard, DigitalPins, AnalogPins } from './board';
