// ---------------------------------------------------------------------------
// @typecode/board-arduino-nano — Typed pin exports
// Generated by TypeCode Board Wizard
// ---------------------------------------------------------------------------

import type {
  IDigitalPin,
  IPWMPin,
  IAnalogInput,
  IInterruptPin,
} from '@typecode/core';
import { pinNumber } from '@typecode/core';

// ---------------------------------------------------------------------------
// Internal stub factories (no-op at runtime; consumed by transpiler)
// ---------------------------------------------------------------------------

function createDigitalPin(pin: number, gpio: number): IDigitalPin {
  return { number: pinNumber(pin), gpio: pinNumber(gpio) } as IDigitalPin;
}

function createPWMPin(pin: number, gpio: number): IPWMPin {
  return { number: pinNumber(pin), gpio: pinNumber(gpio) } as IPWMPin;
}

function createAnalogPin(pin: number, gpio: number): IAnalogInput {
  return { number: pinNumber(pin), gpio: pinNumber(gpio) } as IAnalogInput;
}

function createInterruptPin(pin: number, gpio: number): IDigitalPin & IInterruptPin {
  return { number: pinNumber(pin), gpio: pinNumber(gpio) } as IDigitalPin & IInterruptPin;
}

function createPWMInterruptPin(pin: number, gpio: number): IDigitalPin & IPWMPin & IInterruptPin {
  return { number: pinNumber(pin), gpio: pinNumber(gpio) } as IDigitalPin & IPWMPin & IInterruptPin;
}

function createAnalogPWMPin(pin: number, gpio: number): IDigitalPin & IPWMPin & IAnalogInput {
  return { number: pinNumber(pin), gpio: pinNumber(gpio) } as IDigitalPin & IPWMPin & IAnalogInput;
}

function createFullPin(pin: number, gpio: number): IDigitalPin & IPWMPin & IAnalogInput & IInterruptPin {
  return { number: pinNumber(pin), gpio: pinNumber(gpio) } as IDigitalPin & IPWMPin & IAnalogInput & IInterruptPin;
}

// ---------------------------------------------------------------------------
// Pin exports
// ---------------------------------------------------------------------------

export const D0: IDigitalPin = createDigitalPin(0, 0);
export const D1: IDigitalPin = createDigitalPin(1, 1);
export const D2: IDigitalPin & IInterruptPin = createInterruptPin(2, 2);
export const D3: IDigitalPin & IInterruptPin = createInterruptPin(3, 3);
export const D4: IDigitalPin = createDigitalPin(4, 4);
export const D5: IDigitalPin = createDigitalPin(5, 5);
export const D6: IDigitalPin = createDigitalPin(6, 6);
export const D7: IDigitalPin = createDigitalPin(7, 7);
export const D8: IDigitalPin = createDigitalPin(8, 8);
export const D9: IDigitalPin = createDigitalPin(9, 9);
export const D10: IDigitalPin = createDigitalPin(10, 10);
export const D11: IDigitalPin = createDigitalPin(11, 11);
export const D12: IDigitalPin = createDigitalPin(12, 12);
export const D13: IDigitalPin = createDigitalPin(13, 13);
export const A0: IAnalogInput = createAnalogPin(14, 14);
export const A1: IAnalogInput = createAnalogPin(15, 15);
export const A2: IAnalogInput = createAnalogPin(16, 16);
export const A3: IAnalogInput = createAnalogPin(17, 17);
export const A4: IAnalogInput = createAnalogPin(18, 18);
export const A5: IAnalogInput = createAnalogPin(19, 19);

// ---------------------------------------------------------------------------
// Convenience aliases
// ---------------------------------------------------------------------------

/** On-board LED. */
export const LED = D13;

/** I2C data line. */
export const SDA = A4;
/** I2C clock line. */
export const SCL = A5;

/** SPI master-out / slave-in. */
export const MOSI = D11;
/** SPI master-in / slave-out. */
export const MISO = D12;
/** SPI clock. */
export const SCK = D13;
/** SPI slave select. */
export const SS = D10;

/** UART transmit. */
export const TX = D1;
/** UART receive. */
export const RX = D0;
