import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { scaffoldEspIdfProject } from '../../../packages/framework-esp32/src/toolchain/scaffold';

let tmpDir: string;

beforeEach(() => {
  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'esp32-scaffold-'));
});
afterEach(() => {
  fs.rmSync(tmpDir, { recursive: true, force: true });
});

describe('scaffoldEspIdfProject — idf_component.yml', () => {
  it('writes main/idf_component.yml when managed is non-empty', () => {
    scaffoldEspIdfProject(tmpDir, 'esp32s3', {
      managed: { 'espressif/esp_wifi': '^1.0', 'espressif/mdns': '^1.0' },
      local: [],
    });
    const ymlPath = path.join(tmpDir, 'main', 'idf_component.yml');
    expect(fs.existsSync(ymlPath)).toBe(true);
    const content = fs.readFileSync(ymlPath, 'utf8');
    expect(content).toContain('dependencies:');
    expect(content).toContain('espressif/esp_wifi: "^1.0"');
    expect(content).toContain('espressif/mdns: "^1.0"');
    expect(content).toContain('Auto-generated by @typecad/framework-esp32');
  });

  it('does not write idf_component.yml when managed is empty and none existed', () => {
    scaffoldEspIdfProject(tmpDir, 'esp32s3', { managed: {}, local: [] });
    expect(fs.existsSync(path.join(tmpDir, 'main', 'idf_component.yml'))).toBe(false);
  });

  it('deletes a stale idf_component.yml when managed becomes empty', () => {
    const ymlPath = path.join(tmpDir, 'main', 'idf_component.yml');
    fs.mkdirSync(path.dirname(ymlPath), { recursive: true });
    fs.writeFileSync(ymlPath, 'dependencies:\n  foo: "^1.0"\n', 'utf8');

    scaffoldEspIdfProject(tmpDir, 'esp32s3', { managed: {}, local: [] });
    expect(fs.existsSync(ymlPath)).toBe(false);
  });

  it('is idempotent — stable content on repeat calls with same deps', () => {
    const components = { managed: { 'espressif/esp_wifi': '^1.0' }, local: [] };
    scaffoldEspIdfProject(tmpDir, 'esp32s3', components);
    const ymlPath = path.join(tmpDir, 'main', 'idf_component.yml');
    const first = fs.readFileSync(ymlPath, 'utf8');

    scaffoldEspIdfProject(tmpDir, 'esp32s3', components);
    const second = fs.readFileSync(ymlPath, 'utf8');

    // Content-equality check (writeIfChanged should skip when identical).
    expect(second).toBe(first);
  });

  it('omits components arg → no idf_component.yml, no EXTRA_COMPONENT_DIRS (no regression)', () => {
    scaffoldEspIdfProject(tmpDir, 'esp32s3');
    expect(fs.existsSync(path.join(tmpDir, 'main', 'idf_component.yml'))).toBe(false);
    const cmake = fs.readFileSync(path.join(tmpDir, 'CMakeLists.txt'), 'utf8');
    expect(cmake).not.toContain('EXTRA_COMPONENT_DIRS');
  });
});

describe('scaffoldEspIdfProject — EXTRA_COMPONENT_DIRS', () => {
  it('emits EXTRA_COMPONENT_DIRS block when local is non-empty', () => {
    scaffoldEspIdfProject(tmpDir, 'esp32s3', {
      managed: {},
      local: [
        path.join(tmpDir, 'components', 'my_sensor'),
        path.join(tmpDir, 'components', 'display'),
      ],
    });
    const cmake = fs.readFileSync(path.join(tmpDir, 'CMakeLists.txt'), 'utf8');
    expect(cmake).toContain('set(EXTRA_COMPONENT_DIRS');
    expect(cmake).toContain('components/my_sensor');
    expect(cmake).toContain('components/display');
    expect(cmake).toContain(')');
  });

  it('places EXTRA_COMPONENT_DIRS before the include(project.cmake) line', () => {
    scaffoldEspIdfProject(tmpDir, 'esp32s3', {
      managed: {},
      local: [path.join(tmpDir, 'components', 'foo')],
    });
    const cmake = fs.readFileSync(path.join(tmpDir, 'CMakeLists.txt'), 'utf8');
    const setIdx = cmake.indexOf('set(EXTRA_COMPONENT_DIRS');
    const includeIdx = cmake.indexOf('include($ENV{IDF_PATH}');
    expect(setIdx).toBeGreaterThan(-1);
    expect(includeIdx).toBeGreaterThan(setIdx);
  });
});
