// ---------------------------------------------------------------------------
// Polyfill types
//
// Types for runtime polyfill generation.
// ---------------------------------------------------------------------------

export type PolyfillDomain = "standard" | "arduino" | "embedded";
export type TargetProfile = "generic" | "arduino" | (string & {});

export interface RuntimePolyfillIR {
  kind: "polyfill";
  id: string;
  domain: PolyfillDomain;
  requiredIncludes: string[];
  forwardDeclarations: string[];
  helperStructs: string[];
  helperFunctions: string[];
  shimMacros: string[];
  dependencies: string[];
  /**
   * Variable names of async task instances generated by the async polyfill.
   * The emitter uses these to call `taskVar.run()` inside `loop()`.
   */
  asyncTaskVars?: string[];
  /**
   * True when the Promise/MicrotaskQueue runtime was emitted (requires <functional>/<vector>).
   * False for architectures like AVR that lack the C++ standard library.
   * When false, the emitter must NOT emit typecode_pump_microtasks() calls.
   */
  hasPromiseRuntime?: boolean;
}

// Standard library support by architecture
export interface StdLibSupport {
  hasVector: boolean;
  hasString: boolean;
  hasIostream: boolean;
  hasExceptions: boolean;
  hasRTTI: boolean;
  recommendedArrayImpl: "std_vector" | "static_array";
  recommendedStringImpl: "std_string" | "static_string";
}

export const STDLIB_SUPPORT: Record<string, StdLibSupport> = {
  avr: {
    hasVector: false,
    hasString: false,
    hasIostream: false,
    hasExceptions: false,
    hasRTTI: false,
    recommendedArrayImpl: "static_array",
    recommendedStringImpl: "static_string",
  },
  esp32: {
    hasVector: true,
    hasString: true,
    hasIostream: true,
    hasExceptions: true,
    hasRTTI: true,
    recommendedArrayImpl: "std_vector",
    recommendedStringImpl: "std_string",
  },
  esp8266: {
    hasVector: true,
    hasString: true,
    hasIostream: true,
    hasExceptions: true,
    hasRTTI: true,
    recommendedArrayImpl: "std_vector",
    recommendedStringImpl: "std_string",
  },
  rp2040: {
    hasVector: true,
    hasString: true,
    hasIostream: true,
    hasExceptions: true,
    hasRTTI: true,
    recommendedArrayImpl: "std_vector",
    recommendedStringImpl: "std_string",
  },
  samd: {
    hasVector: true,
    hasString: true,
    hasIostream: true,
    hasExceptions: true,
    hasRTTI: true,
    recommendedArrayImpl: "std_vector",
    recommendedStringImpl: "std_string",
  },
  megaavr: {
    hasVector: false,
    hasString: false,
    hasIostream: false,
    hasExceptions: false,
    hasRTTI: false,
    recommendedArrayImpl: "static_array",
    recommendedStringImpl: "static_string",
  },
  default: {
    hasVector: true,
    hasString: true,
    hasIostream: true,
    hasExceptions: true,
    hasRTTI: true,
    recommendedArrayImpl: "std_vector",
    recommendedStringImpl: "std_string",
  },
};

export function getStdLibSupport(architecture?: string): StdLibSupport {
  if (!architecture) return STDLIB_SUPPORT.default;
  return STDLIB_SUPPORT[architecture.toLowerCase()] ?? STDLIB_SUPPORT.default;}
