import type { SourceSpan } from './types';
import type { ProgramIR } from './ir';
export type PolyfillDomain = "standard" | "arduino" | "embedded";
export type TargetProfile = "generic" | "arduino" | (string & {});
/**
 * A polyfill definition: the contract between the CLI (detection) and
 * framework packages (C++ code generation).
 *
 * Detection logic lives in the CLI; C++ generation is delegated to the
 * active framework package via the `generate` method.
 */
export interface PolyfillDefinition {
    id: string;
    name: string;
    description: string;
    domains: PolyfillDomain[];
    detect: (program: ProgramIR, context: PolyfillContext) => PolyfillNeed[];
    generate: (needs: PolyfillNeed[], context: PolyfillContext) => RuntimePolyfillIR;
}
export interface RuntimePolyfillIR {
    kind: "polyfill";
    id: string;
    domain: PolyfillDomain;
    requiredIncludes: string[];
    forwardDeclarations: string[];
    helperStructs: string[];
    helperFunctions: string[];
    shimMacros: string[];
    dependencies: string[];
    /**
     * Statements to be injected into setup() function.
     * These will be prepended to the setup() function body.
     */
    setupStatements?: string[];
    /**
     * Variable names of async task instances generated by the async polyfill.
     * The emitter uses these to call `taskVar.run()` inside `loop()`.
     * e.g. ["blinkLedTask", "myTask"]
     */
    asyncTaskVars?: string[];
    /**
     * True when the Promise/MicrotaskQueue runtime was emitted (requires <functional>/<vector>).
     * False for architectures like AVR that lack the C++ standard library.
     * When false, the emitter must NOT emit ts2cpp_pump_microtasks() calls.
     */
    hasPromiseRuntime?: boolean;
}
export interface PolyfillContext {
    target: TargetProfile;
    architecture?: string;
    usedIdentifiers: Set<string>;
    config?: PolyfillConfig;
}
export interface PolyfillNeed {
    id: string;
    sourceSpan: SourceSpan;
    details: Record<string, any>;
}
export interface PolyfillConfig {
    console?: {
        enabled: boolean;
        target: "auto" | "serial" | "cout" | "none";
        useFlashStrings?: boolean;
        /** Default baud rate for Serial.begin() when auto-injected. Default: 9600 */
        baudRate?: number;
        /** Automatically inject Serial.begin(baudRate) in setup() when console.log/warn/error is used. Default: true */
        autoInjectSerialBegin?: boolean;
    };
    async?: {
        enabled: boolean;
        mode: "state-machine" | "stub" | "none";
        scheduler?: boolean;
    };
    arrays?: {
        enabled: boolean;
        prefer: "auto" | "std_vector" | "static_array" | "micro_vector";
        staticMaxSize?: number;
        microMaxSize?: number;
    };
    strings?: {
        enabled: boolean;
        prefer: "auto" | "std_string" | "static_string";
        staticMaxLen?: number;
    };
    exceptions?: {
        enabled: boolean | "auto";
        fallback: "error_code" | "noop";
    };
}
export declare const DEFAULT_POLYFILL_CONFIG: PolyfillConfig;
export interface StdLibSupport {
    hasVector: boolean;
    hasString: boolean;
    hasIostream: boolean;
    hasExceptions: boolean;
    hasRTTI: boolean;
    recommendedArrayImpl: "std_vector" | "static_array";
    recommendedStringImpl: "std_string" | "static_string";
}
export declare const STDLIB_SUPPORT: Record<string, StdLibSupport>;
export declare function getStdLibSupport(architecture?: string): StdLibSupport;
//# sourceMappingURL=polyfill-types.d.ts.map