// ---------------------------------------------------------------------------
// Project scaffolding templates for `typehal init`
//
// Pure functions that return file content strings. Each function takes a
// normalized options object and produces the content for one project file.
// ---------------------------------------------------------------------------

import type { ArchitectureIdentifier } from '@typehal/core';

// ---------------------------------------------------------------------------
// Options passed to every template
// ---------------------------------------------------------------------------

export interface InitProjectOptions {
  /** Project name (e.g., 'my-blink') */
  projectName: string;
  /** Board identifier from the built-in registry (e.g., 'arduino-uno') */
  boardId: string;
  /** Human-readable board name (e.g., 'Arduino Uno') */
  boardDisplayName: string;
  /** Target architecture (e.g., 'avr') */
  architecture: ArchitectureIdentifier;
  /** npm package name for the board (e.g., '@typehal/board-arduino-uno') */
  boardPackage: string;
  /** npm package name for the framework (e.g., '@typehal/framework-arduino') */
  frameworkPackage: string;
  /** Framework identifier (e.g., 'arduino', 'avr', or any custom framework) */
  framework: string;
  /** Framework-specific build target identifier (optional) */
  buildTarget?: string;
  /** MCU part number */
  mcu: string;
  /** Serial baud rate */
  baudRate: number;
  /** Whether to generate a starter sketch */
  includeSketch: boolean;
  /** Toolchain type (e.g., 'arduino-cli'). Defaults to 'arduino-cli' when not set. */
  toolchainType?: string;
}

// ---------------------------------------------------------------------------
// package.json
// ---------------------------------------------------------------------------

export function generateProjectPackageJson(options: InitProjectOptions): string {
  const { projectName, boardPackage, frameworkPackage } = options;

  // Derive a reasonable default port hint from the OS
  const portHint = process.platform === 'win32' ? 'COM4' : '/dev/ttyACM0';

  return `{
  "name": "${projectName}",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "build": "typehal build",
    "compile": "typehal build --compile",
    "upload": "typehal build --compile --upload --port ${portHint}",
    "monitor": "typehal build --compile --upload --monitor --port ${portHint}"
  },
  "dependencies": {
    "@typehal/core": "^0.1.0",
    "${boardPackage}": "^0.1.0",
    "${frameworkPackage}": "^0.1.0"
  }
}
`;
}

// ---------------------------------------------------------------------------
// tsconfig.json
// ---------------------------------------------------------------------------

export function generateProjectTsconfig(options: InitProjectOptions): string {
  const { boardPackage } = options;

  return `{
  "compilerOptions": {
    "target": "ES2021",
    "module": "nodenext",
    "moduleResolution": "nodenext",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "paths": {
      "@typehal": ["./node_modules/${boardPackage}"],
      "@typehal/core": ["./node_modules/@typehal/core"]
    }
  },
  "include": ["src/**/*.ts", "typehal.config.ts", "typehal-env.d.ts"]
}
`;
}

// ---------------------------------------------------------------------------
// typehal.config.ts
// ---------------------------------------------------------------------------

export function generateProjectConfig(options: InitProjectOptions): string {
  const { architecture, boardPackage, frameworkPackage, baudRate, framework, toolchainType } = options;
  const buildTarget = options.buildTarget;
  const resolvedToolchain = toolchainType ?? 'arduino-cli';

  const buildTargetLine = buildTarget ? `\n  // Framework-specific data\n  frameworkData: { buildTarget: '${buildTarget}' },` : '';

  return `// ---------------------------------------------------------------------------
// typehal.config.ts — Project configuration
//
// Auto-generated by 'typehal init'. Edit to customise your build.
// ---------------------------------------------------------------------------

import type { TypehalConfig } from '@typehal/core';

const config: TypehalConfig = {
  // Entry point — the main TypeScript file to transpile
  entry: './src/sketch.ts',

  // Target architecture
  target: '${architecture}',

  // Board package — provides pin definitions and board constants
  board: '${boardPackage}',

  // Framework package — controls code generation strategy
  framework: '${frameworkPackage}',${buildTargetLine}

  // Output / build options
  output: {
    framework: '${framework}',
    optimize: 'size',
    outDir: './out',
  },

  // Toolchain configuration
  toolchain: {
    type: '${resolvedToolchain}',
  },

  // Console polyfill configuration
  console: {
    baudRate: ${baudRate},
  },
};

export default config;
`;
}

// ---------------------------------------------------------------------------
// typehal-env.d.ts
// ---------------------------------------------------------------------------

export function generateProjectEnvDts(options: InitProjectOptions): string {
  const { boardPackage, boardDisplayName } = options;

  return `// ---------------------------------------------------------------------------
// typehal-env.d.ts — Virtual module declaration for '@typehal'
//
// Auto-generated by 'typehal init'. Do not edit manually.
// To change the board, update typehal.config.ts and re-run the transpiler.
//
// Board: ${boardDisplayName}
// ---------------------------------------------------------------------------

declare global {
  type Owned<T = any> = T;
  type Shared<T = any> = T;
  type Mutable<T = any> = T;

  // C-style explicit number types recognized by the transpiler
  type uint8_t = number;
  type int8_t = number;
  type uint16_t = number;
  type int16_t = number;
  type uint32_t = number;
  type int32_t = number;
  type size_t = number;
  type float = number;
  type double = number;
}

declare module '@typehal' {
  export * from '${boardPackage}';
}

export {};
`;
}

// ---------------------------------------------------------------------------
// src/sketch.ts — Starter blink sketch
// ---------------------------------------------------------------------------

export function generateStarterSketch(_options: InitProjectOptions): string {
  return `// ---------------------------------------------------------------------------
// Blink — The classic "Hello World" of embedded
//
// Toggles the onboard LED every second using the recommended GPIO pattern.
// ---------------------------------------------------------------------------

import { LED, delay } from '@typehal';

const led = LED.asOutput(false);

while (true) {
  led.toggle();
  delay(1000);
}
`;
}

// ---------------------------------------------------------------------------
// .gitignore
// ---------------------------------------------------------------------------

export function generateGitignore(_options: InitProjectOptions): string {
  return `node_modules/
out/
dist/
*.thcppmap.json
.typehal-cache.json
`;
}
