// ---------------------------------------------------------------------------
// Devicetree overlay generator
//
// Generates <project>/app/boards/<board>.overlay — the standard Zephyr overlay
// path. Content is additive: for each used peripheral with a DT binding the chip
// descriptor knows, emit a `&nodelabel { status = "okay"; }` block enabling it.
// West merges this over the board's base DT; we never rewrite the base.
//
// This is the Zephyr analog of Arduino's library-resolution hooks: the artifact
// that brings external capabilities into a build. (Arduino does it by parsing
// library headers into .d.ts; Zephyr does it by enabling DT nodes + Kconfig.)
// ---------------------------------------------------------------------------

import type { ZephyrChipDescriptor } from '../chips/types.js';
import type { ZephyrDisplayProfile } from '../display/profiles.js';
import type { KconfigUsage } from './kconfig.js';

/**
 * Generate the overlay source for a board + usage. Returns the overlay text
 * (caller writes it to app/boards/<board>.overlay via writeIfChanged).
 */
/** Display wiring from cuttlefish.config.ts (cs/dc/rst/spiFrequency/spiPins). */
export interface DisplayWiring {
  cs?: number;
  dc?: number;
  rst?: number;
  spiFrequency?: number;
  /** SPI bus pins. When present, the overlay remuxes the SPI controller's
   *  pinctrl to these pins (the board defaults rarely match a breakout's
   *  wiring — e.g. demo-st's panel is on SCK=18/MOSI=23, not the devkitc
   *  default 12/11). */
  sck?: number;
  mosi?: number;
  miso?: number;
}

export function generateOverlay(
  chip: ZephyrChipDescriptor,
  usage: KconfigUsage,
  display: ZephyrDisplayProfile | undefined,
  wiring?: DisplayWiring,
): string {
  const lines: string[] = [
    '/* Auto-generated by @typecad/framework-zephyr from cuttlefish.config.ts. */',
    '/* Enables peripherals the program uses. West merges this over the board DT. */',
    '',
  ];

  // Pinctrl override blocks reference the esp32s3 pinmux tokens; the include
  // must precede them. Emitted when the display SPI pins are overridden.
  if (wiring?.sck !== undefined && wiring?.mosi !== undefined) {
    lines.splice(2, 0, '#include <zephyr/dt-bindings/pinctrl/esp32s3-pinctrl.h>', '');
  }

  const block = (label: string, extra: string[] = []): void => {
    lines.push(`&${label} {`);
    lines.push(`    status = "okay";`);
    for (const e of extra) lines.push(`    ${e}`);
    lines.push('};');
    lines.push('');
  };

  if (usage.usesI2c && chip.i2c) {
    for (const c of chip.i2c.controllers) block(c.nodeLabel);
  }
  if (usage.usesSpi && chip.spi) {
    for (const c of chip.spi.controllers) block(c.nodeLabel);
  }
  if (usage.usesUart && chip.uart) {
    for (const c of chip.uart.controllers) block(c.nodeLabel);
  }
  if (display) {
    // Emit a full display DT node definition. Boards like the ESP32 devkit
    // have no display node in their base DT, so a bare `&display0 { status }`
    // fails (the nodelabel doesn't exist). Define the node attached to a SPI
    // controller with the panel's compatible string + dimensions. The pin
    // wiring (cs/dc/rst) uses ESP32 GPIO defaults from the demo config; a
    // real board overlay would carry its own binding.
    emitDisplayNode(lines, display, wiring);
  }
  // FT6336U touch on I2C — defined when the program uses touch (the UI touch
  // adapter references DT_NODELABEL(ft6336u)). Same rationale: the bare devkit
  // has no such node. Gated on usesTouch (not usesI2c/chip.i2c) so it emits
  // even when the chip descriptor doesn't declare I2C controllers (ESP32).
  if (usage.usesTouch) {
    emitTouchNode(lines);
  }

  // Preferences (ZMS settings backend): point the settings subsystem at the
  // board's storage_partition. The backend looks for /chosen
  // zephyr,settings-partition first, then falls back to a fixed-partition
  // labeled storage_partition — most Zephyr boards define that label, so this
  // chosen entry makes the lookup explicit and survives boards that name the
  // partition differently. It only adds a /chosen pointer (never redeclares
  // the partition node — west errors if a node is multiply-defined).
  if (usage.usesPreferences) {
    lines.push('/ {');
    lines.push('    chosen {');
    lines.push('        zephyr,settings-partition = &storage_partition;');
    lines.push('    };');
    lines.push('};');
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Emit a display DT node definition. The node is attached to spi2 (the ESP32's
 * first user SPI controller) via a MIPI DBI SPI bridge. Pin wiring comes from
 * the display config (cs/dc/rst); defaults match the demo-st wiring if absent.
 */
function emitDisplayNode(lines: string[], display: ZephyrDisplayProfile, wiring?: DisplayWiring): void {
  const dc = wiring?.dc ?? 17;
  const rst = wiring?.rst ?? 16;
  const cs = wiring?.cs ?? 5;
  const freq = wiring?.spiFrequency ?? 80000000;
  // DT node describes the NATIVE panel geometry; the effective (rotated)
  // dimensions live in the display profile.
  const nativeW = display.nativeWidth ?? display.width;
  const nativeH = display.nativeHeight ?? display.height;
  const sck = wiring?.sck;
  const mosi = wiring?.mosi;
  const miso = wiring?.miso;
  // ESP32-S3 GPIOs 0-31 are on gpio0, 32-48 on gpio1.
  const gpioController = (pin: number) => pin <= 31 ? 'gpio0' : 'gpio1';
  // The board's spim2_default pinctrl group usually targets the devkitc's
  // default SPI pins (SCLK=12/MOSI=11), which rarely match the display's
  // wiring. When the config declares spiPins, override the pinctrl groups to
  // remux the controller onto the panel's actual pins. Raw ESP32_PINMUX()
  // macros are used instead of the named SPIM2_*_GPIOxx tokens because the
  // bindings header omits GPIOs 22-25 from those lists.
  if (sck !== undefined && mosi !== undefined) {
    lines.push('&spim2_default {');
    lines.push('    group1 {');
    lines.push(`        pinmux = <ESP32_PINMUX(${miso ?? 19}, ESP_FSPIQ_IN, ESP_NOSIG)>,`);
    lines.push(`                 <ESP32_PINMUX(${sck}, ESP_NOSIG, ESP_FSPICLK_OUT)>,`);
    lines.push('                 <ESP32_PINMUX(10, ESP_NOSIG, ESP_FSPICS0_OUT)>;');
    lines.push('    };');
    lines.push('    group2 {');
    lines.push(`        pinmux = <ESP32_PINMUX(${mosi}, ESP_NOSIG, ESP_FSPID_OUT)>;`);
    lines.push('        output-low;');
    lines.push('    };');
    lines.push('};');
    lines.push('');
  }
  lines.push('&spi2 {');
  lines.push('    status = "okay";');
  lines.push(`    cs-gpios = <&${gpioController(cs)} ${cs} GPIO_ACTIVE_LOW>;`);
  lines.push('};');
  lines.push('');
  lines.push('/ {');
  lines.push('    mipi_dbi: mipi-dbi {');
  lines.push('        compatible = "zephyr,mipi-dbi-spi";');
  lines.push('        spi-dev = <&spi2>;');
  lines.push(`        dc-gpios = <&${gpioController(dc)} ${dc} GPIO_ACTIVE_HIGH>;`);
  lines.push(`        reset-gpios = <&${gpioController(rst)} ${rst} GPIO_ACTIVE_LOW>;`);
  lines.push('        write-only;');
  lines.push('        #address-cells = <1>;');
  lines.push('        #size-cells = <0>;');
  lines.push(`        ${display.dtLabel}: display@0 {`);
  lines.push('            compatible = "sitronix,st7796s";');
  lines.push('            reg = <0>;');
  lines.push(`            mipi-max-frequency = <${freq}>;`);
  lines.push('            mipi-mode = "MIPI_DBI_MODE_SPI_4WIRE";');
  lines.push(`            width = <${nativeW}>;`);
  lines.push(`            height = <${nativeH}>;`);
  // MADCTL: rotation 1 (landscape, MV=1) + BGR bit, matching the adapter's
  // direct-drive init (0x28). The DT copy keeps the stock driver's init
  // consistent if it is ever exercised.
  lines.push('            madctl = <0x28>;');
  lines.push('            pgc = [f0 09 0b 06 04 2e 46 46 39 13 15 12 15 12];');
  lines.push('            ngc = [f0 09 0b 06 04 2e 46 46 39 13 15 12 15 12];');
  lines.push('        };');
  lines.push('    };');
  lines.push('};');
  lines.push('');
  if (display.backlight) {
    lines.push('/ {');
    lines.push('    aliases {');
    lines.push(`        ${display.backlight} = &bl_led;`);
    lines.push('    };');
    lines.push('    bl_gpio: bl-gpio-leds {');
    lines.push('        compatible = "gpio-leds";');
    lines.push('        bl_led: led {');
    lines.push('            gpios = <&gpio0 4 GPIO_ACTIVE_HIGH>;');
    lines.push('        };');
    lines.push('    };');
    lines.push('};');
    lines.push('');
  }
}

/**
 * Emit an FT6336U touch DT node on the first I2C controller. The node address
 * is the FT6336U default (0x38). The UI touch adapter references
 * DT_NODELABEL(ft6336u).
 */
function emitTouchNode(lines: string[]): void {
  // Zephyr has no ft6336 binding — the FT6336U is register-compatible with the
  // ft5336 binding (same Focaltech register map: TD_STATUS at 0x02, coordinate
  // registers 0x03-0x06). The C++ touch adapter reads these directly via I2C,
  // so the binding just needs to exist for the DT node to resolve.
  lines.push('&i2c0 {');
  lines.push('    status = "okay";');
  lines.push('    ft6336u: ft6336u@38 {');
  lines.push('        compatible = "focaltech,ft5336";');
  lines.push('        reg = <0x38>;');
  lines.push('        int-gpios = <&gpio0 15 GPIO_ACTIVE_LOW>;');
  lines.push('    };');
  lines.push('};');
  lines.push('');
}
