// ---------------------------------------------------------------------------
// Devicetree overlay generator
//
// Generates <project>/app/boards/<board>.overlay — the standard Zephyr overlay
// path. Content is additive: for each used peripheral with a DT binding the chip
// descriptor knows, emit a `&nodelabel { status = "okay"; }` block enabling it.
// West merges this over the board's base DT; we never rewrite the base.
//
// This is the Zephyr analog of Arduino's library-resolution hooks: the artifact
// that brings external capabilities into a build. (Arduino does it by parsing
// library headers into .d.ts; Zephyr does it by enabling DT nodes + Kconfig.)
// ---------------------------------------------------------------------------

import type { ZephyrChipDescriptor } from '../chips/types.js';
import type { ZephyrDisplayProfile } from '../display/profiles.js';
import type { KconfigUsage } from './kconfig.js';

/**
 * Generate the overlay source for a board + usage. Returns the overlay text
 * (caller writes it to app/boards/<board>.overlay via writeIfChanged).
 */
export function generateOverlay(
  chip: ZephyrChipDescriptor,
  usage: KconfigUsage,
  display: ZephyrDisplayProfile | undefined,
): string {
  const lines: string[] = [
    '/* Auto-generated by @typecad/framework-zephyr from cuttlefish.config.ts. */',
    '/* Enables peripherals the program uses. West merges this over the board DT. */',
    '',
  ];

  const block = (label: string, extra: string[] = []): void => {
    lines.push(`&${label} {`);
    lines.push(`    status = "okay";`);
    for (const e of extra) lines.push(`    ${e}`);
    lines.push('};');
    lines.push('');
  };

  if (usage.usesI2c && chip.i2c) {
    for (const c of chip.i2c.controllers) block(c.nodeLabel);
  }
  if (usage.usesSpi && chip.spi) {
    for (const c of chip.spi.controllers) block(c.nodeLabel);
  }
  if (usage.usesUart && chip.uart) {
    for (const c of chip.uart.controllers) block(c.nodeLabel);
  }
  if (display) block(display.dtLabel);

  // Preferences (ZMS settings backend): point the settings subsystem at the
  // board's storage_partition. The backend looks for /chosen
  // zephyr,settings-partition first, then falls back to a fixed-partition
  // labeled storage_partition — most Zephyr boards define that label, so this
  // chosen entry makes the lookup explicit and survives boards that name the
  // partition differently. It only adds a /chosen pointer (never redeclares
  // the partition node — west errors if a node is multiply-defined).
  if (usage.usesPreferences) {
    lines.push('/ {');
    lines.push('    chosen {');
    lines.push('        zephyr,settings-partition = &storage_partition;');
    lines.push('    };');
    lines.push('};');
    lines.push('');
  }

  return lines.join('\n');
}
