// Auto-generated by typecad-hal gen-decls. Do not edit.
// Source: arrays.h
// C names are preserved verbatim; calls lower 1-to-1 to the C header.

export type esp_err_t = number;

export interface buf_t {
  bytes: number[];
  n: number;
}

export declare function set_mac_sized(ifx: number, mac: number): esp_err_t;
export declare function set_mac_unsized(ifx: number, mac: number): esp_err_t;
