// Auto-generated by cuttlefish gen-decls. Do not edit.
// Source: esp_idf_style.h
// C names are preserved verbatim; calls lower 1-to-1 to the C header.

export type wifi_interface_t = 0 | 1;
export const WIFI_IF_STA: wifi_interface_t = 0;
export const WIFI_IF_AP: wifi_interface_t = 1;

export type wifi_mode_t = 0 | 1 | 2;
export const WIFI_MODE_NULL: wifi_mode_t = 0;
export const WIFI_MODE_STA: wifi_mode_t = 1;
export const WIFI_MODE_AP: wifi_mode_t = 2;

export interface wifi_config_t {
  ssid_addr: number[];
  mode: wifi_mode_t;
}

export type esp_netif_t = number;

// esp_event_handler_t is a C function-pointer typedef; TS has no faithful representation.
export type esp_event_handler_t = any;

export type esp_err_t = number;

export declare function nvs_flash_init(): esp_err_t;
export declare function esp_netif_init(): esp_err_t;
export declare function esp_event_loop_create_default(): esp_err_t;
export declare function esp_netif_create_default_wifi_sta(): esp_netif_t;
export declare function esp_wifi_init(config: number): esp_err_t;
export declare function esp_wifi_set_mode(mode: wifi_mode_t): esp_err_t;
export declare function esp_wifi_set_config(interface: wifi_interface_t, conf: number): esp_err_t;
export declare function esp_wifi_start(): esp_err_t;
export declare function esp_wifi_connect(): esp_err_t;
export declare function esp_netif_get_ip_info(esp_netif: esp_netif_t, ip_info: number): esp_err_t;
