// Auto-generated by typecad-hal gen-decls. Do not edit.
// Source: simple_funcs.h
// C names are preserved verbatim; calls lower 1-to-1 to the C header.

export type esp_err_t = number;

export declare function simple_init(port: number): esp_err_t;
export declare function simple_set_mode(mode: number): esp_err_t;
export declare function simple_no_args(): void;
