// Auto-generated by cuttlefish gen-decls. Do not edit.
// Source: types.h

export type device_mode_t = 0 | 1 | 5;
export const MODE_OFF: device_mode_t = 0;
export const MODE_ON: device_mode_t = 1;
export const MODE_AUTO: device_mode_t = 5;

export interface device_config_t {
  slot: number;
  flags: number;
}

export type device_handle_t = number;

export declare const device: {
  open(cfg: number): device_handle_t;
  get_mode(h: device_handle_t): device_mode_t;
};
