// ---------------------------------------------------------------------------
// Board constant resolver
//
// Board data comes from the project-local generated board module: boardgen
// (in framework-zephyr) materializes `.typecad-hal/board.ts` + `board.json`
// above the user's sources, and `board.json` carries the flat dot-path
// constant map read here. The legacy @typecad/board-* / @typecad/mcu-*
// packages and their TypeScript BoardDefinition manifests are gone, so there
// is no AST path — the JSON manifest is the only board source.
//
// The result is stored in `ProgramIR.boardConstants` and used by the C++
// emitter to fold board constant lookups (`board("pins.led")` and friends)
// into inline literals — without maintaining a separate hard-coded copy of
// the manifest.
// ---------------------------------------------------------------------------

import path from "node:path";
import fs from "node:fs";

import type { BoardConstants } from "../api/shared/index.js";

export type { BoardConstants };

/**
 * Returns a set of default board constants (standard Arduino Uno-like)
 * used as a fallback when no specific board manifest is loaded.
 */
export function getDefaultBoardConstants(): BoardConstants {
  const result: BoardConstants = new Map();
  result.set("pins.analogOffset", 14);
  result.set("peripherals.aliases.UART0", "UART0");
  result.set("peripherals.aliases.I2C0", "I2C0");
  result.set("peripherals.aliases.SPI0", "SPI0");
  return result;
}

/**
 * Locate the project-local generated board module by walking up from a
 * source file. A project carries `.typecad-hal/board.ts` + `board.json`
 * (generated by the framework's board generator — see boardgen in
 * framework-zephyr) instead of a board package.
 */
export function findGeneratedBoard(
  fromFile: string,
): { boardTs: string; boardJson: string } | undefined {
  let dir = path.dirname(path.resolve(fromFile));
  for (let i = 0; i < 8; i++) {
    const boardJson = path.join(dir, ".typecad-hal", "board.json");
    const boardTs = path.join(dir, ".typecad-hal", "board.ts");
    if (fs.existsSync(boardJson) && fs.existsSync(boardTs)) {
      return { boardTs, boardJson };
    }
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return undefined;
}

/**
 * Read a generated board.json manifest into BoardConstants. The manifest is
 * `{ version, identifier, soc, tier, pinNames, constants: {dot-path → value} }`
 * — the `constants` object IS the flat map.
 */
export function readGeneratedBoardConstants(boardJsonPath: string): BoardConstants {
  const manifest = JSON.parse(fs.readFileSync(boardJsonPath, "utf-8")) as {
    constants?: Record<string, string | number | boolean>;
  };
  const result: BoardConstants = new Map();
  for (const [k, v] of Object.entries(manifest.constants ?? {})) {
    result.set(k, v);
  }
  return result;
}

/**
 * Given a source file path and an import module specifier, return the path
 * of the generated board.json manifest the specifier refers to, or
 * undefined. Three specifiers name board data: the user-facing virtual
 * `@typecad/hal` module (tsconfig-mapped onto the generated board module),
 * and (defensively) the config's own
 * board target string. Relative-path board imports are gone with the board
 * packages.
 */
export function tryResolveBoardDefFile(
  fromFile: string,
  moduleSpecifier: string,
  boardTarget?: string,
): string | undefined {
  const lower = moduleSpecifier.toLowerCase();
  const isVirtualBoardSpecifier = lower === "@typecad/hal";
  if (isVirtualBoardSpecifier || moduleSpecifier === boardTarget) {
    const generated = findGeneratedBoard(fromFile);
    if (generated) return generated.boardJson;
  }
  return undefined;
}
