// Auto-generated by typecad-hal (UI lowering). Do not edit.
import type { TextElement, ButtonElement, ViewElement, CheckElement, SelectElement, RadioElement, ProgressElement, RangeElement, InputElement, CanvasElement } from "@typecad/ui";
export interface ScreenTree {
  titlebar: ViewElement;
  title: TextElement;
  shades: ViewElement;
  shDark: TextElement;
  shMid: TextElement;
  shBright: TextElement;
  imgRow: ViewElement;
  gradImg: TextElement;
  shadeEcho: TextElement;
  progRow: ViewElement;
  sweep: ProgressElement;
  uptimeRow: ViewElement;
  uptime: TextElement;
  dimRow: ViewElement;
  dimText: TextElement;
}
export const screen: ScreenTree;