// Auto-generated by typecad-hal (UI lowering). Do not edit.
import type { TextElement, ButtonElement, ViewElement, CheckElement, SelectElement, RadioElement, ProgressElement, RangeElement, InputElement, CanvasElement } from "@typecad/ui";
export interface ScreenTree {
  titlebar: ViewElement;
  title: TextElement;
  card: ViewElement;
  uptime: TextElement;
  body: ViewElement;
  btnrow: TextElement;
}
export const screen: ScreenTree;