// Auto-generated by the typecad-hal transpiler. Do not edit manually.
// Re-exports the configured board/MCU package so the tsconfig path
// mapping for the virtual "@typecad/board" specifier resolves correctly.
export * from '@typecad/board-esp32-devkit';
