// ---------------------------------------------------------------------------
// @typecad/debug — Debug Preprocessor
//
// Transforms TypeScript source by injecting debug code at breakpoint locations.
// The injected code is generated by the loaded framework's strategy
// (e.g., Serial.println for Arduino, std::cout for generic targets).
// ---------------------------------------------------------------------------

import ts from 'typescript';
import path from 'node:path';
import type { BreakpointMap, CapturedVariable, DebugCppType, RichBreakpoint } from './types.js';
import { getBreakpointsForFile } from './breakpoint-loader.js';
import { getLoadedFramework, hasLoadedFramework } from '../framework-registry.js';
import { GenericStrategy } from '../platform/generic-strategy.js';
import type { PlatformStrategy } from '../api/shared/platform-strategy.js';

type LogMessagePart = { type: 'text' | 'variable'; value: string };

/** A function-like declaration with a body and parameters (scope-bearing). */
type ScopeBearingFunction =
  | ts.FunctionDeclaration
  | ts.ArrowFunction
  | ts.MethodDeclaration;

function getDebugStrategy(explicit?: PlatformStrategy) {
  // The strategy that will EMIT this file decides the debug dialect — its
  // codegen must match the runtime the emitted code links against. The
  // global loaded-framework registry is only a fallback for callers that
  // don't know their strategy (picking it blind once emitted Zephyr printk
  // code into a native build).
  if (explicit) {
    if (explicit.generateDebugInitCode) return explicit;
    // The emitting strategy has no debug dialect (e.g. NativeStrategy) —
    // its embedded fallback is the generic printf codegen.
    return new GenericStrategy();
  }
  if (hasLoadedFramework()) {
    const { strategy } = getLoadedFramework();
    if (strategy.generateDebugInitCode) return strategy;
  }
  // Fall back to the generic strategy's printf-based debug output
  return new GenericStrategy();
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export function preprocess(options: {
  /** The source file path (for line number calculation) */
  fileName: string;
  /** The breakpoint map loaded from .typecad-hal/breakpoints.json */
  breakpoints: BreakpointMap;
  /** The source text to transform */
  source: string;
  /** The platform strategy that will emit this file — its debug dialect
   *  (generateDebug*Code) is used. Omit when unknown; the global loaded
   *  framework is consulted, then the generic printf codegen. */
  strategy?: PlatformStrategy;
}): string {
  const { fileName, breakpoints, source, strategy: emittingStrategy } = options;
  const breakpointLines = getBreakpointsForFile(breakpoints, fileName);

  if (breakpointLines.length === 0) {
    return source; // No breakpoints, return unchanged
  }

  const sf = ts.createSourceFile(fileName, source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
  const lines = source.split('\n');
  const outputLines: string[] = [];
  const relativeFileName = path.basename(fileName);

  // Create a map of line number (0-indexed) to breakpoint
  const breakpointMap = new Map<number, RichBreakpoint>();
  for (const bp of breakpointLines) {
    breakpointMap.set(bp.line - 1, bp);
  }

  // Collect variables in scope at each breakpoint
  const scopeAnalyzer = new ScopeAnalyzer(sf);
  const debugStrategy = getDebugStrategy(emittingStrategy);

  // Per-file breakpoint ID counter. Each HALTING breakpoint gets a stable
  // integer ID so the codegen can emit a per-breakpoint disable flag (skipped
  // via the 's' key at runtime). IDs are scoped to this file and reset per
  // preprocess() call, so they stay small and deterministic across builds.
  // Logpoints never halt and don't need an ID.
  let nextBreakpointId = 0;

  // Find the first non-import, non-comment line to insert debug init
  let insertIndex = 0;
  for (let i = 0; i < lines.length; i++) {
    const trimmed = lines[i].trim();
    // Skip import statements and comments
    if (trimmed.startsWith('import ') || trimmed.startsWith('//') || trimmed === '') {
      insertIndex = i + 1;
    } else {
      break;
    }
  }

  // Process each line
  for (let i = 0; i < lines.length; i++) {
    // Insert debug init after imports, before first actual code
    if (i === insertIndex) {
      const initLines = debugStrategy.generateDebugInitCode?.() ?? [];
      outputLines.push(...initLines);
    }

    const lineNum = i; // 0-indexed
    const lineText = lines[i];

    const bp = breakpointMap.get(lineNum);
    if (bp) {
      // Get the original line content (trimmed, for display)
      const displayLine = lineText.trim();

      // Collect variables in scope at this line
      const vars = scopeAnalyzer.getVariablesInScope(lineNum);

      // Halting breakpoints get a per-file ID (used by the codegen to emit a
      // disable flag the user can toggle at runtime with the 's' key). Logpoints
      // never halt, so they pass no ID.
      const breakpointId = bp.logMessage ? undefined : nextBreakpointId++;

      // Inject debug code BEFORE the breakpoint line
      outputLines.push(...generateBreakpointCode(relativeFileName, lineNum + 1, displayLine, vars, bp, debugStrategy, breakpointId));
    }

    // Always include the original line
    outputLines.push(lineText);
  }

  // If all lines were imports/comments, append at end
  if (insertIndex >= lines.length) {
    const initLines = debugStrategy.generateDebugInitCode?.() ?? [];
    outputLines.push(...initLines);
  }

  return outputLines.join('\n');
}

// ---------------------------------------------------------------------------
// Internal — Breakpoint Code Generation
// ---------------------------------------------------------------------------

/**
 * Generate debug code for a breakpoint.
 * Delegates to the loaded strategy when available.
 */
function generateBreakpointCode(
  fileName: string,
  lineNum: number,
  originalLine: string,
  variables: CapturedVariable[],
  bp: RichBreakpoint,
  debugStrategy: ReturnType<typeof getDebugStrategy>,
  breakpointId: number | undefined,
): string[] {
  // If this is a logpoint (has logMessage), generate log-only code
  if (bp.logMessage) {
    const parts = parseLogMessage(bp.logMessage);
    if (debugStrategy.generateDebugLogpointCode) {
      return debugStrategy.generateDebugLogpointCode({
        fileName, lineNum, parts,
        variables: variables.map(v => ({ name: v.name, isFunction: v.isFunction, cppType: v.cppType })),
      });
    }
    return [];
  }

  // Normalize condition for C++ (convert === to ==, strip semicolons, etc.)
  const normalizedCondition = bp.condition ? normalizeCondition(bp.condition) : undefined;

  if (debugStrategy.generateDebugBreakpointCode) {
    return debugStrategy.generateDebugBreakpointCode({
      fileName, lineNum, originalLine,
      variables: variables.map(v => ({ name: v.name, isFunction: v.isFunction, cppType: v.cppType })),
      normalizedCondition,
      breakpointId,
    });
  }

  return [];
}

// ---------------------------------------------------------------------------
// Internal — Log message parsing
// ---------------------------------------------------------------------------

function parseLogMessage(message: string): Array<{ type: 'text' | 'variable'; value: string }> {
  const parts: Array<{ type: 'text' | 'variable'; value: string }> = [];
  let current = '';
  let i = 0;

  while (i < message.length) {
    if (message[i] === '{') {
      if (current) {
        parts.push({ type: 'text', value: current });
        current = '';
      }
      let varName = '';
      i++;
      while (i < message.length && message[i] !== '}') {
        varName += message[i];
        i++;
      }
      i++;
      parts.push({ type: 'variable', value: varName.trim() });
    } else {
      current += message[i];
      i++;
    }
  }

  if (current) {
    parts.push({ type: 'text', value: current });
  }

  return parts;
}

function normalizeCondition(condition: string): string {
  return condition
    .replace(/;+$/, '')
    .replace(/===/g, '==')
    .replace(/!==/g, '!=')
    .trim();
}

// ---------------------------------------------------------------------------
// Internal — Scope Analysis
// ---------------------------------------------------------------------------

class ScopeAnalyzer {
  private sf: ts.SourceFile;
  private functionVars: Map<number, CapturedVariable[]> = new Map();

  constructor(sf: ts.SourceFile) {
    this.sf = sf;
    this.analyze();
  }

  getVariablesInScope(line: number): CapturedVariable[] {
    if (this.functionVars.has(line)) {
      return this.functionVars.get(line)!;
    }
    // Module-scope (top-level): filter by declaration order so breakpoints
    // before a variable's declaration don't reference it (use-before-declare).
    const topVars = this.functionVars.get(-1) || [];
    return topVars.filter(v => v.declLine === undefined || v.declLine < line);
  }

  private analyze(): void {
    // Top-level (module-scope) variables. Iterating sf.statements is reliable
    // across TS statement-classification variants (a bare `let x = 0;` can be
    // parsed as either VariableStatement or FirstStatement; both expose
    // .declarationList, so read it uniformly).
    const topLevelVars: CapturedVariable[] = [];
    for (const stmt of this.sf.statements) {
      this.collectVariablesFromStatement(stmt, topLevelVars);
    }
    this.functionVars.set(-1, topLevelVars);

    // Record a scope entry for every line inside each function body, capturing
    // enclosing-scope vars + parameters + body locals. Nested functions get
    // their own entries that shadow the parent on their line range.
    //
    // Per-line scope filtering: body locals are only in scope on lines STRICTLY
    // AFTER their declaration line. The breakpoint dump is injected at the
    // START of the breakpoint line (before that line's own declaration runs),
    // so a local declared on line N is not yet in scope at line N. Params and
    // enclosing-scope vars are in scope from the function's first line.
    const recordFunction = (node: ScopeBearingFunction, currentVars: CapturedVariable[]): void => {
      // Scope starts at the BODY, not the signature: a breakpoint on the
      // signature line is injected BEFORE the function exists (top-level
      // position), so params are not in scope there — treating it as
      // in-function dumped undeclared identifiers into main().
      const startLine = this.sf.getLineAndCharacterOfPosition(
        (node.body ?? node).getStart(),
      ).line;
      const endLine = node.body
        ? this.sf.getLineAndCharacterOfPosition(node.body.getEnd()).line
        : startLine;

      // Always-in-scope from the function's first line: enclosing vars + params.
      const alwaysInScope: CapturedVariable[] = [...currentVars];
      for (const param of node.parameters) {
        if (ts.isIdentifier(param.name)) {
          alwaysInScope.push({
            name: param.name.text,
            // Params have no initializer; infer from the annotation only.
            cppType: this.inferCppTypeFromAnnotation(param.type),
          });
        }
      }

      // Body locals carry their own declaration line for per-line filtering.
      const bodyLocals: CapturedVariable[] = [];
      if (node.body) {
        this.collectVariablesInBody(node.body, bodyLocals, recordFunction);
      }

      for (let line = startLine; line <= endLine; line++) {
        // A body local is in scope at `line` only if declared on a strictly
        // earlier line (declLine < line). This prevents both compile errors
        // (use-before-declaration on the declaring line) and runtime reads of
        // uninitialized locals at breakpoints above the declaration.
        const localsInScope = bodyLocals.filter(v => v.declLine === undefined || v.declLine < line);
        this.functionVars.set(line, [...alwaysInScope, ...localsInScope]);
      }
    };

    // Find top-level functions, then recurse into their bodies for nested
    // ones. Top-level functions start from an EMPTY enclosing scope: the
    // module-scope variables live in the enclosing scope chain only for
    // NESTED functions. Top-level statements lower into main() locals, so a
    // module-scope name is not visible inside a top-level function — dumping
    // one there emitted references to undeclared identifiers (a breakpoint in
    // any function flagged every top-level const). A breakpoint placed on a
    // top-level statement still sees them via getVariablesInScope's top-level
    // path, filtered by declaration order.
    for (const stmt of this.sf.statements) {
      this.findAndRecordFunctions(stmt, [], recordFunction);
    }
  }

  /** Collect variables declared directly by a single statement (top-level use). */
  private collectVariablesFromStatement(stmt: ts.Statement, vars: CapturedVariable[]): void {
    if (ts.isVariableStatement(stmt) && stmt.declarationList) {
      this.collectFromDeclarationList(stmt.declarationList, vars);
    } else if (this.isFirstStatementVariableDeclaration(stmt)) {
      this.collectFromDeclarationList((stmt as unknown as { declarationList: ts.VariableDeclarationList }).declarationList, vars);
    }
  }

  /**
   * Walk a function body collecting locals, recursing into nested functions so
   * they get their own scope entry (without leaking their locals to the parent).
   */
  private collectVariablesInBody(
    body: ts.Node,
    vars: CapturedVariable[],
    recordFunction: (node: ScopeBearingFunction, currentVars: CapturedVariable[]) => void,
  ): void {
    ts.forEachChild(body, (child) => {
      if (ts.isFunctionDeclaration(child) || ts.isArrowFunction(child) || ts.isMethodDeclaration(child)) {
        // Nested function: record its scope, but do not add its name to this
        // scope's printable vars (it's a function value).
        recordFunction(child as ScopeBearingFunction, vars);
        return;
      }
      this.collectVariablesFromStatement(child as ts.Statement, vars);
      this.collectVariablesInBody(child, vars, recordFunction);
    });
  }

  /** Recurse looking for function declarations to record. */
  private findAndRecordFunctions(
    node: ts.Node,
    currentVars: CapturedVariable[],
    recordFunction: (node: ScopeBearingFunction, currentVars: CapturedVariable[]) => void,
  ): void {
    if (ts.isFunctionDeclaration(node) || ts.isArrowFunction(node) || ts.isMethodDeclaration(node)) {
      recordFunction(node as ScopeBearingFunction, currentVars);
      return; // recordFunction already walks the body for nested functions.
    }
    ts.forEachChild(node, (child) => this.findAndRecordFunctions(child, currentVars, recordFunction));
  }

  private collectFromDeclarationList(list: ts.VariableDeclarationList, vars: CapturedVariable[]): void {
    for (const decl of list.declarations) {
      if (ts.isIdentifier(decl.name)) {
        const isFunction = decl.initializer !== undefined && this.isFunctionExpression(decl.initializer);
        // declLine is the 0-indexed source line of the declaration. Used by
        // recordFunction to filter body locals per line (declLine < line).
        const declLine = this.sf.getLineAndCharacterOfPosition(decl.getStart()).line;
        vars.push({
          name: decl.name.text,
          isFunction,
          declLine,
          cppType: isFunction ? undefined : this.inferCppType(decl),
        });
      }
    }
  }

  /**
   * Infer a coarse C++ type category from an explicit `: T` type annotation
   * node. Returns `unknown` when there is no annotation or it isn't a primitive
   * keyword we recognize.
   */
  private inferCppTypeFromAnnotation(typeNode: ts.TypeNode | undefined): DebugCppType {
    if (!typeNode) return 'unknown';
    if (typeNode.kind === ts.SyntaxKind.BooleanKeyword) return 'bool';
    if (typeNode.kind === ts.SyntaxKind.StringKeyword) return 'string';
    if (typeNode.kind === ts.SyntaxKind.NumberKeyword) return 'float'; // TS number → %g is the safe choice
    if (typeNode.kind === ts.SyntaxKind.BigIntKeyword) return 'long';
    return 'unknown';
  }

  /**
   * Infer a coarse C++ type category from a variable declaration, WITHOUT a
   * TypeChecker (the debug path is parse-only). Priority:
   *   1. Explicit `: T` annotation (authoritative).
   *   2. Initializer shape (literal kind, or a small allowlist of known HAL
   *      calls like millis()/micros() → long).
   *   3. `unknown` — printf codegens cast to double + %g so it always compiles.
   *
   * Function-valued vars are handled by the caller (isFunction); this returns
   * unknown for them but the caller skips emission of function-typed vars.
   */
  private inferCppType(decl: ts.VariableDeclaration): DebugCppType {
    // 1. Explicit type annotation wins.
    const fromAnnotation = this.inferCppTypeFromAnnotation(decl.type);
    if (fromAnnotation !== 'unknown') return fromAnnotation;

    // 2. Initializer shape.
    const init = decl.initializer;
    if (init) {
      if (init.kind === ts.SyntaxKind.TrueKeyword || init.kind === ts.SyntaxKind.FalseKeyword) return 'bool';
      if (ts.isStringLiteral(init)) return 'string';
      if (ts.isNoSubstitutionTemplateLiteral(init) || ts.isTemplateExpression(init)) return 'string';
      if (ts.isNumericLiteral(init)) {
        // Integer literal unless it contains '.' or an exponent marker.
        return /[.eE]/.test(init.text) ? 'float' : 'int';
      }
      if (ts.isCallExpression(init)) {
        // A small allowlist of HAL calls with known C++ return types.
        const callee = ts.isIdentifier(init.expression) ? init.expression.text : '';
        if (callee === 'millis' || callee === 'micros') return 'long';
      }
    }

    // 3. Anything else (references, binary expressions, unknown calls, …).
    return 'unknown';
  }

  /**
   * TS sometimes parses a bare `let x = 0;` as a FirstStatement node rather
   * than a VariableStatement. Detect that case by shape (has declarationList).
   */
  private isFirstStatementVariableDeclaration(node: ts.Node): boolean {
    if (node.kind !== ts.SyntaxKind.FirstStatement) return false;
    return Object.prototype.hasOwnProperty.call(node, 'declarationList');
  }

  private isFunctionExpression(expr: ts.Expression): boolean {
    return ts.isArrowFunction(expr) || ts.isFunctionExpression(expr);
  }
}
