// Auto-generated by cuttlefish (UI lowering). Do not edit.
import type { TextElement, ButtonElement, ViewElement, CheckElement, SelectElement, RadioElement, ProgressElement, RangeElement, InputElement, CanvasElement } from "@typecad/ui";
interface WeatherScreenGroup {
  header: ViewElement;
  title: TextElement;
  subtitle: TextElement;
  tempText: TextElement;
  tempBar: ProgressElement;
  humText: TextElement;
  humBar: ProgressElement;
  presText: TextElement;
  presBar: ProgressElement;
  gasText: TextElement;
  gasBar: ProgressElement;
  gauge: CanvasElement;
}
interface ScreenGroups {
  weather: WeatherScreenGroup;
}
export interface ScreenTree {
  weather: ViewElement;
  header: ViewElement;
  title: TextElement;
  subtitle: TextElement;
  tempText: TextElement;
  tempBar: ProgressElement;
  humText: TextElement;
  humBar: ProgressElement;
  presText: TextElement;
  presBar: ProgressElement;
  gasText: TextElement;
  gasBar: ProgressElement;
  gauge: CanvasElement;
  groups: ScreenGroups;
}
export const screen: ScreenTree;