// ---------------------------------------------------------------------------
// @typehal/debug — Debug Preprocessor
//
// Transforms TypeScript source by injecting debug code at breakpoint locations.
// The injected code is generated by the loaded framework's strategy
// (e.g., Serial.println for Arduino, std::cout for generic targets).
// ---------------------------------------------------------------------------

import ts from 'typescript';
import path from 'node:path';
import type { BreakpointMap, CapturedVariable, RichBreakpoint } from './types';
import { getBreakpointsForFile } from './breakpoint-loader';
import { getLoadedFramework, hasLoadedFramework } from '../framework-registry';

type LogMessagePart = { type: 'text' | 'variable'; value: string };

function getDebugStrategy() {
  if (hasLoadedFramework()) {
    const { strategy } = getLoadedFramework();
    if (strategy.generateDebugInitCode) return strategy;
  }
  // Fall back to the generic strategy's std::cout-based debug output
  const { GenericStrategy } = require('../platform/generic-strategy');
  return new GenericStrategy();
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export function preprocess(options: {
  /** The source file path (for line number calculation) */
  fileName: string;
  /** The breakpoint map loaded from .typehal/breakpoints.json */
  breakpoints: BreakpointMap;
  /** The source text to transform */
  source: string;
}): string {
  const { fileName, breakpoints, source } = options;
  const breakpointLines = getBreakpointsForFile(breakpoints, fileName);

  if (breakpointLines.length === 0) {
    return source; // No breakpoints, return unchanged
  }

  const sf = ts.createSourceFile(fileName, source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
  const lines = source.split('\n');
  const outputLines: string[] = [];
  const relativeFileName = path.basename(fileName);

  // Create a map of line number (0-indexed) to breakpoint
  const breakpointMap = new Map<number, RichBreakpoint>();
  for (const bp of breakpointLines) {
    breakpointMap.set(bp.line - 1, bp);
  }

  // Collect variables in scope at each breakpoint
  const scopeAnalyzer = new ScopeAnalyzer(sf);
  const debugStrategy = getDebugStrategy();

  // Find the first non-import, non-comment line to insert debug init
  let insertIndex = 0;
  for (let i = 0; i < lines.length; i++) {
    const trimmed = lines[i].trim();
    // Skip import statements and comments
    if (trimmed.startsWith('import ') || trimmed.startsWith('//') || trimmed === '') {
      insertIndex = i + 1;
    } else {
      break;
    }
  }

  // Process each line
  for (let i = 0; i < lines.length; i++) {
    // Insert debug init after imports, before first actual code
    if (i === insertIndex) {
      const initLines = debugStrategy.generateDebugInitCode?.() ?? [];
      outputLines.push(...initLines);
    }

    const lineNum = i; // 0-indexed
    const lineText = lines[i];

    const bp = breakpointMap.get(lineNum);
    if (bp) {
      // Get the original line content (trimmed, for display)
      const displayLine = lineText.trim();

      // Collect variables in scope at this line
      const vars = scopeAnalyzer.getVariablesInScope(lineNum);

      // Inject debug code BEFORE the breakpoint line
      outputLines.push(...generateBreakpointCode(relativeFileName, lineNum + 1, displayLine, vars, bp, debugStrategy));
    }

    // Always include the original line
    outputLines.push(lineText);
  }

  // If all lines were imports/comments, append at end
  if (insertIndex >= lines.length) {
    const initLines = debugStrategy.generateDebugInitCode?.() ?? [];
    outputLines.push(...initLines);
  }

  return outputLines.join('\n');
}

// ---------------------------------------------------------------------------
// Internal — Breakpoint Code Generation
// ---------------------------------------------------------------------------

/**
 * Generate debug code for a breakpoint.
 * Delegates to the loaded strategy when available.
 */
function generateBreakpointCode(
  fileName: string,
  lineNum: number,
  originalLine: string,
  variables: CapturedVariable[],
  bp: RichBreakpoint,
  debugStrategy: ReturnType<typeof getDebugStrategy>,
): string[] {
  // If this is a logpoint (has logMessage), generate log-only code
  if (bp.logMessage) {
    const parts = parseLogMessage(bp.logMessage);
    if (debugStrategy.generateDebugLogpointCode) {
      return debugStrategy.generateDebugLogpointCode({
        fileName, lineNum, parts,
        variables: variables.map(v => ({ name: v.name, isFunction: v.isFunction })),
      });
    }
    return [];
  }

  // Normalize condition for C++ (convert === to ==, strip semicolons, etc.)
  const normalizedCondition = bp.condition ? normalizeCondition(bp.condition) : undefined;

  if (debugStrategy.generateDebugBreakpointCode) {
    return debugStrategy.generateDebugBreakpointCode({
      fileName, lineNum, originalLine,
      variables: variables.map(v => ({ name: v.name, isFunction: v.isFunction })),
      normalizedCondition,
    });
  }

  return [];
}

// ---------------------------------------------------------------------------
// Internal — Log message parsing
// ---------------------------------------------------------------------------

function parseLogMessage(message: string): Array<{ type: 'text' | 'variable'; value: string }> {
  const parts: Array<{ type: 'text' | 'variable'; value: string }> = [];
  let current = '';
  let i = 0;

  while (i < message.length) {
    if (message[i] === '{') {
      if (current) {
        parts.push({ type: 'text', value: current });
        current = '';
      }
      let varName = '';
      i++;
      while (i < message.length && message[i] !== '}') {
        varName += message[i];
        i++;
      }
      i++;
      parts.push({ type: 'variable', value: varName.trim() });
    } else {
      current += message[i];
      i++;
    }
  }

  if (current) {
    parts.push({ type: 'text', value: current });
  }

  return parts;
}

function normalizeCondition(condition: string): string {
  return condition
    .replace(/;+$/, '')
    .replace(/===/g, '==')
    .replace(/!==/g, '!=')
    .trim();
}

// ---------------------------------------------------------------------------
// Internal — Scope Analysis
// ---------------------------------------------------------------------------

class ScopeAnalyzer {
  private sf: ts.SourceFile;
  private functionVars: Map<number, CapturedVariable[]> = new Map();

  constructor(sf: ts.SourceFile) {
    this.sf = sf;
    this.analyze();
  }

  getVariablesInScope(line: number): CapturedVariable[] {
    if (this.functionVars.has(line)) {
      return this.functionVars.get(line)!;
    }
    return this.functionVars.get(-1) || [];
  }

  private analyze(): void {
    const topLevelVars: CapturedVariable[] = [];
    this.collectVariables(this.sf, topLevelVars);
    this.functionVars.set(-1, topLevelVars);

    const visit = (node: ts.Node, currentVars: CapturedVariable[]): CapturedVariable[] => {
      if (ts.isFunctionDeclaration(node) || ts.isArrowFunction(node) || ts.isMethodDeclaration(node)) {
        const startLine = this.sf.getLineAndCharacterOfPosition(node.getStart()).line;
        const endLine = node.body
          ? this.sf.getLineAndCharacterOfPosition(node.body.getEnd()).line
          : startLine;
        const localVars: CapturedVariable[] = [...currentVars];

        for (const param of node.parameters) {
          if (ts.isIdentifier(param.name)) {
            localVars.push({ name: param.name.text });
          }
        }

        if (node.body) {
          this.collectVariables(node.body, localVars);
        }

        for (let line = startLine; line <= endLine; line++) {
          this.functionVars.set(line, localVars);
        }
        return localVars;
      }

      ts.forEachChild(node, child => visit(child, currentVars));
      return currentVars;
    };

    visit(this.sf, topLevelVars);
  }

  private collectVariables(node: ts.Node, vars: CapturedVariable[]): void {
    if (ts.isVariableStatement(node)) {
      for (const decl of node.declarationList.declarations) {
        if (ts.isIdentifier(decl.name)) {
          const isFunction = decl.initializer !== undefined && this.isFunctionExpression(decl.initializer);
          vars.push({ name: decl.name.text, isFunction });
        }
      }
    }

    ts.forEachChild(node, child => {
      if (!ts.isFunctionDeclaration(child) && !ts.isArrowFunction(child) && !ts.isMethodDeclaration(child)) {
        this.collectVariables(child, vars);
      }
    });
  }

  private isFunctionExpression(expr: ts.Expression): boolean {
    return ts.isArrowFunction(expr) || ts.isFunctionExpression(expr);
  }
}
