// Entry point for `npm run test:http`.
//
// Does three things, then keeps running until Ctrl+C:
//   1. Detects the host machine's LAN IP (so the ESP32 can reach this server).
//   2. Prompts for WiFi SSID + password (or reuses an existing secrets.ts).
//   3. Writes secrets.ts (this directory) and starts the local test server.
//
// Run in one terminal, then run the firmware test in another:
//   npm run test:http
//   cd tests/hardware && npx typecad-hal test --port COM4 http-client.test.ts

import { networkInterfaces } from 'node:os';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { createInterface } from 'node:readline';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createTestServer, createHttpsTestServer, createMqttBroker, createMqttTlsBroker } from './server';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SECRETS_PATH = resolve(__dirname, 'secrets.ts');
const DEFAULT_PORT = 8080;
const DEFAULT_HTTPS_PORT = 8443;
const DEFAULT_MQTT_PORT = 1883;
const DEFAULT_MQTT_TLS_PORT = 8883;

/** Find the first non-internal IPv4 address on the host. */
function detectLanIp(): string | null {
	const nets = networkInterfaces();
	for (const name of Object.keys(nets)) {
		for (const net of nets[name] ?? []) {
			// Skip internal (loopback) and non-IPv4. Prefer the first match.
			if (!net.internal && net.family === 'IPv4') {
				return net.address;
			}
		}
	}
	return null;
}

function ask(rl: any, question: string, defaultValue?: string): Promise<string> {
	const prompt = defaultValue ? `${question} [${defaultValue}]: ` : `${question}: `;
	return new Promise((res) => {
		rl.question(prompt, (answer: string) => {
			const trimmed = answer.trim();
			res(trimmed || (defaultValue ?? ''));
		});
	});
}

/** Parse the existing secrets.ts (if present) to reuse the WiFi creds. */
function readExistingSecrets(): { ssid: string; password: string; host: string; port: number; httpsPort?: number; mqttPort?: number; mqttTlsPort?: number } | null {
	if (!existsSync(SECRETS_PATH)) return null;
	try {
		const text = readFileSync(SECRETS_PATH, 'utf8');
		const ssid = text.match(/WIFI_SSID\s*=\s*'([^']*)'/)?.[1] ?? '';
		const password = text.match(/WIFI_PASSWORD\s*=\s*'([^']*)'/)?.[1] ?? '';
		const host = text.match(/TEST_HOST\s*=\s*'([^']*)'/)?.[1] ?? '';
		const port = parseInt(text.match(/TEST_PORT\s*=\s*(\d+)/)?.[1] ?? String(DEFAULT_PORT), 10);
		const httpsPort = parseInt(text.match(/TEST_HTTPS_PORT\s*=\s*(\d+)/)?.[1] ?? '0', 10) || undefined;
		const mqttPort = parseInt(text.match(/TEST_MQTT_PORT\s*=\s*(\d+)/)?.[1] ?? '0', 10) || undefined;
		const mqttTlsPort = parseInt(text.match(/TEST_MQTT_TLS_PORT\s*=\s*(\d+)/)?.[1] ?? '0', 10) || undefined;
		// Only reuse if they look filled in (not the EDIT_ME template).
		if (ssid && ssid !== 'EDIT_ME') {
			return { ssid, password, host, port, httpsPort, mqttPort, mqttTlsPort };
		}
	} catch {
		// ignore parse errors — fall through to prompting
	}
	return null;
}

function writeSecrets(ssid: string, password: string, host: string, port: number, httpsPort: number, mqttPort: number, mqttTlsPort: number): void {
	const content = `// Auto-generated by \`npm run test:http\`. Do not edit by hand —
// re-run the script to change values. This file is gitignored.

export const WIFI_SSID = ${JSON.stringify(ssid)};
export const WIFI_PASSWORD = ${JSON.stringify(password)};
export const TEST_HOST = ${JSON.stringify(host)};
export const TEST_PORT = ${port};
export const TEST_HTTPS_PORT = ${httpsPort};
export const TEST_MQTT_PORT = ${mqttPort};
export const TEST_MQTT_TLS_PORT = ${mqttTlsPort};
`;
	writeFileSync(SECRETS_PATH, content, 'utf8');
}

async function main() {
	const detectedIp = detectLanIp();
	const existing = readExistingSecrets();

	// Non-interactive mode: if all four values are provided via env vars or
	// CLI flags, skip the prompts entirely (for CI / scripted use).
	//
	//   WIFI_SSID=net WIFI_PASSWORD=pass TEST_HOST=1.2.3.4 npm run test:http
	//
	// TEST_HOST defaults to the detected LAN IP; TEST_PORT defaults to 8080,
	// TEST_HTTPS_PORT to 8443, TEST_MQTT_PORT to 1883, TEST_MQTT_TLS_PORT to 8883.
	const envSsid = process.env.WIFI_SSID;
	const envPassword = process.env.WIFI_PASSWORD;
	const envHost = process.env.TEST_HOST ?? detectedIp ?? undefined;
	const envPort = parseInt(process.env.TEST_PORT ?? '', 10) || undefined;
	const envHttpsPort = parseInt(process.env.TEST_HTTPS_PORT ?? '', 10) || undefined;
	const envMqttPort = parseInt(process.env.TEST_MQTT_PORT ?? '', 10) || undefined;
	const envMqttTlsPort = parseInt(process.env.TEST_MQTT_TLS_PORT ?? '', 10) || undefined;
	const nonInteractive = !process.stdin.isTTY
		|| (!!envSsid && !!envPassword);

	let ssid: string;
	let password: string;
	let host: string;
	let port: number;

	if (nonInteractive && (envSsid || existing)) {
		ssid = envSsid ?? existing?.ssid ?? '';
		password = envPassword ?? existing?.password ?? '';
		host = envHost ?? existing?.host ?? detectedIp ?? '127.0.0.1';
		port = envPort ?? existing?.port ?? DEFAULT_PORT;
		console.log('\n  typecad-hal HTTP test server (non-interactive)\n  ----------------------------------------------');
		if (detectedIp) console.log(`  Detected LAN IP: ${detectedIp}`);
	} else {
		// Interactive mode — prompt for each value.
		console.log('\n  typecad-hal HTTP test server\n  ----------------------------\n');
		if (detectedIp) {
			console.log(`  Detected LAN IP: ${detectedIp}`);
		} else {
			console.log('  Could not detect a LAN IP. Enter the IP manually.');
		}

		const rl = createInterface({ input: process.stdin, output: process.stdout });
		ssid = await ask(rl, 'WiFi SSID', envSsid ?? existing?.ssid ?? '');
		password = await ask(rl, 'WiFi password', envPassword ?? existing?.password ?? '');
		host = await ask(rl, 'Server IP (ESP32 connects here)', envHost ?? detectedIp ?? '192.168.1.100');
		const portStr = await ask(rl, 'Server port', String(envPort ?? existing?.port ?? DEFAULT_PORT));
		port = parseInt(portStr, 10) || DEFAULT_PORT;
		rl.close();
	}

	if (!ssid || !password) {
		console.error('\nError: SSID and password are required.');
		console.error('Provide them interactively, or via WIFI_SSID / WIFI_PASSWORD env vars,');
		console.error('or copy secrets.template.ts to secrets.ts and fill it in.');
		process.exit(1);
	}

	writeSecrets(ssid, password, host, port,
		envHttpsPort ?? existing?.httpsPort ?? DEFAULT_HTTPS_PORT,
		envMqttPort ?? existing?.mqttPort ?? DEFAULT_MQTT_PORT,
		envMqttTlsPort ?? existing?.mqttTlsPort ?? DEFAULT_MQTT_TLS_PORT);
	console.log(`\n  Wrote secrets.ts  (SSID=${ssid}, server=${host}:${port}, https=${envHttpsPort ?? existing?.httpsPort ?? DEFAULT_HTTPS_PORT}, mqtt=${envMqttPort ?? existing?.mqttPort ?? DEFAULT_MQTT_PORT})`);

	const httpServer = await createTestServer(port);
	const httpsPort = envHttpsPort ?? existing?.httpsPort ?? DEFAULT_HTTPS_PORT;
	let httpsServer;
	try {
		httpsServer = await createHttpsTestServer(httpsPort);
	} catch (err) {
		// A missing/expired cert or a port conflict shouldn't kill the plaintext
		// server — HTTP tests still run. Surface it and continue without HTTPS.
		console.log(`  HTTPS server NOT started: ${(err as Error).message}`);
	}
	console.log(`  HTTP  server listening on http://0.0.0.0:${httpServer.port}`);
	console.log(`  ESP32 → http://${host}:${httpServer.port}`);
	if (httpsServer) {
		console.log(`  HTTPS server listening on https://0.0.0.0:${httpsServer.port}`);
		console.log(`  ESP32 → https://${host}:${httpsServer.port}  (pin certs/ca.crt via caCert)`);
	}
	console.log('\n  Routes (served on both HTTP and HTTPS):');
	console.log('    GET/POST/PUT/DELETE/PATCH/HEAD  /echo');
	console.log('    GET                              /status/{code}');
	console.log('    GET                              /headers');
	console.log('    GET/POST/PUT/DELETE/PATCH        /items?key={key}  (stateful CRUD)');

	// ── MQTT broker (aedes) ─────────────────────────────────────────────
	// Plain mqtt:// on 1883 + mqtts:// (TLS, same cert pair) on 8883. The TLS
	// broker is optional (a missing cert / port conflict doesn't kill the plain
	// broker or the HTTP servers).
	const mqttPort = envMqttPort ?? existing?.mqttPort ?? DEFAULT_MQTT_PORT;
	const mqttTlsPort = envMqttTlsPort ?? existing?.mqttTlsPort ?? DEFAULT_MQTT_TLS_PORT;
	let mqttServer;
	let mqttTlsServer;
	try {
		mqttServer = await createMqttBroker(mqttPort);
	} catch (err) {
		console.log(`  MQTT broker NOT started: ${(err as Error).message}`);
	}
	try {
		mqttTlsServer = await createMqttTlsBroker(mqttTlsPort);
	} catch (err) {
		console.log(`  MQTT TLS broker NOT started: ${(err as Error).message}`);
	}
	if (mqttServer) {
		console.log(`  MQTT  broker listening on mqtt://0.0.0.0:${mqttServer.port}`);
		console.log(`  ESP32 → mqtt://${host}:${mqttServer.port}`);
	}
	if (mqttTlsServer) {
		console.log(`  MQTTS broker listening on mqtts://0.0.0.0:${mqttTlsServer.port}`);
		console.log(`  ESP32 → mqtts://${host}:${mqttTlsServer.port}  (pin certs/ca.crt via caCert)`);
	}

	console.log('\n  Press Ctrl+C to stop. Watching for requests...\n');

	// Keep the process alive until interrupted.
	process.on('SIGINT', async () => {
		console.log('\n  Shutting down...');
		await httpServer.close();
		if (httpsServer) await httpsServer.close();
		if (mqttServer) await mqttServer.close();
		if (mqttTlsServer) await mqttTlsServer.close();
		process.exit(0);
	});
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
