// ---------------------------------------------------------------------------
// clean.ts — the `typecad-hal clean` escape hatch.
//
// Every steady-state flow self-heals on build (board switches nuke the cached
// build dir, outDir renames rewrite the debug artifacts, generated sources
// are rewritten on change). clean is the recovery path for the states build
// CANNOT heal: a build dir wedged by an SDK/Zephyr-tree change or an
// interrupted configure, orphans left by a toolchain upgrade, reclaiming the
// (hundreds of MB) Zephyr build tree, and CI's clean-slate build.
//
// It resolves the output dir exactly like build does (flag > config
// output.outDir against the entry's dir) and removes the WHOLE generated
// tree — everything in it is regenerated by the next build, .gitignore
// marker included. Guard rails keep a misconfigured outDir from taking user
// files with it: the generated-dir marker must be present (build writes it
// into every output root), and directories containing the project root, the
// entry's dir, or a typecad-hal.config.ts are refused outright.
// ---------------------------------------------------------------------------

import fs from 'node:fs';
import path from 'node:path';

/** First line of the .gitignore the transpiler writes into every generated
 *  output root — the machine-checkable proof a dir is cuttlefish-owned. */
export const GENERATED_DIR_MARKER = '# Generated by typecad-hal on build';

export interface CleanOutcome {
  /** Directories removed, with the bytes they held. */
  removed: Array<{ dir: string; bytes: number }>;
  /** Existing candidates without the generated marker — need --force. */
  unmarked: string[];
  /** Candidate dirs that don't exist (nothing to clean). */
  absent: string[];
  /** Directories refused for safety, with the reason. */
  refused: Array<{ dir: string; reason: string }>;
}

function isGeneratedDir(dir: string): boolean {
  try {
    return fs.readFileSync(path.join(dir, '.gitignore'), 'utf8').startsWith(GENERATED_DIR_MARKER);
  } catch {
    return false;
  }
}

function dirBytes(dir: string): number {
  let total = 0;
  const walk = (d: string): void => {
    for (const e of fs.readdirSync(d, { withFileTypes: true })) {
      const p = path.join(d, e.name);
      if (e.isDirectory()) walk(p);
      else {
        try { total += fs.statSync(p).size; } catch { /* unreadable entry */ }
      }
    }
  };
  try { walk(dir); } catch { /* unreadable tree */ }
  return total;
}

/** Whether `ancestor` equals or contains `descendant` (path-containment,
 *  platform-safe via path.relative). */
function contains(ancestor: string, descendant: string): boolean {
  const rel = path.relative(path.resolve(ancestor), path.resolve(descendant));
  return rel === '' || (!rel.startsWith('..') && !path.isAbsolute(rel));
}

export function runClean(o: {
  /** Absolute dir containing typecad-hal.config.ts. */
  projectRoot: string;
  /** Absolute entry file path — its dir anchors relative outDir resolution. */
  entryPath: string;
  /** --out-dir flag (absolute) — wins over the config. */
  outDirOverride?: string;
  /** Config output.outDir, relative to the entry dir. */
  configOutDir?: string;
  /** Remove an existing candidate even without the generated-dir marker. */
  force?: boolean;
}): CleanOutcome {
  const entryDir = path.dirname(path.resolve(o.entryPath));
  let candidates: string[];
  if (o.outDirOverride) {
    candidates = [path.resolve(o.outDirOverride)];
  } else if (o.configOutDir) {
    candidates = [path.resolve(entryDir, o.configOutDir)];
  } else {
    // No dedicated outDir — in-source emit mode. The strategies' generated
    // subdirs (zephyr src/, generic .build/) are the only cuttlefish-owned
    // output there; the marker decides which actually exist.
    candidates = [path.join(entryDir, 'src'), path.join(entryDir, '.build')];
  }

  const outcome: CleanOutcome = { removed: [], unmarked: [], absent: [], refused: [] };
  for (const dir of candidates) {
    if (contains(dir, o.projectRoot)) {
      outcome.refused.push({ dir, reason: 'it contains the project root (typecad-hal.config.ts)' });
      continue;
    }
    if (contains(dir, entryDir)) {
      outcome.refused.push({ dir, reason: 'it contains the entry file directory' });
      continue;
    }
    if (!fs.existsSync(dir)) {
      outcome.absent.push(dir);
      continue;
    }
    if (fs.existsSync(path.join(dir, 'typecad-hal.config.ts'))) {
      outcome.refused.push({ dir, reason: 'it contains a typecad-hal.config.ts (a project, not build output)' });
      continue;
    }
    if (!isGeneratedDir(dir) && !o.force) {
      outcome.unmarked.push(dir);
      continue;
    }
    const bytes = dirBytes(dir);
    fs.rmSync(dir, { recursive: true, force: true });
    outcome.removed.push({ dir, bytes });
  }
  return outcome;
}
