// Auto-generated by typecad-hal (UI lowering). Do not edit.
import type { TextElement, ButtonElement, ViewElement, CheckElement, SelectElement, RadioElement, ProgressElement, RangeElement, InputElement, CanvasElement } from "@typecad/ui";
export interface ScreenTree {
  r10: ViewElement;
  t10: TextElement;
  r11: ViewElement;
  t11: TextElement;
  r13: ViewElement;
  t13: TextElement;
}
export const screen: ScreenTree;