// ---------------------------------------------------------------------------
// sdk-board-data.test.ts — pins the generated board data pack against the
// three boards whose hardware truths we hold, plus pack-level invariants.
// The pack is generated by scripts/gen-zephyr-board-data.mjs against the
// pinned Zephyr tree (4.4.x); regenerate explicitly, never hand-edit.
// ----------------------------------------------------------------------------

import { describe, it, expect } from 'vitest';
import { BOARD_DATA } from '../../../packages/framework-zephyr/src/sdk/board-data.generated';

describe('board data pack', () => {
  it('covers hundreds of board variants, keyed by qualified target', () => {
    const keys = Object.keys(BOARD_DATA);
    expect(keys.length).toBeGreaterThan(600);
    for (const k of keys.slice(0, 50)) {
      expect(BOARD_DATA[k].identifier).toBe(k);
      expect(k.includes('/')).toBe(true);
    }
  });

  it('esp32s3_devkitc/esp32s3/procpu: sw0 on GPIO0, console uart0, no LED', () => {
    const b = BOARD_DATA['esp32s3_devkitc/esp32s3/procpu'];
    expect(b).toBeDefined();
    expect(b.console).toBe('uart0');
    expect(b.led).toBeUndefined(); // WS2812, not gpio-leds
    expect(b.button).toMatchObject({ dtSpec: 'sw0', controller: 'gpio0', pin: 0 });
  });

  it('blackpill_f411ce/stm32f411xe: led0 PC13 active-low, sw0 PA0', () => {
    const b = BOARD_DATA['blackpill_f411ce/stm32f411xe'];
    expect(b).toBeDefined();
    expect(b.console).toBe('usart1');
    expect(b.led).toMatchObject({ dtSpec: 'led0', controller: 'gpioc', pin: 13, flags: ['GPIO_ACTIVE_LOW'] });
    expect(b.button).toMatchObject({ dtSpec: 'sw0', controller: 'gpioa', pin: 0 });
  });

  it('xiao_ble/nrf52840: three LEDs and the D0–D10 connector', () => {
    const b = BOARD_DATA['xiao_ble/nrf52840'];
    expect(b).toBeDefined();
    expect(b.led).toMatchObject({ dtSpec: 'led0', controller: 'gpio0', pin: 26 });
    expect(b.extraLeds?.map((l) => l.dtSpec)).toEqual(['led1', 'led2']);
    const xiao = b.connectors?.find((c) => c.nodelabel === 'xiao_d');
    expect(xiao?.pins['D2']).toMatchObject({ controller: 'gpio0', pin: 28 });
    expect(xiao?.pins['D10']).toMatchObject({ controller: 'gpio1', pin: 15 });
  });

  it('major vendors are represented', () => {
    const vendors = new Set(Object.values(BOARD_DATA).map((b) => b.vendor));
    for (const v of ['espressif', 'seeed', 'weact', 'arduino', 'raspberrypi', 'nordic', 'st']) {
      expect(vendors.has(v), v).toBe(true);
    }
  });
});
