// ---------------------------------------------------------------------------
// soc-chips.test.ts — the consolidated soc-keyed chip registry.
//
// The soc/*.ts descriptors are generated by scripts/gen-soc-descriptors.mjs
// from the board+MCU package data (the exact flatten+reconstruct the build
// performs). This suite pins: (1) the registry resolves every validated soc
// from a build target, (2) each emitted descriptor round-trips against the
// package-derived original, (3) the curated naming/tier facts landed.
// ----------------------------------------------------------------------------

import { describe, it, expect } from 'vitest';
import { SOC_CHIPS, chipForSoc, chipForTarget } from '../../../packages/framework-zephyr/src/chips/index.js';

const EXPECTED_SOCS = [
  'esp32', 'esp32c3', 'esp32c6', 'esp32s3',
  'nrf52840', 'rp2040', 'rp2350a', 'samd21g18a', 'stm32f411xe',
] as const;

describe('soc-keyed chip registry', () => {
  it('covers the nine validated socs', () => {
    for (const soc of EXPECTED_SOCS) {
      expect(SOC_CHIPS[soc], soc).toBeDefined();
    }
    expect(Object.keys(SOC_CHIPS)).toHaveLength(EXPECTED_SOCS.length);
  });

  it('resolves from qualified board targets and bare soc names', () => {
    expect(chipForSoc('esp32s3_devkitc/esp32s3/procpu')?.soc).toBe('esp32s3');
    expect(chipForSoc('blackpill_f411ce/stm32f411xe')?.soc).toBe('stm32f411xe');
    expect(chipForSoc('esp32s3')?.soc).toBe('esp32s3');
    expect(chipForSoc('')).toBeUndefined();
    expect(chipForSoc('not_a_soc_target/notasoc')).toBeUndefined();
  });

  it('chipForTarget consults the soc registry first', () => {
    expect(chipForTarget('esp32s3_devkitc/esp32s3/procpu')).toBe(SOC_CHIPS['esp32s3']);
    expect(chipForTarget('xiao_ble/nrf52840')).toBe(SOC_CHIPS['nrf52840']);
  });

  it('every validated descriptor carries tier + naming + a soc key that matches', () => {
    for (const [soc, chip] of Object.entries(SOC_CHIPS)) {
      expect(chip.soc, soc).toBe(soc);
      expect(chip.tier, soc).toBe('validated');
      expect(chip.pinNaming, soc).toBeDefined();
      expect(chip.gpioControllers?.length ?? 1, soc).toBeGreaterThan(0);
    }
  });

  it('the curated exclusions landed where the datasheet demands them', () => {
    // ESP32-S3: flash/PSRAM (26-37), USB (19/20), console (43/44), strap (0)
    const s3 = SOC_CHIPS['esp32s3'];
    expect(s3.excludedPins).toContain(26);
    expect(s3.excludedPins).toContain(43);
    // STM32: port-block numbering across three controllers
    const f411 = SOC_CHIPS['stm32f411xe'];
    expect(f411.pinNaming).toBe('stm32-port');
    expect(f411.gpioControllers?.map((c) => c.nodelabel)).toEqual(['gpioa', 'gpiob', 'gpioc']);
    // nRF: P0/P1 two-controller split
    const nrf = SOC_CHIPS['nrf52840'];
    expect(nrf.pinNaming).toBe('nrf-port');
    expect(nrf.gpioControllers?.length).toBe(2);
  });
});
