// Auto-generated by typecad-hal (UI lowering). Do not edit.
import type { TextElement, ButtonElement, ViewElement, CheckElement, SelectElement, RadioElement, ProgressElement, RangeElement, InputElement, CanvasElement } from "@typecad/ui";
interface CounterScreenGroup {
  label: TextElement;
  tapBtn: ButtonElement;
}
interface ScreenGroups {
  counter: CounterScreenGroup;
}
export interface ScreenTree {
  counter: ViewElement;
  label: TextElement;
  tapBtn: ButtonElement;
  groups: ScreenGroups;
}
export const screen: ScreenTree;