// Auto-generated by typecad-hal (UI lowering). Do not edit.
import type { TextElement, ButtonElement, ViewElement, CheckElement, SelectElement, RadioElement, ProgressElement, RangeElement, InputElement, CanvasElement } from "@typecad/ui";
interface HomeScreenGroup {
  navBody: ViewElement;
  navTitle: TextElement;
  linkSettings: TextElement;
  linkAbout: TextElement;
  navCounter: TextElement;
}
interface SettingsScreenGroup {
  settingsBody: ViewElement;
  settingsTitle: TextElement;
  settingsHint: TextElement;
  backFromSettings: TextElement;
}
interface AboutScreenGroup {
  aboutBody: ViewElement;
  aboutTitle: TextElement;
  aboutText: TextElement;
  backFromAbout: TextElement;
}
interface ScreenGroups {
  home: HomeScreenGroup;
  settings: SettingsScreenGroup;
  about: AboutScreenGroup;
}
export interface ScreenTree {
  home: ViewElement;
  navBody: ViewElement;
  navTitle: TextElement;
  linkSettings: TextElement;
  linkAbout: TextElement;
  navCounter: TextElement;
  settings: ViewElement;
  settingsBody: ViewElement;
  settingsTitle: TextElement;
  settingsHint: TextElement;
  backFromSettings: TextElement;
  about: ViewElement;
  aboutBody: ViewElement;
  aboutTitle: TextElement;
  aboutText: TextElement;
  backFromAbout: TextElement;
  groups: ScreenGroups;
}
export const screen: ScreenTree;