// ---------------------------------------------------------------------------
// PlatformioToolchain — toolchain implementation for PlatformIO
//
// Wraps the PlatformIO CLI (pio) for compile, upload, and monitor operations.
// PlatformIO auto-installs toolchains on first use.
// ---------------------------------------------------------------------------

import path from 'node:path';
import fs from 'node:fs';
import { spawnSync, spawn } from 'node:child_process';
import type { Toolchain, CompileOptions, CompileResult, UploadOptions, UploadResult, MonitorOptions, CompileError } from './types';
import { registerToolchain } from './registry';
import { parseCompileErrors } from '../utils/toolchain';

/**
 * Map FQBN to PlatformIO board ID.
 * Examples:
 *   arduino:avr:uno -> uno
 *   arduino:esp32:esp32 -> esp32dev
 *   esp32:esp32:esp32 -> esp32dev
 */
function fqbnToPlatformioBoard(fqbn: string): string {
  const parts = fqbn.split(':');
  if (parts.length < 3) return fqbn;

  const [, arch, board] = parts;

  // Common mappings
  const boardMap: Record<string, string> = {
    // Arduino AVR
    'uno': 'uno',
    'nano': 'nanoatmega328',
    'mega': 'megaatmega2560',
    'leonardo': 'leonardo',
    // ESP32
    'esp32': 'esp32dev',
    'esp32s2': 'esp32-s2-saola-1',
    'esp32s3': 'esp32-s3-devkitc-1',
    'esp32c3': 'esp32-c3-devkitm-1',
    // ESP8266
    'esp8266': 'esp01',
    'nodemcu': 'nodemcuv2',
    // RP2040
    'pico': 'pico',
    'rp2040': 'pico',
  };

  return boardMap[board.toLowerCase()] ?? board;
}

/**
 * Generate a minimal platformio.ini for a sketch.
 */
function generatePlatformioIni(
  sketchDir: string,
  fqbn: string,
  options: CompileOptions,
  envName?: string
): string {
  const board = fqbnToPlatformioBoard(fqbn);
  const env = envName ?? 'typecode';

  const lines: string[] = [
    '; PlatformIO Project Configuration File',
    '; Auto-generated by TypeCode - do not edit manually',
    '',
    '[env:' + env + ']',
    'platform = packages/framework-arduino',
    'board = ' + board,
    'framework = arduino',
  ];

  // Add optimization flags
  if (options.optimize === 'size') {
    lines.push('build_flags = -Os');
  } else if (options.optimize === 'speed') {
    lines.push('build_flags = -O3');
  }

  // Add defines
  if (options.defines && Object.keys(options.defines).length > 0) {
    const defineFlags = Object.entries(options.defines)
      .map(([k, v]) => `-D${k}=${v}`)
      .join(' ');
    lines.push('build_flags = ' + defineFlags);
  }

  return lines.join('\n');
}

/**
 * Configuration options for PlatformioToolchain.
 */
export interface PlatformioToolchainOptions {
  /** Custom path to pio executable. */
  path?: string;
  /** Target environment name from platformio.ini. */
  env?: string;
}

/**
 * PlatformIO toolchain implementation.
 */
export class PlatformioToolchain implements Toolchain {
  readonly id = 'platformio' as const;
  readonly name = 'PlatformIO';

  private options: PlatformioToolchainOptions;

  constructor(options: PlatformioToolchainOptions = {}) {
    this.options = options;
  }

  /**
   * Get the path to pio executable.
   * Priority: options.path > PATH lookup
   */
  private getExecutablePath(): string {
    if (this.options.path) {
      return this.options.path;
    }
    return 'pio';
  }

  /**
   * Check if PlatformIO is installed and available.
   */
  async isInstalled(): Promise<string | undefined> {
    const result = spawnSync(this.getExecutablePath(), ['--version'], {
      encoding: 'utf8',
      timeout: 5000,
    });

    if (result.status === 0) {
      return this.getExecutablePath();
    }
    return undefined;
  }

  /**
   * Compile a sketch for the target board.
   */
  async compile(options: CompileOptions): Promise<CompileResult> {
    const resolvedSketchFilePath = path.resolve(options.sketchPath);
    const sketchDir = path.dirname(resolvedSketchFilePath);
    const platformioIniPath = path.join(sketchDir, 'platformio.ini');

    // Generate platformio.ini if it doesn't exist
    if (!fs.existsSync(platformioIniPath)) {
      const iniContent = generatePlatformioIni(
        sketchDir,
        options.fqbn,
        options,
        this.options.env
      );
      fs.writeFileSync(platformioIniPath, iniContent, 'utf8');
    }

    // Build compile command
    const args = ['run'];

    if (this.options.env) {
      args.push('--environment', this.options.env);
    }

    args.push('--project-dir', sketchDir);

    const cmd = spawnSync(this.getExecutablePath(), args, {
      encoding: 'utf8',
      timeout: 300000, // PlatformIO may need to download toolchains on first use
    });

    const output = `${cmd.stdout ?? ''}\n${cmd.stderr ?? ''}`.trim();
    const errors = parseCompileErrors(output);

    return {
      success: cmd.status === 0,
      output,
      errors,
    };
  }

  /**
   * Upload compiled firmware to the target board.
   */
  async upload(options: UploadOptions): Promise<UploadResult> {
    const args = ['device', 'upload'];

    if (this.options.env) {
      args.push('--environment', this.options.env);
    }

    args.push('--project-dir', options.sketchDir);
    args.push('--port', options.port);

    const cmd = spawnSync(this.getExecutablePath(), args, {
      encoding: 'utf8',
      timeout: 120000,
    });

    const output = `${cmd.stdout ?? ''}\n${cmd.stderr ?? ''}`.trim();

    return {
      success: cmd.status === 0,
      output,
    };
  }

  /**
   * Open a serial monitor connection.
   * Blocks until the user closes it (Ctrl+C).
   */
  async monitor(options: MonitorOptions): Promise<void> {
    const args = ['device', 'monitor'];

    if (this.options.env) {
      args.push('--environment', this.options.env);
    }

    args.push('--port', options.port);
    args.push('--baud', String(options.baud));

    return new Promise((resolve, reject) => {
      const proc = spawn(this.getExecutablePath(), args, {
        stdio: 'inherit',
      });

      proc.on('close', (code) => {
        if (code === 0 || code === null) {
          resolve();
        } else {
          reject(new Error(`Monitor exited with code ${code}`));
        }
      });

      proc.on('error', (err) => {
        reject(err);
      });
    });
  }

  /**
   * List available serial ports.
   */
  async listPorts(): Promise<Array<{ port: string; description?: string }>> {
    const args = ['device', 'list', '--json-output'];

    const cmd = spawnSync(this.getExecutablePath(), args, {
      encoding: 'utf8',
      timeout: 10000,
    });

    if (cmd.status !== 0 || !cmd.stdout) {
      return [];
    }

    try {
      const data = JSON.parse(cmd.stdout);
      if (!Array.isArray(data)) return [];

      return data
        .filter((item: any) => item.port)
        .map((item: any) => ({
          port: item.port,
          description: item.description || item.product || undefined,
        }));
    } catch {
      return [];
    }
  }
}

// Register the toolchain
registerToolchain(new PlatformioToolchain());