// Public surface for the generated Zephyr board catalog. The pack itself is
// generated by scripts/gen-zephyr-board-data.mjs against the pinned Zephyr
// tree and lives at src/create/board-catalog.generated.ts (shared with the
// create/scaffold flow). The framework's board generator (boardgen) joins
// this catalog with its curated soc descriptors.
export { BOARD_DATA } from '../../create/board-catalog.generated.js';
export type { BoardDataEntry } from '../../create/board-catalog.generated.js';
