// ---------------------------------------------------------------------------
// Polyfill types
//
// Types for runtime polyfill generation via platform strategies.
// ---------------------------------------------------------------------------

import type { SourceSpan } from './types.js';

export interface RuntimePolyfillIR {
  kind: "polyfill";
  id: string;
  domain: "standard" | "embedded" | (string & {});
  requiredIncludes: string[];
  forwardDeclarations: string[];
  helperStructs: string[];
  helperFunctions: string[];
  shimMacros: string[];
  dependencies: string[];
  /**
   * Variable names of async task instances generated by the async polyfill.
   * The emitter uses these to call `taskVar.run()` inside `loop()`.
   */
  asyncTaskVars?: string[];
  /**
   * True when the Promise/MicrotaskQueue runtime was emitted (requires <functional>/<vector>).
   * False for architectures that lack the C++ standard library.
   * When false, the emitter must NOT emit cuttlefish_pump_microtasks() calls.
   */
  hasPromiseRuntime?: boolean;
}

// Standard library support by architecture
export interface StdLibSupport {
  hasVector: boolean;
  hasString: boolean;
  hasIostream: boolean;
  hasExceptions: boolean;
  hasRTTI: boolean;
  recommendedArrayImpl: "std_vector" | "static_array";
  recommendedStringImpl: "std_string" | "static_string";
}

export const DEFAULT_STDLIB_SUPPORT: StdLibSupport = {
  hasVector: true,
  hasString: true,
  hasIostream: true,
  hasExceptions: true,
  hasRTTI: true,
  recommendedArrayImpl: "std_vector",
  recommendedStringImpl: "std_string",
};

const STDLIB_SUPPORT: Record<string, StdLibSupport> = {
  esp32: {
    hasVector: true,
    hasString: true,
    hasIostream: true,
    hasExceptions: true,
    hasRTTI: true,
    recommendedArrayImpl: "std_vector",
    recommendedStringImpl: "std_string",
  },
  rp2040: {
    hasVector: true,
    hasString: true,
    hasIostream: true,
    hasExceptions: true,
    hasRTTI: true,
    recommendedArrayImpl: "std_vector",
    recommendedStringImpl: "std_string",
  },
  samd: {
    hasVector: true,
    hasString: true,
    hasIostream: true,
    hasExceptions: true,
    hasRTTI: true,
    recommendedArrayImpl: "std_vector",
    recommendedStringImpl: "std_string",
  },
  default: DEFAULT_STDLIB_SUPPORT,
};

export function getStdLibSupport(architecture?: string): StdLibSupport {
  if (!architecture) return DEFAULT_STDLIB_SUPPORT;
  return STDLIB_SUPPORT[architecture.toLowerCase()] ?? DEFAULT_STDLIB_SUPPORT;
}
