// ---------------------------------------------------------------------------
// Zephyr project scaffolding
//
// Writes the CMakeLists.txt + prj.conf around the cuttlefish-emitted src/main.cpp
// so `west build` has a valid Zephyr application. Idempotent: overwrites the
// generated files only when their content changes (avoids invalidating the
// Ninja incremental build's mtime-based dependency tracking).
// ---------------------------------------------------------------------------

import { writeFileSync, existsSync, mkdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

/** Write a file only if the content differs from the existing file. */
function writeIfChanged(filePath: string, content: string): void {
  if (existsSync(filePath)) {
    try {
      if (readFileSync(filePath, 'utf8') === content) return;
    } catch {
      // Read failed — fall through to write.
    }
  }
  writeFileSync(filePath, content);
}

/**
 * Emit the Zephyr application skeleton around the generated src/main.cpp.
 *
 * Layout written:
 *   <projectRoot>/
 *     CMakeLists.txt   (find_package(Zephyr), target_sources app ← src/*.cpp)
 *     prj.conf         (CONFIG_* for GPIO + C++ + libc)
 *     src/main.cpp     (owned by cuttlefish's emit pipeline — NOT touched here)
 *
 * Idempotent. Mirrors scaffoldEspIdfProject's writeIfChanged discipline.
 */
export function scaffoldZephyrProject(projectRoot: string): void {
  const srcDir = join(projectRoot, 'src');
  if (!existsSync(srcDir)) mkdirSync(srcDir, { recursive: true });

  // ── Root CMakeLists.txt ─────────────────────────────────────────────────
  // The canonical Zephyr CMake application. GLOB src/*.cpp so future multi-
  // file emits are picked up automatically; cuttlefish owns the file contents.
  const cmakeLists = [
    '# Auto-generated by @typecad/framework-zephyr from cuttlefish.config.ts.',
    'cmake_minimum_required(VERSION 3.20.0)',
    '',
    'find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})',
    '',
    'project(zephyr_app)',
    '',
    '# Collect cuttlefish-emitted sources.',
    'file(GLOB app_sources src/*.cpp src/*.c)',
    '',
    'target_sources(app PRIVATE ${app_sources})',
    '',
  ].join('\n');
  writeIfChanged(join(projectRoot, 'CMakeLists.txt'), cmakeLists);

  // ── prj.conf ────────────────────────────────────────────────────────────
  // Driver Kconfig symbols enabling the peripherals the framework lowers. These
  // are emitted unconditionally — Zephyr's Kconfig treats an enabled-but-unused
  // driver as harmless (it just isn't linked if no consumer references it), so
  // emitting the union keeps the scaffold simple and lets any program use any
  // lowered peripheral without re-scaffolding.
  //
  // Trade-off: this trades binary size for scaffold simplicity. The notable
  // cost is CONFIG_BT — the NimBLE stack is large even when unused. A future
  // optimization could usage-gate the driver symbols on ctx.analysis.usesX
  // (the way forcedIncludes/shimLines already gate per-peripheral state), so a
  // BLE-free program does not link the stack. For the MVP, the union is simpler
  // and avoids re-scaffolding when a program adds a peripheral.
  //
  // NOTE: the C++ symbol was renamed across Zephyr versions. Current mainline
  // (≥ ~3.x) uses CONFIG_CPP; older releases used CONFIG_CPLUSPLUS.
  const prjConf = [
    '# Auto-generated by @typecad/framework-zephyr from cuttlefish.config.ts.',
    '# Edit in cuttlefish.config.ts (frameworkData), not here.',
    '',
    '# Core drivers. Only emit symbols that exist as Kconfig configs (the board',
    '# already enables SERIAL/console; there is no CONFIG_UART — UART drivers are',
    '# gated by CONFIG_SERIAL which the board sets).',
    'CONFIG_GPIO=y',
    'CONFIG_ADC=y',
    'CONFIG_PWM=y',
    'CONFIG_I2C=y',
    'CONFIG_SPI=y',
    'CONFIG_WATCHDOG=y',
    '',
    '# Bluetooth (NimBLE peripheral). CONFIG_BT_GATT_DYNAMIC_DB enables the',
    '# runtime bt_gatt_service_register path the BLE lowering uses.',
    'CONFIG_BT=y',
    'CONFIG_BT_PERIPHERAL=y',
    'CONFIG_BT_GATT_DYNAMIC_DB=y',
    'CONFIG_BT_DEVICE_NAME="TypeCAD"',
    '',
    '# C++ support (std::string, std::vector via Newlib).',
    'CONFIG_CPP=y',
    'CONFIG_NEWLIB_LIBC=y',
    '# C++14 — BLE/HAL callbacks lower to functions with deduced (auto) return',
    '# types, which require -std=c++14 or higher. The Zephyr default is C++11.',
    'CONFIG_STD_CPP14=y',
    '',
    '# Main thread stack — bumped for setup() init paths.',
    'CONFIG_MAIN_STACK_SIZE=4096',
    '',
  ].join('\n');
  writeIfChanged(join(projectRoot, 'prj.conf'), prjConf);
}
