// ---------------------------------------------------------------------------
// Zephyr project scaffolding
//
// Writes the CMakeLists.txt + prj.conf around the cuttlefish-emitted src/main.cpp
// so `west build` has a valid Zephyr application. Idempotent: overwrites the
// generated files only when their content changes (avoids invalidating the
// Ninja incremental build's mtime-based dependency tracking).
// ---------------------------------------------------------------------------

import { writeFileSync, existsSync, mkdirSync, readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { resolveKconfigFragments, type KconfigUsage } from '../dt-config/kconfig.js';

/** Write a file only if the content differs from the existing file. */
export function writeIfChanged(filePath: string, content: string): void {
  if (existsSync(filePath)) {
    try {
      if (readFileSync(filePath, 'utf8') === content) return;
    } catch {
      // Read failed — fall through to write.
    }
  }
  writeFileSync(filePath, content);
}

/**
 * Concatenate all emitted source under src/ so the scaffold can detect which
 * peripherals the program actually uses. The cuttlefish lowering emits
 * well-known driver API tokens (adc_read, spi_transceive, bt_*, …), so scanning
 * the post-transpile source is an authoritative usage signal — and it keeps the
 * scaffold self-contained (no need to thread analysis through the toolchain
 * contract). Returns '' when no sources exist yet (first prepare call).
 */
function readEmittedSources(srcDir: string): string {
  if (!existsSync(srcDir)) return '';
  let out = '';
  for (const name of readdirSync(srcDir)) {
    if (name.endsWith('.cpp') || name.endsWith('.c')) {
      try {
        out += readFileSync(join(srcDir, name), 'utf8');
      } catch {
        // ignore unreadable files
      }
    }
  }
  return out;
}

/**
 * Emit the Zephyr application skeleton around the generated src/main.cpp.
 *
 * Layout written:
 *   <projectRoot>/
 *     CMakeLists.txt   (find_package(Zephyr), target_sources app ← src/*.cpp)
 *     prj.conf         (CONFIG_* for GPIO + C++ + libc)
 *     src/main.cpp     (owned by cuttlefish's emit pipeline — NOT touched here)
 *
 * Idempotent. Mirrors scaffoldEspIdfProject's writeIfChanged discipline.
 */
export function scaffoldZephyrProject(projectRoot: string, debug = false): void {
  const srcDir = join(projectRoot, 'src');
  if (!existsSync(srcDir)) mkdirSync(srcDir, { recursive: true });

  // Detect which peripherals the program actually uses by scanning the emitted
  // source. The cuttlefish lowering emits well-known driver API tokens, so this
  // is authoritative. Usage-gating the Kconfig symbols keeps a GPIO-only
  // program from pulling in (and linking) stacks it doesn't need — notably
  // NimBLE (CONFIG_BT), whose Espressif prebuilt blobs are not always present
  // in a workspace. The symbol set itself lives in resolveKconfigFragments
  // (dt-config/kconfig.ts), unit-tested separately.
  const src = readEmittedSources(srcDir);
  const uses = (token: string): boolean => src.includes(token);
  const usage: KconfigUsage = {
    usesAdc: uses('adc_'),
    usesPwm: uses('pwm_'),
    usesI2c: uses('i2c_'),
    usesSpi: uses('spi_'),
    usesUart: uses('uart_'),
    usesWdt: uses('wdt_'),
    usesBle: uses('bt_') || uses('bt_gatt') || uses('bt_le_'),
    usesDisplay: uses('display_write') || uses('display_init') || uses('display_fill_rect'),
    usesPower: uses('pm_') || uses('k_sleep') || uses('power_'),
    usesWifi: uses('wifi_') || uses('net_mgmt') || uses('conn_mgr'),
  };

  // ── Root CMakeLists.txt ─────────────────────────────────────────────────
  // The canonical Zephyr CMake application. GLOB src/*.cpp so future multi-
  // file emits are picked up automatically; cuttlefish owns the file contents.
  const cmakeLists = [
    '# Auto-generated by @typecad/framework-zephyr from cuttlefish.config.ts.',
    'cmake_minimum_required(VERSION 3.20.0)',
    '',
    'find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})',
    '',
    'project(zephyr_app)',
    '',
    '# Collect cuttlefish-emitted sources.',
    'file(GLOB app_sources src/*.cpp src/*.c)',
    '',
    'target_sources(app PRIVATE ${app_sources})',
    '',
  ].join('\n');
  writeIfChanged(join(projectRoot, 'CMakeLists.txt'), cmakeLists);

  // ── prj.conf ────────────────────────────────────────────────────────────
  // Driver Kconfig symbols are usage-gated on the emitted source: only a
  // peripheral whose driver API the program actually references is enabled.
  // Zephyr's Kconfig treats an enabled-but-unused driver as harmless, BUT
  // several driver stacks pull in large/specific dependencies — notably
  // NimBLE (CONFIG_BT) needs Espressif prebuilt blobs that are not always
  // fetched (`west blobs fetch hal_espressif`). Usage-gating keeps a GPIO-only
  // blink from requiring those, and shrinks the link for every program. The
  // core GPIO driver and C++ support stay unconditional. Symbol selection is
  // delegated to resolveKconfigFragments (unit-tested in dt-config/kconfig).
  const symbols = resolveKconfigFragments(usage, debug);

  const prjConf: string[] = [
    '# Auto-generated by @typecad/framework-zephyr from cuttlefish.config.ts.',
    '# Edit in cuttlefish.config.ts (frameworkData), not here.',
    '# Driver symbols are usage-gated on the emitted source — only peripherals',
    '# the program references are enabled.',
    '',
  ];
  // Emit a section header before the BT block when present.
  let btHeaderEmitted = false;
  let wifiHeaderEmitted = false;
  for (const [sym, val] of symbols) {
    if (sym === 'CONFIG_BT' && !btHeaderEmitted) {
      prjConf.push('', '# Bluetooth (NimBLE peripheral).');
      btHeaderEmitted = true;
    }
    if (sym === 'CONFIG_WIFI' && !wifiHeaderEmitted) {
      prjConf.push('', '# WiFi / networking (conn_mgr + esp32 wifi driver).');
      wifiHeaderEmitted = true;
    }
    prjConf.push(`${sym}=${val}`);
  }
  // CONFIG_BT_DEVICE_NAME is a string value not produced by the resolver — add
  // it after the BT block when BLE is used (parity with the previous inline form).
  if (usage.usesBle) prjConf.push('CONFIG_BT_DEVICE_NAME="TypeCAD"');
  prjConf.push('');
  writeIfChanged(join(projectRoot, 'prj.conf'), prjConf.join('\n'));
}
