// ---------------------------------------------------------------------------
// Zephyr project scaffolding
//
// Writes the CMakeLists.txt + prj.conf around the cuttlefish-emitted src/main.cpp
// so `west build` has a valid Zephyr application. Idempotent: overwrites the
// generated files only when their content changes (avoids invalidating the
// Ninja incremental build's mtime-based dependency tracking).
// ---------------------------------------------------------------------------

import { writeFileSync, existsSync, mkdirSync, readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

/** Write a file only if the content differs from the existing file. */
function writeIfChanged(filePath: string, content: string): void {
  if (existsSync(filePath)) {
    try {
      if (readFileSync(filePath, 'utf8') === content) return;
    } catch {
      // Read failed — fall through to write.
    }
  }
  writeFileSync(filePath, content);
}

/**
 * Concatenate all emitted source under src/ so the scaffold can detect which
 * peripherals the program actually uses. The cuttlefish lowering emits
 * well-known driver API tokens (adc_read, spi_transceive, bt_*, …), so scanning
 * the post-transpile source is an authoritative usage signal — and it keeps the
 * scaffold self-contained (no need to thread analysis through the toolchain
 * contract). Returns '' when no sources exist yet (first prepare call).
 */
function readEmittedSources(srcDir: string): string {
  if (!existsSync(srcDir)) return '';
  let out = '';
  for (const name of readdirSync(srcDir)) {
    if (name.endsWith('.cpp') || name.endsWith('.c')) {
      try {
        out += readFileSync(join(srcDir, name), 'utf8');
      } catch {
        // ignore unreadable files
      }
    }
  }
  return out;
}

/**
 * Emit the Zephyr application skeleton around the generated src/main.cpp.
 *
 * Layout written:
 *   <projectRoot>/
 *     CMakeLists.txt   (find_package(Zephyr), target_sources app ← src/*.cpp)
 *     prj.conf         (CONFIG_* for GPIO + C++ + libc)
 *     src/main.cpp     (owned by cuttlefish's emit pipeline — NOT touched here)
 *
 * Idempotent. Mirrors scaffoldEspIdfProject's writeIfChanged discipline.
 */
export function scaffoldZephyrProject(projectRoot: string, debug = false): void {
  const srcDir = join(projectRoot, 'src');
  if (!existsSync(srcDir)) mkdirSync(srcDir, { recursive: true });

  // Detect which peripherals the program actually uses by scanning the emitted
  // source. The cuttlefish lowering emits well-known driver API tokens, so this
  // is authoritative. Usage-gating the Kconfig symbols keeps a GPIO-only
  // program from pulling in (and linking) stacks it doesn't need — notably
  // NimBLE (CONFIG_BT), whose Espressif prebuilt blobs are not always present
  // in a workspace. Mirrors the usage-gating forcedIncludes/shimLines already
  // apply via ctx.analysis.usesX.
  const src = readEmittedSources(srcDir);
  const uses = (token: string): boolean => src.includes(token);
  const usesAdc = uses('adc_');
  const usesPwm = uses('pwm_');
  const usesI2c = uses('i2c_');
  const usesSpi = uses('spi_');
  const usesWdt = uses('wdt_');
  const usesBle = uses('bt_') || uses('bt_gatt') || uses('bt_le_');

  // ── Root CMakeLists.txt ─────────────────────────────────────────────────
  // The canonical Zephyr CMake application. GLOB src/*.cpp so future multi-
  // file emits are picked up automatically; cuttlefish owns the file contents.
  const cmakeLists = [
    '# Auto-generated by @typecad/framework-zephyr from cuttlefish.config.ts.',
    'cmake_minimum_required(VERSION 3.20.0)',
    '',
    'find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})',
    '',
    'project(zephyr_app)',
    '',
    '# Collect cuttlefish-emitted sources.',
    'file(GLOB app_sources src/*.cpp src/*.c)',
    '',
    'target_sources(app PRIVATE ${app_sources})',
    '',
  ].join('\n');
  writeIfChanged(join(projectRoot, 'CMakeLists.txt'), cmakeLists);

  // ── prj.conf ────────────────────────────────────────────────────────────
  // Driver Kconfig symbols are usage-gated on the emitted source: only a
  // peripheral whose driver API the program actually references is enabled.
  // Zephyr's Kconfig treats an enabled-but-unused driver as harmless, BUT
  // several driver stacks pull in large/specific dependencies — notably
  // NimBLE (CONFIG_BT) needs Espressif prebuilt blobs that are not always
  // fetched (`west blobs fetch hal_espressif`). Usage-gating keeps a GPIO-only
  // blink from requiring those, and shrinks the link for every program. The
  // core GPIO driver and C++ support stay unconditional.
  //
  // NOTE: the C++ symbol was renamed across Zephyr versions. Current mainline
  // (≥ ~3.x) uses CONFIG_CPP; older releases used CONFIG_CPLUSPLUS.
  const prjConf: string[] = [
    '# Auto-generated by @typecad/framework-zephyr from cuttlefish.config.ts.',
    '# Edit in cuttlefish.config.ts (frameworkData), not here.',
    '# Driver symbols are usage-gated on the emitted source — only peripherals',
    '# the program references are enabled.',
    '',
    '# Core driver + console (the board enables SERIAL/console).',
    'CONFIG_GPIO=y',
  ];
  if (usesAdc) prjConf.push('CONFIG_ADC=y');
  if (usesPwm) prjConf.push('CONFIG_PWM=y');
  if (usesI2c) prjConf.push('CONFIG_I2C=y');
  if (usesSpi) prjConf.push('CONFIG_SPI=y');
  if (usesWdt) prjConf.push('CONFIG_WATCHDOG=y');
  if (usesBle) {
    // Bluetooth (NimBLE peripheral). CONFIG_BT_GATT_DYNAMIC_DB enables the
    // runtime bt_gatt_service_register path the BLE lowering uses.
    prjConf.push('', '# Bluetooth (NimBLE peripheral).');
    prjConf.push('CONFIG_BT=y');
    prjConf.push('CONFIG_BT_PERIPHERAL=y');
    prjConf.push('CONFIG_BT_GATT_DYNAMIC_DB=y');
    prjConf.push('CONFIG_BT_DEVICE_NAME="TypeCAD"');
  }
  prjConf.push(
    '',
    '# C++ support. CONFIG_CPP + CONFIG_NEWLIB_LIBC enable the language and the',
    '# C library; CONFIG_REQUIRES_FULL_LIBCPP selects the full GNU C++ standard',
    "# library (libstdc++) instead of Zephyr's minimal C++ lib, which only",
    '# ships <cstddef>/<cstdint>/<new> and has no <string>/<vector>. Programs',
    '# that lower std::string parameters/variables (or any STL) need it.',
    'CONFIG_CPP=y',
    'CONFIG_NEWLIB_LIBC=y',
    'CONFIG_REQUIRES_FULL_LIBCPP=y',
    '# C++14 — BLE/HAL callbacks lower to functions with deduced (auto) return',
    '# types, which require -std=c++14 or higher. The Zephyr default is C++11.',
    'CONFIG_STD_CPP14=y',
    '',
    '# Main thread stack — bumped for setup() init paths.',
    'CONFIG_MAIN_STACK_SIZE=4096',
    '',
    '# System workqueue — bumped for worker-offload (Phase 1) AND the timer',
    "# methods polyfill (timer callbacks run on the system workqueue via k_work).",
    '# The default ~2 KB stack overflows under heavy workers / timer callbacks.',
    '# Bump to 8 KB; pin a private workqueue (k_work_q_start) if more is needed.',
    'CONFIG_SYSTEM_WORKQUEUE=y',
    'CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=8192',
    '',
  );
  if (debug) {
    // Debug build: -Og (stable single-step over -Os) + ASSERTIONS for runtime
    // checks. Zephyr emits DWARF (-g) by default, so no explicit DEBUG_INFO is
    // needed. CONFIG_DEBUG also enables the CONFIG_ASSERT assert path which is
    // valuable while debugging.
    prjConf.push(
      '# Debug build (--debug): -Og optimization + assertions enabled.',
      'CONFIG_DEBUG=y',
      'CONFIG_DEBUG_OPTIMIZATIONS=y',
      '',
    );
  }
  writeIfChanged(join(projectRoot, 'prj.conf'), prjConf.join('\n'));
}
