// Template for secrets.ts (this directory).
//
// The real secrets.ts is generated by `npm run test:http` (start-server.ts),
// which detects the host LAN IP and writes it here along with the WiFi
// credentials you enter at the prompt. secrets.ts is gitignored.
//
// If you'd rather not use the script, copy this file to secrets.ts and fill
// in the values by hand:
//
//   cp secrets.template.ts secrets.ts

export const WIFI_SSID = 'EDIT_ME';
export const WIFI_PASSWORD = 'EDIT_ME';

/** Host IP the ESP32 will connect to (your machine's LAN IP). */
export const TEST_HOST = '192.168.1.100';
/** Port the local plaintext HTTP test server listens on. */
export const TEST_PORT = 8080;
/** Port the local HTTPS (TLS) test server listens on. */
export const TEST_HTTPS_PORT = 8443;
/** Port the local plaintext MQTT broker listens on. */
export const TEST_MQTT_PORT = 1883;
/** Port the local MQTT-over-TLS broker listens on. */
export const TEST_MQTT_TLS_PORT = 8883;
