// ---------------------------------------------------------------------------
// typecad-hal-env.d.ts — Global type declarations + legacy board alias
//
// Auto-generated by the typecad-hal transpiler. Do not edit manually.
// To change the board, update typecad-hal.config.ts and re-run the transpiler.
//
// Board: native
// ---------------------------------------------------------------------------

declare global {
  type Owned<T = unknown> = T;
  type Shared<T = unknown> = T;
  type Mutable<T = unknown> = T;

  // C-style explicit number types recognized by the transpiler
  type uint8_t = number;
  type int8_t = number;
  type uint16_t = number;
  type int16_t = number;
  type uint32_t = number;
  type int32_t = number;
  type size_t = number;
  type float = number;
  type double = number;

  // Convenience helper for volatile variables in TypeCAD programs.
  // The transpiler detects calls to volatile() and emits the C++ volatile qualifier.
  declare function volatile<T>(value: T): T;

}


export {};
