// ---------------------------------------------------------------------------
// Project scaffolding templates for `typecode init`
//
// Pure functions that return file content strings. Each function takes a
// normalized options object and produces the content for one project file.
// ---------------------------------------------------------------------------

import type { ArchitectureIdentifier } from '@typecode/core';

// ---------------------------------------------------------------------------
// Options passed to every template
// ---------------------------------------------------------------------------

export interface InitProjectOptions {
  /** Project name (e.g., 'my-blink') */
  projectName: string;
  /** Board identifier from the built-in registry (e.g., 'arduino-uno') */
  boardId: string;
  /** Human-readable board name (e.g., 'Arduino Uno') */
  boardDisplayName: string;
  /** Target architecture (e.g., 'avr') */
  architecture: ArchitectureIdentifier;
  /** npm package name for the board (e.g., '@typecode/board-arduino-uno') */
  boardPackage: string;
  /** npm package name for the framework (e.g., '@typecode/framework-arduino') */
  frameworkPackage: string;
  /** Framework id: 'arduino' or 'avr' */
  framework: 'arduino' | 'avr';
  /** Fully Qualified Board Name for arduino-cli */
  fqbn: string;
  /** MCU part number */
  mcu: string;
  /** Serial baud rate */
  baudRate: number;
  /** Whether to generate a starter sketch */
  includeSketch: boolean;
}

// ---------------------------------------------------------------------------
// package.json
// ---------------------------------------------------------------------------

export function generateProjectPackageJson(options: InitProjectOptions): string {
  const { projectName, boardPackage, frameworkPackage, fqbn } = options;

  // Derive a reasonable default port hint from the OS
  const portHint = process.platform === 'win32' ? 'COM4' : '/dev/ttyACM0';

  return `{
  "name": "${projectName}",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "build": "typecode ./src/sketch.ts",
    "compile": "typecode ./src/sketch.ts --compile",
    "upload": "typecode ./src/sketch.ts --compile --upload --port ${portHint}",
    "monitor": "typecode ./src/sketch.ts --compile --upload --monitor --port ${portHint}"
  },
  "dependencies": {
    "@typecode/core": "^0.1.0",
    "${boardPackage}": "^0.1.0",
    "${frameworkPackage}": "^0.1.0"
  }
}
`;
}

// ---------------------------------------------------------------------------
// tsconfig.json
// ---------------------------------------------------------------------------

export function generateProjectTsconfig(options: InitProjectOptions): string {
  const { boardPackage } = options;

  return `{
  "compilerOptions": {
    "target": "ES2021",
    "module": "nodenext",
    "moduleResolution": "nodenext",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "paths": {
      "@typecode": ["./node_modules/${boardPackage}"],
      "@typecode/core": ["./node_modules/@typecode/core"]
    }
  },
  "include": ["src/**/*.ts", "typecode.config.ts", "typecode-env.d.ts"]
}
`;
}

// ---------------------------------------------------------------------------
// typecode.config.ts
// ---------------------------------------------------------------------------

export function generateProjectConfig(options: InitProjectOptions): string {
  const { architecture, boardPackage, frameworkPackage, fqbn, baudRate, framework } = options;

  return `// ---------------------------------------------------------------------------
// typecode.config.ts — Project configuration
//
// Auto-generated by 'typecode init'. Edit to customise your build.
// ---------------------------------------------------------------------------

import type { TypecodeConfig } from '@typecode/core';

const config: TypecodeConfig = {
  // Target architecture
  target: '${architecture}',

  // Board package — provides pin definitions and board constants
  board: '${boardPackage}',

  // Framework package — controls code generation strategy
  framework: '${frameworkPackage}',

  // Fully-Qualified Board Name for arduino-cli
  fqbn: '${fqbn}',

  // Output / build options
  output: {
    framework: '${framework}',
    optimize: 'size',
    outDir: './out',
  },

  // Toolchain configuration
  toolchain: {
    type: 'arduino-cli',
  },

  // Console polyfill configuration
  console: {
    baudRate: ${baudRate},
  },
};

export default config;
`;
}

// ---------------------------------------------------------------------------
// typecode-env.d.ts
// ---------------------------------------------------------------------------

export function generateProjectEnvDts(options: InitProjectOptions): string {
  const { boardPackage, boardDisplayName } = options;

  return `// ---------------------------------------------------------------------------
// typecode-env.d.ts — Virtual module declaration for '@typecode'
//
// Auto-generated by 'typecode init'. Do not edit manually.
// To change the board, update typecode.config.ts and re-run the transpiler.
//
// Board: ${boardDisplayName}
// ---------------------------------------------------------------------------

declare global {
  type Owned<T = any> = T;
  type Ref<T = any> = T;
  type MutRef<T = any> = T;
}

declare module '@typecode' {
  export * from '${boardPackage}';
}

export {};
`;
}

// ---------------------------------------------------------------------------
// src/sketch.ts — Starter blink sketch
// ---------------------------------------------------------------------------

export function generateStarterSketch(_options: InitProjectOptions): string {
  return `// ---------------------------------------------------------------------------
// Blink — The classic "Hello World" of embedded
//
// Toggles the onboard LED every second using the recommended GPIO pattern.
// ---------------------------------------------------------------------------

import { LED, delay } from '@typecode';

const led = LED.asOutput(false);

while (true) {
  led.toggle();
  delay(1000);
}
`;
}

// ---------------------------------------------------------------------------
// .gitignore
// ---------------------------------------------------------------------------

export function generateGitignore(_options: InitProjectOptions): string {
  return `node_modules/
out/
dist/
*.tscppmap.json
.typecode-cache.json
`;
}
