// ---------------------------------------------------------------------------
// typecad-hal-env.d.ts — Global type declarations + legacy board alias
//
// Auto-generated by the typecad-hal transpiler. Do not edit manually.
// To change the board, update typecad-hal.config.ts and re-run the transpiler.
//
// Board: esp32_devkitc/esp32/procpu
// ---------------------------------------------------------------------------

declare global {
  type Owned<T = unknown> = T;
  type Shared<T = unknown> = T;
  type Mutable<T = unknown> = T;

  // C-style explicit number types recognized by the transpiler
  type uint8_t = number;
  type int8_t = number;
  type uint16_t = number;
  type int16_t = number;
  type uint32_t = number;
  type int32_t = number;
  type size_t = number;
  type float = number;
  type double = number;

  // Convenience helper for volatile variables in TypeCAD programs.
  // The transpiler detects calls to volatile() and emits the C++ volatile qualifier.
  declare function volatile<T>(value: T): T;


  // Timing utilities (transpiled to millis/micros/delay/delayMicroseconds)
  const Timing: {
    millis(): number;
    micros(): number;
    delay(ms: number): void;
    delayMicroseconds(us: number): void;
  };

  // Watchdog timer (transpiled to wdt_enable/wdt_reset/wdt_disable)
  const WDT: {
    enable(timeout?: '15ms' | '30ms' | '60ms' | '120ms' | '250ms' | '500ms' | '1s' | '2s' | '4s' | '8s'): void;
    reset(): void;
    disable(): void;
  };

  // Key-value non-volatile storage (EEPROM-backed on AVR, native Preferences.h on ESP32)
  const Preferences: {
    begin(name: string, readOnly?: boolean): void;
    end(): void;
    putInt(key: string, value: number): void;
    getInt(key: string, defaultValue: number): number;
    putUInt(key: string, value: number): void;
    getUInt(key: string, defaultValue: number): number;
    putBool(key: string, value: boolean): void;
    getBool(key: string, defaultValue: boolean): boolean;
    putFloat(key: string, value: number): void;
    getFloat(key: string, defaultValue: number): number;
    putString(key: string, value: string): void;
    getString(key: string, defaultValue: string): string;
    remove(key: string): void;
  };
}


export {};
