// ---------------------------------------------------------------------------
// cuttlefish-env.d.ts — Virtual module declaration for '@typecad'
//
// Auto-generated by the cuttlefish transpiler. Do not edit manually.
// To change the board, update cuttlefish.config.ts and re-run the transpiler.
//
// Board: native
// ---------------------------------------------------------------------------

declare global {
  type Owned<T = unknown> = T;
  type Shared<T = unknown> = T;
  type Mutable<T = unknown> = T;

  // C-style explicit number types recognized by the transpiler
  type uint8_t = number;
  type int8_t = number;
  type uint16_t = number;
  type int16_t = number;
  type uint32_t = number;
  type int32_t = number;
  type size_t = number;
  type float = number;
  type double = number;

  // Millis timer function (provided by native framework)
  declare function millis(): number;

  // Convenience helper for volatile variables in TypeCAD programs.
  // The transpiler detects calls to volatile() and emits the C++ volatile qualifier.
  declare function volatile<T>(value: T): T;

  // Compile-time C++ injection
  declare function emit(code: string): void;

  // Compile-time C++ header registration — emits nothing at the call site,
  // but adds the given header to the generated #include list.
  declare function include(header: string): void;

  // JS-style timers
  declare function setInterval(handler: () => void, timeout?: number): number;
  declare function setTimeout(handler: () => void, timeout?: number): number;
  declare function clearInterval(id: number): void;
  declare function clearTimeout(id: number): void;

  // console — declared here (not pulled from lib.dom) so this project does not
  // need "dom" in tsconfig lib just to type console.log. Avoiding lib.dom also
  // keeps DOM global type names (Node, Element, Event, ...) out of scope, so a
  // user class named e.g. Node is not shadowed by the DOM global. Platforms may
  // declaration-merge extra members onto this interface.
  interface Console {
    log(...args: unknown[]): void;
    info(...args: unknown[]): void;
    debug(...args: unknown[]): void;
    warn(...args: unknown[]): void;
    error(...args: unknown[]): void;
    readLine(): string;
    readCharacter(): string;
  }
  const console: Console;
}

declare module '@typecad' {

}

export {};
