// ---------------------------------------------------------------------------
// cuttlefish-env.d.ts — Virtual module declaration for '@typecad'
//
// Auto-generated by the cuttlefish transpiler. Do not edit manually.
// To change the board, update cuttlefish.config.ts and re-run the transpiler.
//
// Board: native
// ---------------------------------------------------------------------------

declare global {
  type Owned<T = any> = T;
  type Shared<T = any> = T;
  type Mutable<T = any> = T;

  // C-style explicit number types recognized by the transpiler
  type uint8_t = number;
  type int8_t = number;
  type uint16_t = number;
  type int16_t = number;
  type uint32_t = number;
  type int32_t = number;
  type size_t = number;
  type float = number;
  type double = number;

  // Millis timer function (provided by native framework)
  declare function millis(): number;

  // Convenience helper for volatile variables in TypeCAD programs.
  // The transpiler detects calls to volatile() and emits the C++ volatile qualifier.
  declare function volatile<T>(value: T): T;

  // Compile-time C++ injection
  declare function emit(code: string): void;

  // JS-style timers
  declare function setInterval(handler: () => void, timeout?: number): number;
  declare function setTimeout(handler: () => void, timeout?: number): number;
  declare function clearInterval(id: number): void;
  declare function clearTimeout(id: number): void;

  // Console input methods
  interface Console {
    readLine(): string;
    readCharacter(): string;
  }
}

declare module '@typecad' {
  
}

export {};
