// ---------------------------------------------------------------------------
// typecode-env.d.ts — Virtual module declaration for '@typecode'
//
// Auto-generated by the typecode transpiler. Do not edit manually.
// To change the board, update typecode.config.ts and re-run the transpiler.
//
// Board: @typecode/board-esp32-devkit
// ---------------------------------------------------------------------------

declare global {
  type Owned<T = any> = T;
  type Ref<T = any> = T;
  type MutRef<T = any> = T;

  // C-style explicit number types recognized by the transpiler
  type uint8_t = number;
  type int8_t = number;
  type uint16_t = number;
  type int16_t = number;
  type uint32_t = number;
  type int32_t = number;
  type size_t = number;
  type float = number;
  type double = number;

  // Convenience helper for volatile variables in TypeCode programs.
  // The transpiler detects calls to volatile() and emits the C++ volatile qualifier.
  declare function volatile<T>(value: T): T;
}

declare module '@typecode' {
  export * from '@typecode/board-esp32-devkit';
}

export {};
