// ---------------------------------------------------------------------------
// typecode-env.d.ts — Virtual module declaration for '@typecode'
//
// Auto-generated by the typecode transpiler. Do not edit manually.
// To change the board, update typecode.config.ts and re-run the transpiler.
//
// Board: packages/board-arduino-nano
// ---------------------------------------------------------------------------

declare module '@typecode' {
  export * from 'packages/board-arduino-nano';
}
