// ---------------------------------------------------------------------------
// typecode-env.d.ts — Virtual module declaration for '@typecode'
//
// Auto-generated by the typecode transpiler. Do not edit manually.
// To change the board, update typecode.config.ts and re-run the transpiler.
//
// Board: @typecode/board-arduino-uno
// ---------------------------------------------------------------------------

declare global {
  type Owned<T = any> = T;
  type Ref<T = any> = T;
  type MutRef<T = any> = T;
}

declare module '@typecode' {
  export * from '@typecode/board-arduino-uno';
}

export {};
