// ---------------------------------------------------------------------------
// typehal-env.d.ts — Virtual module declaration for '@typehal'
//
// Auto-generated by the typehal transpiler. Do not edit manually.
// To change the board, update typehal.config.ts and re-run the transpiler.
//
// Board: @typehal/board-arduino-uno
// ---------------------------------------------------------------------------

declare global {
  type Owned<T = any> = T;
  type Shared<T = any> = T;
  type Mutable<T = any> = T;

  // C-style explicit number types recognized by the transpiler
  type uint8_t = number;
  type int8_t = number;
  type uint16_t = number;
  type int16_t = number;
  type uint32_t = number;
  type int32_t = number;
  type size_t = number;
  type float = number;
  type double = number;

  // Convenience helper for volatile variables in TypeHAL programs.
  // The transpiler detects calls to volatile() and emits the C++ volatile qualifier.
  declare function volatile<T>(value: T): T;

  // JS-style timers
  declare function setInterval(handler: () => void, timeout?: number): number;
  declare function setTimeout(handler: () => void, timeout?: number): number;
  declare function clearInterval(id: number): void;
  declare function clearTimeout(id: number): void;

  // Timing utilities (transpiled to millis/micros/delay/delayMicroseconds)
  const Timing: {
    millis(): number;
    micros(): number;
    delay(ms: number): void;
    delayMicroseconds(us: number): void;
  };

  // EEPROM non-volatile storage (transpiled to EEPROM.*)
  const EEPROM: {
    read(addr: number): number;
    write(addr: number, value: number): void;
    update(addr: number, value: number): void;
    length(): number;
    get<T>(addr: number, ref: T): T;
    put<T>(addr: number, ref: T): void;
  };

  // Watchdog timer (transpiled to wdt_enable/wdt_reset/wdt_disable)
  const WDT: {
    enable(timeout?: '15ms' | '30ms' | '60ms' | '120ms' | '250ms' | '500ms' | '1s' | '2s' | '4s' | '8s'): void;
    reset(): void;
    disable(): void;
  };

  // Key-value non-volatile storage (EEPROM-backed on AVR, native Preferences.h on ESP32)
  const Preferences: {
    begin(name: string, readOnly?: boolean): void;
    end(): void;
    putInt(key: string, value: number): void;
    getInt(key: string, defaultValue: number): number;
    putUInt(key: string, value: number): void;
    getUInt(key: string, defaultValue: number): number;
    putBool(key: string, value: boolean): void;
    getBool(key: string, defaultValue: boolean): boolean;
    putFloat(key: string, value: number): void;
    getFloat(key: string, defaultValue: number): number;
    putString(key: string, value: string): void;
    getString(key: string, defaultValue: string): string;
    clear(): void;
    remove(key: string): void;
  };
}
declare module '@typehal' {
  export type Owned<T = any> = T;
  export type Shared<T = any> = T;
  export type Mutable<T = any> = T;
}
declare global {
}

declare module '@typehal' {
  export * from '@typehal/board-arduino-uno';
}

export {};
