// Auto-generated by cuttlefish (UI lowering). Do not edit.
import type { TextElement, ButtonElement, ViewElement, CheckElement, SelectElement, RadioElement, ProgressElement, RangeElement, InputElement, CanvasElement } from "@typecad/ui";
interface HomeScreenGroup {
  btn: TextElement;
  countLabel: ViewElement;
}
interface ScreenGroups {
  home: HomeScreenGroup;
}
export interface ScreenTree {
  home: ViewElement;
  btn: TextElement;
  countLabel: ViewElement;
  groups: ScreenGroups;
}
export const screen: ScreenTree;