// ---------------------------------------------------------------------------
// UI lowering — styled tree + computed boxes → C++ node/binding/transition
// tables + a .ui.html.d.ts declaration file.
//
// This is the bridge between the host-side parse/layout pipeline and the
// device-side retained runtime. Colors are resolved to the target color format
// here (once, at transpile time) so the device never converts colors.
//
// Output shape:
//   - nodeTable:       `static const UINode __ui_nodes[] = { ... };`
//   - transitionTable: `static const UITransition __ui_trans[] = { ... };`
//   - typeDecl:        TypeScript declarations so .ui.html imports are typed.
// ---------------------------------------------------------------------------

import { StyledNode } from "../../ui/style-resolver.js";
import { Box } from "../../ui/layout-engine.js";
import { lowerUIToModel, UIProgram, UINodeModel } from "../../ui/model.js";

export interface LoweredUI {
  nodeTable: string;
  transitionTable: string;
  typeDecl: string;
}

type ColorFormat = "rgb565" | "mono";
type Storage = "progmem" | "flash";

export function lowerUIToCpp(
  root: StyledNode,
  boxes: Box[],
  colorFormat: ColorFormat,
  storage: Storage,
): LoweredUI {
  void storage;
  const model = lowerUIToModel(root, boxes, colorFormat);

  // Tables are mutable RAM (ui_tick updates bg/dirty/elapsed/active each
  // frame), so no PROGMEM/flash storage keyword — those imply read-only.
  const nodeTable = emitNodeTable(model);
  const transitionTable = emitTransitionTable(model);
  const typeDecl = emitTypeDecl(root);

  return { nodeTable, transitionTable, typeDecl };
}

function cppKind(kind: UINodeModel["kind"]): string {
  switch (kind) {
    case "fill": return "NODE_FILL";
    case "button": return "NODE_BUTTON";
    case "check": return "NODE_CHECK";
    case "radio": return "NODE_RADIO";
    case "progress": return "NODE_PROGRESS";
    case "range": return "NODE_RANGE";
    case "text": return "NODE_TEXT";
  }
}

function hex(c: number): string {
  return `0x${c.toString(16).padStart(4, "0")}`;
}

function emitNodeTable(model: UIProgram): string {
  const lines = model.nodes.map((n) => {
    const text = n.text ? `"${n.text}"` : "nullptr";
    const font = "nullptr";
    const box = `{${n.box.x},${n.box.y},${n.box.w},${n.box.h}}`;
    const parent = n.parentIndex >= 0 ? n.parentIndex : 255;
    // Progress/range use lastTextWidth as a "previous fill width" for
    // incremental redraw. -1 = never drawn, because fill width 0 is valid.
    const lastTextWidth = n.kind === "progress" || n.kind === "range" ? -1 : 0;
    return `  { .box=${box}, .bg=${hex(n.bg)}, .fg=${hex(n.fg)}, .kind=${cppKind(n.kind)}, .text=${text}, .textBuffer={0}, .hasTextBinding=0, .font=${font}, .hasBg=${n.hasBg ? 1 : 0}, .textAlign=${n.textAlign}, .borderColor=${hex(n.borderColor)}, .borderStyle=${n.borderStyle}, .underline=${n.underline ? 1 : 0}, .visible=${n.visible ? 1 : 0}, .clearColor=${hex(n.clearColor)}, .lastTextWidth=${lastTextWidth}, .scrollable=${n.scrollable ? 1 : 0}, .scrollY=0, .contentHeight=${n.contentHeight}, .parent=${parent}, .subtreeEnd=${n.subtreeEnd}, .rangeMin=${n.rangeMin}, .rangeMax=${n.rangeMax}, .dirty=0, .value=${n.checked ? 1 : 0} },`;
  });
  return [
    // Mutable (not const) so ui_tick can update bg/dirty during transitions.
    // AVR would want PROGMEM + a shadow copy; ESP32-class has RAM to spare.
    `UINode __ui_nodes[] = {`,
    ...lines,
    `};`,
  ].join("\n");
}

function emitTransitionTable(model: UIProgram): string {
  const entries = model.transitions.map((t) => {
    const prop = t.prop === "background" ? "PROP_BG" : "PROP_FG";
    return `  { .node=${t.node}, .prop=${prop}, .durationMs=${t.durationMs}, .pressedTarget=${hex(t.pressedTarget)}, .baseTarget=${hex(t.baseTarget)} },`;
  });
  if (entries.length === 0) {
    return `const UITransition __ui_trans[] = {};`;
  }
  return [
    // Mutable: ui_tick updates elapsed/active each frame.
    `UITransition __ui_trans[] = {`,
    ...entries,
    `};`,
  ].join("\n");
}

function emitTypeDecl(root: StyledNode): string {
  // Collect id → tag pairs by walking the tree.
  const ids: Array<{ id: string; tag: string }> = [];
  const collect = (n: StyledNode) => {
    if (n.id) ids.push({ id: n.id, tag: n.tag });
    n.children.forEach(collect);
  };
  collect(root);

  const fields = ids.map(({ id, tag }) => {
    const typeName = tag.charAt(0).toUpperCase() + tag.slice(1);
    return `  ${id}: ${typeName}Element;`;
  }).join("\n");

  return [
    `// Auto-generated by cuttlefish UI lowering. Do not edit.`,
    `export interface ScreenTree {`,
    fields,
    `}`,
    ``,
    `export const screen: ScreenTree;`,
  ].join("\n");
}
