// ---------------------------------------------------------------------------
// UI lowering — styled tree + computed boxes → C++ node/binding/transition
// tables + a .ui.html.d.ts declaration file.
//
// This is the bridge between the host-side parse/layout pipeline and the
// device-side retained runtime. Colors are resolved to the target color format
// here (once, at transpile time) so the device never converts colors.
//
// Output shape:
//   - nodeTable:       `static const UINode __ui_nodes[] = { ... };`
//   - transitionTable: `static const UITransition __ui_trans[] = { ... };`
//   - typeDecl:        TypeScript declarations so .ui.html imports are typed.
// ---------------------------------------------------------------------------

import { StyledNode } from "../../ui/style-resolver";
import { Box } from "../../ui/layout-engine";
import { resolveColor } from "../../ui/color";
import { CSSProperty } from "../../ui/css-parser";

export interface LoweredUI {
  nodeTable: string;
  transitionTable: string;
  typeDecl: string;
}

type ColorFormat = "rgb565" | "mono";
type Storage = "progmem" | "flash";

interface FlatNode {
  index: number;
  tag: string;
  id?: string;
  text?: string;
  style: CSSProperty;
  box: Box;
  hasPressed: boolean;
}

export function lowerUIToCpp(
  root: StyledNode,
  boxes: Box[],
  colorFormat: ColorFormat,
  storage: Storage,
): LoweredUI {
  const flat: FlatNode[] = [];
  flatten(root, boxes, flat, { i: 0 });

  const storageKw = storage === "progmem" ? "PROGMEM" : "";
  const nodeTable = emitNodeTable(flat, colorFormat, storageKw);
  const transitionTable = emitTransitionTable(flat, colorFormat);
  const typeDecl = emitTypeDecl(root);

  return { nodeTable, transitionTable, typeDecl };
}

function flatten(
  node: StyledNode,
  boxes: Box[],
  out: FlatNode[],
  cursor: { i: number },
): void {
  const index = cursor.i++;
  const box = boxes[index] ?? { x: 0, y: 0, w: 0, h: 0 };
  const hasPressed = !!(node.style as CSSProperty & { pressed?: CSSProperty }).pressed;
  out.push({
    index,
    tag: node.tag,
    id: node.id,
    text: node.text,
    style: node.style,
    box,
    hasPressed,
  });
  for (const child of node.children) flatten(child, boxes, out, cursor);
}

function emitNodeTable(flat: FlatNode[], colorFormat: ColorFormat, storageKw: string): string {
  const lines = flat.map((n) => {
    const kind = n.tag === "screen" || n.tag === "view" ? "NODE_FILL" : "NODE_TEXT";
    const bg = n.style.background ? resolveColor(n.style.background, colorFormat) : 0;
    const fg = n.style.color ? resolveColor(n.style.color, colorFormat) : 0xffff;
    const text = n.text ? `"${n.text}"` : "nullptr";
    const font = n.style.font ? `&font_${n.style.font.replace("x", "_")}` : "nullptr";
    const box = `{${n.box.x},${n.box.y},${n.box.w},${n.box.h}}`;
    const bgStr = `0x${bg.toString(16).padStart(4, "0")}`;
    const fgStr = `0x${fg.toString(16).padStart(4, "0")}`;
    return `  { .box=${box}, .bg=${bgStr}, .fg=${fgStr}, .kind=${kind}, .text=${text}, .font=${font} },`;
  });
  return [
    `static const UINode __ui_nodes[] ${storageKw} = {`,
    ...lines,
    `};`,
  ].join("\n");
}

function emitTransitionTable(flat: FlatNode[], _colorFormat: ColorFormat): string {
  const entries: string[] = [];
  for (const n of flat) {
    if (!n.style.transition) continue;
    const prop = n.style.transition.property === "background" ? "PROP_BG" : "PROP_FG";
    entries.push(`  { .node=${n.index}, .prop=${prop}, .durationMs=${n.style.transition.durationMs} },`);
  }
  if (entries.length === 0) {
    return `static const UITransition __ui_trans[] = {};`;
  }
  return [
    `static const UITransition __ui_trans[] = {`,
    ...entries,
    `};`,
  ].join("\n");
}

function emitTypeDecl(root: StyledNode): string {
  // Collect id → tag pairs by walking the tree.
  const ids: Array<{ id: string; tag: string }> = [];
  const collect = (n: StyledNode) => {
    if (n.id) ids.push({ id: n.id, tag: n.tag });
    n.children.forEach(collect);
  };
  collect(root);

  const fields = ids.map(({ id, tag }) => {
    const typeName = tag.charAt(0).toUpperCase() + tag.slice(1);
    return `  ${id}: ${typeName}Element;`;
  }).join("\n");

  return [
    `// Auto-generated by cuttlefish UI lowering. Do not edit.`,
    `export interface ScreenTree {`,
    fields,
    `}`,
    ``,
    `export const screen: ScreenTree;`,
  ].join("\n");
}
