import type { PsramMode } from '../components/types.js';

/**
 * Targets that have PSRAM-capable variants. The ESP32 (classic) and ESP32-S3
 * are the common cases; ESP32-C6 also has a PSRAM option on newer modules.
 * S2/C3/C5 do not (or are not yet supported here).
 */
const PSRAM_CAPABLE_TARGETS = new Set(['esp32', 'esp32s3', 'esp32c6']);

/**
 * Generate sdkconfig.defaults contents for a given ESP32 target + PSRAM mode.
 * Users override by editing the file directly or running `idf.py menuconfig`.
 * Spec §3.3.
 */
export function sdkconfigDefaultsForTarget(
  target: string,
  psram: PsramMode | false = false,
): string {
  const lines: string[] = [
    '# Auto-generated by @typecad/framework-esp32.',
    '# Override by editing this file, or run `idf.py menuconfig` for interactive config.',
    '',
    `CONFIG_IDF_TARGET="${target}"`,
    '',
    '# Logging (WARNING level to suppress IDF boot/task messages that interfere',
    '# with serial protocol output during hardware tests)',
    'CONFIG_LOG_DEFAULT_LEVEL_WARNING=y',
    'CONFIG_LOG_COLORS=y',
    '',
    '# FreeRTOS',
    'CONFIG_FREERTOS_HZ=1000',
    '',
    '# main_task stack: setup()/loop() run in app_main directly (IDF-idiomatic,',
    '# cf. esp_http_client example). The IDF default of 3584 overflows on WiFi/HTTP',
    '# paths — esp_wifi_connect, TLS handshake, printf with response bodies.',
    'CONFIG_ESP_MAIN_TASK_STACK_SIZE=16384',
    '',
    '# Components the framework uses',
    'CONFIG_ESP_TASK_WDT_INIT=y',
    '# Power management: required for esp_pm_configure() (power.set_cpu_frequency).',
    'CONFIG_PM_ENABLE=y',
    '',
    '# HTTPS via esp_http_client + esp_crt_bundle_attach',
    'CONFIG_MBEDTLS_CERTIFICATE_BUNDLE=y',
    'CONFIG_MBEDTLS_CERTIFICATE_BUNDLE_DEFAULT_CMN=y',
    '',
    '# Bluetooth (NimBLE) — enabled by the BLE HAL domain. GATT peripheral v1.',
    'CONFIG_BT_ENABLED=y',
    'CONFIG_BT_NIMBLE_ENABLED=y',
    'CONFIG_BT_NIMBLE_ROLE_PERIPHERAL=y',
    'CONFIG_BT_NIMBLE_MAX_CONNECTIONS=1',
    '',
  ];

  // ── PSRAM ────────────────────────────────────────────────────────────────
  // Reference: ESP-IDF "SPI Flash and External SPI RAM Configuration" guide.
  // Octal PSRAM (OPI): ESP32-S3 N8R8/N16R8 modules — 80 MHz max.
  // Quad PSRAM:        ESP32 classic, ESP32-S2, some S3 modules — 40 MHz max.
  if (psram !== false) {
    if (!PSRAM_CAPABLE_TARGETS.has(target)) {
      lines.push(
        `# PSRAM: frameworkData.psram='${psram}' requested but target '${target}'`,
        `# has no PSRAM-capable variant. Skipping PSRAM config.`,
        '',
      );
    } else {
      const isOctal = psram === 'opi';
      const mode = isOctal ? 'Octal (OPI)' : 'Quad SPI';
      const speed = isOctal ? '80M' : '40M';
      lines.push(
        `# PSRAM (${mode} mode — ${isOctal ? 'ESP32-S3 N8R8/N16R8' : 'ESP32/S2/some S3'} modules)`,
        '# Reference: https://docs.espressif.com/projects/esp-idf/en/stable/esp32s3/api-guides/flash_psram_config.html',
        'CONFIG_SPIRAM=y',
        `CONFIG_SPIRAM_MODE_${isOctal ? 'OCT' : 'QUAD'}=y`,
        `CONFIG_SPIRAM_SPEED_${speed}=y`,
        '',
        '# Allow malloc() to hand out PSRAM for large allocations. Small allocs',
        '# stay in fast internal SRAM (ALWAYSINTERNAL threshold below).',
        'CONFIG_SPIRAM_USE_MALLOC=y',
        'CONFIG_SPIRAM_MEMTEST=y',
        '# Allocations ≤16 KiB stay in internal SRAM; larger ones (scroll canvases,',
        '# fonts, image buffers) can spill to PSRAM. Espressif-recommended tuning.',
        'CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL=16384',
        '# Always retain at least 32 KiB of internal heap for ISRs / Wi-Fi / BT.',
        'CONFIG_SPIRAM_MALLOC_RETAIN_HEAP=32768',
        '# Let Wi-Fi/LWIP allocate large buffers in PSRAM (frees internal SRAM).',
        'CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP=y',
        '',
      );
    }
  }

  switch (target) {
    case 'esp32':
      lines.push('CONFIG_ESPTOOLPY_FLASHSIZE_4MB=y', 'CONFIG_PARTITION_TABLE_SINGLE_APP=y', '');
      break;
    case 'esp32s3':
      lines.push('CONFIG_ESPTOOLPY_FLASHSIZE_8MB=y', 'CONFIG_PARTITION_TABLE_TWO_OTA=y', '');
      break;
    case 'esp32c3':
      lines.push('CONFIG_ESPTOOLPY_FLASHSIZE_4MB=y', 'CONFIG_PARTITION_TABLE_SINGLE_APP=y', '');
      break;
    case 'esp32c6':
      lines.push('CONFIG_ESPTOOLPY_FLASHSIZE_4MB=y', 'CONFIG_PARTITION_TABLE_SINGLE_APP=y', '');
      break;
    default:
      // Unknown target — emit nothing extra; let idf.py error helpfully.
      break;
  }

  return lines.join('\n');
}
