/**
 * Generate sdkconfig.defaults contents for a given ESP32 target.
 * Users override by editing the file directly or running `idf.py menuconfig`.
 * Spec §3.3.
 */
export function sdkconfigDefaultsForTarget(target: string): string {
  const lines: string[] = [
    '# Auto-generated by @typecad/framework-esp32.',
    '# Override by editing this file, or run `idf.py menuconfig` for interactive config.',
    '',
    `CONFIG_IDF_TARGET="${target}"`,
    '',
    '# Logging (WARNING level to suppress IDF boot/task messages that interfere',
    '# with serial protocol output during hardware tests)',
    'CONFIG_LOG_DEFAULT_LEVEL_WARNING=y',
    'CONFIG_LOG_COLORS=y',
    '',
    '# FreeRTOS',
    'CONFIG_FREERTOS_HZ=1000',
    'CONFIG_FREERTOS_ENABLE_BACKWARD_COMPATIBILITY=y',
    '',
    '# Components the framework uses',
    'CONFIG_ESP_TASK_WDT_INIT=y',
    '',
  ];

  switch (target) {
    case 'esp32':
      lines.push('CONFIG_ESPTOOLPY_FLASHSIZE_4MB=y', 'CONFIG_PARTITION_TABLE_SINGLE_APP=y', '');
      break;
    case 'esp32s3':
      lines.push('CONFIG_ESPTOOLPY_FLASHSIZE_8MB=y', 'CONFIG_PARTITION_TABLE_TWO_OTA=y', '');
      break;
    case 'esp32c3':
      lines.push('CONFIG_ESPTOOLPY_FLASHSIZE_4MB=y', 'CONFIG_PARTITION_TABLE_SINGLE_APP=y', '');
      break;
    case 'esp32c6':
      lines.push('CONFIG_ESPTOOLPY_FLASHSIZE_4MB=y', 'CONFIG_PARTITION_TABLE_SINGLE_APP=y', '');
      break;
    default:
      // Unknown target — emit nothing extra; let idf.py error helpfully.
      break;
  }

  return lines.join('\n');
}
