import type { HALOpIR } from '@typecad/cuttlefish/api/shared';

/**
 * Native ESP-IDF NimBLE runtime shim (`__tc_ble_*`). Uses the nimble_host stack
 * (not Bluedroid). GATT peripheral role only.
 *
 * State mirrors the HAL BleStatus enum:
 *   0 Idle, 1 Initializing, 2 Advertising, 3 Connected, 4 Error.
 *
 * All helpers are `static inline` so unused ones don't trip -Wunused-function
 * in the single generated TU.
 */
export function bleInitLines(): string[] {
  return [
    `// CUTTLEFISH_BLE_BEGIN`,
    `#define __TC_BLE_MAX_CHARS 16`,
    `#define __TC_BLE_MAX_SVCS 8`,
    ``,
    `// Forward declarations (advertise_start is called from gap_event + on_sync).`,
    `static void __tc_ble_advertise_start(void);`,
    `static int __tc_ble_gap_event(struct ble_gap_event *event, void *arg);`,
    ``,
    `// Read handlers are stored as void* and cast based on the char's type.`,
    `// The transpiler infers int/double/std::string return types per callback.`,
    `typedef int  (*__tc_ble_read_int_cb_t)(void);`,
    `typedef double (*__tc_ble_read_dbl_cb_t)(void);`,
    `typedef const char* (*__tc_ble_read_str_cb_t)(void);`,
    `typedef void (*__tc_ble_write_cb_t)(int value);`,
    `typedef void (*__tc_ble_event_cb_t)(void);`,
    ``,
    `// Deferred characteristic definition (populated before __tc_ble_server_begin).`,
    `typedef struct {`,
    `    const char* uuid_str;    // raw UUID string ("2A6E" or full 128-bit)`,
    `    bool uuid_is_128;        // true if uuid_str is a 128-bit UUID`,
    `    int perms;               // bitmask: READ=1, WRITE=2, NOTIFY=4`,
    `    int svc_index;           // which service this char belongs to`,
    `    const char* type;        // value type: "int16", "uint8", "float32", "utf8", etc.`,
    `} __tc_ble_char_def_t;`,
    ``,
    `static struct {`,
    `    int status;                // BleStatus enum`,
    `    bool inited;`,
    `    bool advertising;`,
    `    int connected_clients;`,
    `    int conn_handle;           // active connection handle (-1 = none)`,
    `    uint16_t svc_count;`,
    `    int current_char;          // set by add_char, read by on_read/on_write`,
    `    void* on_read[__TC_BLE_MAX_CHARS];    // typed function pointer, cast by char type`,
    `    __tc_ble_write_cb_t  on_write[__TC_BLE_MAX_CHARS];`,
    `    uint16_t val_handles[__TC_BLE_MAX_CHARS];  // value handles, captured after ble_gatts_add_svcs`,
    `    __tc_ble_event_cb_t  on_connect;`,
    `    __tc_ble_event_cb_t  on_disconnect;`,
    `    char name[32];`,
    `    int8_t pending_tx_power;   // requested TX power (dBm); -128 = unset; applied after stack init`,
    `} __tc_ble = { 0, false, false, 0, -1, 0, 0, {}, {}, {}, NULL, NULL, {}, -128 };`,
    ``,
    `static __tc_ble_char_def_t __tc_ble_char_defs[__TC_BLE_MAX_CHARS];`,
    `static int __tc_ble_char_count = 0;`,
    `static const char* __tc_ble_svc_uuids[__TC_BLE_MAX_SVCS];`,
    ``,
    `// Static pools for the synthesized NimBLE GATT table.`,
    `// UUID objects must persist for the lifetime of the stack.`,
    `static ble_uuid16_t __tc_ble_svc_uuid16_objs[__TC_BLE_MAX_SVCS];`,
    `static ble_uuid128_t __tc_ble_svc_uuid128_objs[__TC_BLE_MAX_SVCS];`,
    `static ble_uuid16_t __tc_ble_chr_uuid16_objs[__TC_BLE_MAX_CHARS];`,
    `static ble_uuid128_t __tc_ble_chr_uuid128_objs[__TC_BLE_MAX_CHARS];`,
    `static struct ble_gatt_chr_def __tc_ble_chr_defs[__TC_BLE_MAX_CHARS + __TC_BLE_MAX_SVCS];`,
    `static struct ble_gatt_svc_def __tc_ble_svcs[__TC_BLE_MAX_SVCS + 1];`,
    ``,
    `// ── GATT access callback: bridges NimBLE → user read/write handlers ──`,
    `static int __tc_ble_gatt_access(uint16_t conn_handle, uint16_t attr_handle,`,
    `                                struct ble_gatt_access_ctxt *ctxt, void *arg) {`,
    `    (void)conn_handle; (void)attr_handle; (void)arg;`,
    `    // Match by char index using attr_handle offset from the first char handle.`,
    `    // The characteristic index is passed via arg (set during table build).`,
    `    // This routes each read/write to the correct handler instead of always`,
    `    // firing the first one.`,
    `    int idx = arg ? static_cast<int>(intptr_t)arg : 0;`,
    `    if (idx < 0 || idx >= __TC_BLE_MAX_CHARS) return 0;`,
    `    if (ctxt->op == BLE_GATT_ACCESS_OP_READ_CHR && __tc_ble.on_read[idx]) {`,
    `        const char* t = __tc_ble_char_defs[idx].type;`,
    `        if (t && (strcmp(t, "utf8") == 0)) {`,
    `            std::string s = ((std::string(*)(void))__tc_ble.on_read[idx])();`,
    `            os_mbuf_append(ctxt->om, s.c_str(), s.length() + 1);`,
    `        } else if (t && (strcmp(t, "float32") == 0)) {`,
    `            double d = ((double(*)(void))__tc_ble.on_read[idx])();`,
    `            float f = static_cast<float>(d);`,
    `            os_mbuf_append(ctxt->om, &f, sizeof(f));`,
    `        } else if (t && (strcmp(t, "uint32") == 0)) {`,
    `            int v = ((int(*)(void))__tc_ble.on_read[idx])();`,
    `            uint32_t u = static_cast<uint32_t>(v);`,
    `            os_mbuf_append(ctxt->om, &u, sizeof(u));`,
    `        } else if (t && (strcmp(t, "boolean") == 0)) {`,
    `            int v = ((int(*)(void))__tc_ble.on_read[idx])();`,
    `            uint8_t b = v ? 1 : 0;`,
    `            os_mbuf_append(ctxt->om, &b, sizeof(b));`,
    `        } else {`,
    `            // uint8/16, int8/16/32 → default to int16 for GATT compat.`,
    `            int v = ((int(*)(void))__tc_ble.on_read[idx])();`,
    `            int16_t s = static_cast<int16_t>(v);`,
    `            os_mbuf_append(ctxt->om, &s, sizeof(s));`,
    `        }`,
    `        return 0;`,
    `    }`,
    `    if (ctxt->op == BLE_GATT_ACCESS_OP_WRITE_CHR && __tc_ble.on_write[idx]) {`,
    `        const char* wt = __tc_ble_char_defs[idx].type;`,
    `        int cb_val = 0;`,
    `        int pktlen = OS_MBUF_PKTLEN(ctxt->om);`,
    `        // Decode via os_mbuf_copydata rather than reading ctxt->om->om_data`,
    `        // directly: a write payload can span a chain of mbufs, and only the`,
    `        // first segment's om_data is reachable by direct dereference.`,
    `        // os_mbuf_copydata flattens the whole chain into a local buffer.`,
    `        if (wt && (strcmp(wt, "utf8") == 0)) {`,
    `            // For utf8 writes, pass the first byte's value (truncated for v1).`,
    `            // Full string write support needs a different callback signature.`,
    `            if (pktlen >= 1) { uint8_t b0 = 0; os_mbuf_copydata(ctxt->om, 0, 1, &b0); cb_val = b0; }`,
    `        } else if (wt && (strcmp(wt, "uint32") == 0)) {`,
    `            uint32_t u = 0;`,
    `            if (pktlen >= static_cast<int>(sizeof(u))) os_mbuf_copydata(ctxt->om, 0, sizeof(u), &u);`,
    `            cb_val = static_cast<int>(u);`,
    `        } else if (wt && (strcmp(wt, "float32") == 0)) {`,
    `            float f = 0;`,
    `            if (pktlen >= static_cast<int>(sizeof(f))) os_mbuf_copydata(ctxt->om, 0, sizeof(f), &f);`,
    `            cb_val = static_cast<int>(f);`,
    `        } else {`,
    `            // uint8/16, int8/16/32, boolean → int16`,
    `            int16_t s = 0;`,
    `            if (pktlen >= static_cast<int>(sizeof(s))) os_mbuf_copydata(ctxt->om, 0, sizeof(s), &s);`,
    `            cb_val = s;`,
    `        }`,
    `        __tc_ble.on_write[idx](cb_val);`,
    `        return 0;`,
    `    }`,
    `    return 0;`,
    `}`,
    ``,
    `// ── GAP event handler ──`,
    `static int __tc_ble_gap_event(struct ble_gap_event *event, void *arg) {`,
    `    (void)arg;`,
    `    switch (event->type) {`,
    `    case BLE_GAP_EVENT_CONNECT:`,
    `        if (event->connect.status == 0) {`,
    `            __tc_ble.connected_clients = __tc_ble.connected_clients + 1;`,
    `            __tc_ble.conn_handle = event->connect.conn_handle;`,
    `            __tc_ble.status = 3; // Connected`,
    `            if (__tc_ble.on_connect) __tc_ble.on_connect();`,
    `        } else {`,
    `            __tc_ble_advertise_start();`,
    `        }`,
    `        break;`,
    `    case BLE_GAP_EVENT_DISCONNECT:`,
    `        if (__tc_ble.on_disconnect) __tc_ble.on_disconnect();`,
    `        __tc_ble.connected_clients = __tc_ble.connected_clients > 0 ? __tc_ble.connected_clients - 1 : 0;`,
    `        __tc_ble.conn_handle = -1;`,
    `        __tc_ble.status = 2; // Advertising`,
    `        __tc_ble_advertise_start();`,
    `        break;`,
    `    default: break;`,
    `    }`,
    `    return 0;`,
    `}`,
    ``,
    `// ── NimBLE host task (called by nimble_port_freertos_init) ──`,
    `static void __tc_ble_host_task(void *param) {`,
    `    (void)param;`,
    `    nimble_port_run();  // blocks — processes BLE events until stack stops`,
    `    nimble_port_freertos_deinit();`,
    `}`,
    ``,
    `// ── Sync callback: NimBLE stack is ready — start advertising ──`,
    `static uint8_t __tc_ble_own_addr_type;`,
    `static void __tc_ble_on_sync(void) {`,
    `    int rc = ble_hs_id_infer_auto(0, &__tc_ble_own_addr_type);`,
    `    if (rc != 0) {`,
    `        ESP_LOGW("tc", "ble: id_infer_auto rc=%d", rc);`,
    `        return;`,
    `    }`,
    `    __tc_ble.status = 2; // Advertising`,
    `    __tc_ble_advertise_start();`,
    `}`,
    ``,
    `static void __tc_ble_ensure_init(void) {`,
    `    if (__tc_ble.inited) return;`,
    `    __tc_ble.conn_handle = -1;`,
    `    // NVS is required by the PHY/BT controller for calibration data. When WiFi`,
    `    // is also used it calls nvs_flash_init() first; the second call here returns`,
    `    // ESP_ERR_INVALID_STATE, which we accept (NVS is already up). Only the`,
    `    // corrupt-partition cases warrant erase+retry.`,
    `    esp_err_t err = nvs_flash_init();`,
    `    if (err == ESP_ERR_NVS_NO_FREE_PAGES || err == ESP_ERR_NVS_NEW_VERSION_FOUND) {`,
    `        nvs_flash_erase();`,
    `        nvs_flash_init();`,
    `    }`,
    `    ESP_ERROR_CHECK(nimble_port_init());`,
    `    ble_hs_cfg.sync_cb = __tc_ble_on_sync;`,
    `    __tc_ble.inited = true;`,
    `    // The controller is up now; apply any TX power requested before begin().`,
    `    __tc_ble_apply_tx_power();`,
    `    __tc_ble.status = 1; // Initializing`,
    `}`,
    ``,
    `static inline bool __tc_ble_is_connected(void) {`,
    `    return __tc_ble.status == 3 && __tc_ble.connected_clients > 0;`,
    `}`,
    ``,
    `static inline int __tc_ble_client_count(void) {`,
    `    return __tc_ble.connected_clients;`,
    `}`,
    ``,
    `static inline void __tc_ble_set_name(const char* name) {`,
    `    strlcpy(__tc_ble.name, name, sizeof(__tc_ble.name));`,
    `}`,
    ``,
    `// TX power via the BLE controller API (esp_bt.h), available under NimBLE.`,
    `// esp_power_level_t is a 3 dBm grid from -24..+20; snap the requested dBm to the`,
    `// nearest grid point. We stash the requested value so a set_tx_power() issued`,
    `// before server_begin()/ensure_init() still applies once the controller is up.`,
    `static inline esp_power_level_t __tc_ble_dbm_to_pwr(int dbm) {`,
    `    if (dbm <= -24) return ESP_PWR_LVL_N24;`,
    `    if (dbm <= -21) return ESP_PWR_LVL_N21;`,
    `    if (dbm <= -18) return ESP_PWR_LVL_N18;`,
    `    if (dbm <= -15) return ESP_PWR_LVL_N15;`,
    `    if (dbm <= -12) return ESP_PWR_LVL_N12;`,
    `    if (dbm <= -9)  return ESP_PWR_LVL_N9;`,
    `    if (dbm <= -6)  return ESP_PWR_LVL_N6;`,
    `    if (dbm <= -3)  return ESP_PWR_LVL_N3;`,
    `    if (dbm <= 0)   return ESP_PWR_LVL_N0;`,
    `    if (dbm <= 3)   return ESP_PWR_LVL_P3;`,
    `    if (dbm <= 6)   return ESP_PWR_LVL_P6;`,
    `    if (dbm <= 9)   return ESP_PWR_LVL_P9;`,
    `    if (dbm <= 12)  return ESP_PWR_LVL_P12;`,
    `    if (dbm <= 15)  return ESP_PWR_LVL_P15;`,
    `    if (dbm <= 18)  return ESP_PWR_LVL_P18;`,
    `    return ESP_PWR_LVL_P20;`,
    `}`,
    ``,
    `static inline void __tc_ble_apply_tx_power(void) {`,
    `    if (__tc_ble.pending_tx_power != -128) {`,
    `        esp_ble_tx_power_set(ESP_BLE_PWR_TYPE_DEFAULT,`,
    `                             __tc_ble_dbm_to_pwr(__tc_ble.pending_tx_power));`,
    `    }`,
    `}`,
    ``,
    `static inline void __tc_ble_set_tx_power(int dbm) {`,
    `    __tc_ble.pending_tx_power = static_cast<int8_t>(dbm);`,
    `    if (__tc_ble.inited) __tc_ble_apply_tx_power();`,
    `}`,
    ``,
    `// ── Deferred service graph ──`,
    `// Detect 128-bit UUIDs (contain dashes, > 4 hex chars).`,
    `static bool __tc_ble_uuid_is_128(const char* s) { return strchr(s, '-') != NULL; }`,
    ``,
    `static inline void __tc_ble_add_service(const char* uuid_str) {`,
    `    if (__tc_ble.svc_count < __TC_BLE_MAX_SVCS) {`,
    `        __tc_ble_svc_uuids[__tc_ble.svc_count] = uuid_str;`,
    `        __tc_ble.svc_count++;`,
    `    }`,
    `}`,
    ``,
    `static inline void __tc_ble_add_char(int idx, const char* uuid_str, const char* type, int perms, int svc_index) {`,
    `    // idx is the characteristic slot the HAL assigns (it also keys the matching`,
    `    // on_read/on_write assignment via current_char). Validate and use it directly`,
    `    // rather than a separate internal counter — they must agree or callbacks land`,
    `    // on the wrong characteristic.`,
    `    if (idx < 0 || idx >= __TC_BLE_MAX_CHARS) return;`,
    `    __tc_ble_char_defs[idx].uuid_str = uuid_str;`,
    `    __tc_ble_char_defs[idx].uuid_is_128 = __tc_ble_uuid_is_128(uuid_str);`,
    `    __tc_ble_char_defs[idx].perms = perms;`,
    `    __tc_ble_char_defs[idx].svc_index = svc_index;`,
    `    __tc_ble_char_defs[idx].type = type;`,
    `    __tc_ble.current_char = idx;`,
    `    if (idx + 1 > __tc_ble_char_count) __tc_ble_char_count = idx + 1;`,
    `}`,
    ``,
    `// Parse a canonical "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" UUID string into the`,
    `// 16-byte value array of a ble_uuid128_t. The Bluetooth Core Spec transmits`,
    `// 128-bit UUIDs in little-endian byte order, and NimBLE's BLE_UUID128_INIT`,
    `// expects bytes reversed relative to the string — so the first hex pair of the`,
    `// string lands in value[15], the last in value[0]. Storing left-to-right`,
    `// (string order) silently advertises the wrong UUID and a central scanning for`,
    `// the UUID the user wrote never finds it.`,
    `static void __tc_ble_uuid128_parse(uint8_t* value, const char* u) {`,
    `    int bi = 0;  // counts hex pairs parsed (0..15), most-significant first`,
    `    for (int i = 0; u[i] && bi < 16; i++) {`,
    `        if (u[i] == '-') continue;`,
    `        char hex[3] = {u[i], u[i+1], 0};`,
    `        // Store reversed: string byte 0 → value[15], byte 1 → value[14], …`,
    `        value[15 - bi] = static_cast<uint8_t>(strtol(hex, NULL, 16));`,
    `        bi++;`,
    `        i++;  // skip second hex digit of the pair`,
    `    }`,
    `}`,
    ``,
    `// Build the NimBLE ble_gatt_svc_def[] tree from the deferred graph.`,
    `// Parse UUID strings into ble_uuid16_t or ble_uuid128_t as appropriate.`,
    `static const ble_uuid_t* __tc_ble_make_svc_uuid(int s) {`,
    `    const char* u = __tc_ble_svc_uuids[s];`,
    `    if (__tc_ble_uuid_is_128(u)) {`,
    `        ble_uuid128_t* obj = &__tc_ble_svc_uuid128_objs[s];`,
    `        obj->u.type = BLE_UUID_TYPE_128;`,
    `        __tc_ble_uuid128_parse(obj->value, u);`,
    `        return &obj->u;`,
    `    } else {`,
    `        __tc_ble_svc_uuid16_objs[s] = (ble_uuid16_t)BLE_UUID16_INIT(static_cast<uint16_t>(strtol(u, NULL, 16)));`,
    `        return &__tc_ble_svc_uuid16_objs[s].u;`,
    `    }`,
    `}`,
    ``,
    `static const ble_uuid_t* __tc_ble_make_chr_uuid(int c) {`,
    `    const char* u = __tc_ble_char_defs[c].uuid_str;`,
    `    if (__tc_ble_char_defs[c].uuid_is_128) {`,
    `        ble_uuid128_t* obj = &__tc_ble_chr_uuid128_objs[c];`,
    `        obj->u.type = BLE_UUID_TYPE_128;`,
    `        __tc_ble_uuid128_parse(obj->value, u);`,
    `        return &obj->u;`,
    `    } else {`,
    `        __tc_ble_chr_uuid16_objs[c] = (ble_uuid16_t)BLE_UUID16_INIT(static_cast<uint16_t>(strtol(u, NULL, 16)));`,
    `        return &__tc_ble_chr_uuid16_objs[c].u;`,
    `    }`,
    `}`,
    ``,
    `static void __tc_ble_build_svc_table(void) {`,
    `    int chr_idx = 0;`,
    `    for (int s = 0; s < __tc_ble.svc_count; s++) {`,
    `        __tc_ble_svcs[s].type = BLE_GATT_SVC_TYPE_PRIMARY;`,
    `        __tc_ble_svcs[s].uuid = __tc_ble_make_svc_uuid(s);`,
    `        __tc_ble_svcs[s].characteristics = &__tc_ble_chr_defs[chr_idx];`,
    `        for (int c = 0; c < __tc_ble_char_count; c++) {`,
    `            if (__tc_ble_char_defs[c].svc_index == s && __tc_ble_char_defs[c].uuid_str) {`,
    `                __tc_ble_chr_defs[chr_idx].uuid = __tc_ble_make_chr_uuid(c);`,
    `                __tc_ble_chr_defs[chr_idx].access_cb = __tc_ble_gatt_access;`,
    `                __tc_ble_chr_defs[chr_idx].arg = (void*)(intptr_t)c;`,
    `                int flags = 0;`,
    `                if (__tc_ble_char_defs[c].perms & 1) flags |= BLE_GATT_CHR_F_READ;`,
    `                if (__tc_ble_char_defs[c].perms & 2) flags |= BLE_GATT_CHR_F_WRITE;`,
    `                if (__tc_ble_char_defs[c].perms & 4) flags |= BLE_GATT_CHR_F_NOTIFY;`,
    `                __tc_ble_chr_defs[chr_idx].flags = (ble_gatt_chr_flags)flags;`,
    `                __tc_ble_chr_defs[chr_idx].min_key_size = 0;`,
    `                __tc_ble_chr_defs[chr_idx].descriptors = NULL;`,
    `                __tc_ble_chr_defs[chr_idx].val_handle = 0;`,
    `                chr_idx++;`,
    `            }`,
    `        }`,
    `        __tc_ble_chr_defs[chr_idx].uuid = NULL;`,
    `        chr_idx++;`,
    `    }`,
    `    __tc_ble_svcs[__tc_ble.svc_count].type = 0;`,
    `    __tc_ble_svcs[__tc_ble.svc_count].uuid = NULL;`,
    `    __tc_ble_svcs[__tc_ble.svc_count].characteristics = NULL;`,
    `}`,
    ``,
    `// After ble_gatts_add_svcs, NimBLE assigns each characteristic a value handle`,
    `// (the attribute handle a client writes/notifies against) and writes it into the`,
    `// same ble_gatt_chr_def array we built. Walk those entries and copy each`,
    `// val_handle into __tc_ble.val_handles, keyed by the characteristic index we`,
    `// stashed in each entry's arg during build_svc_table. notify then looks the`,
    `// handle up by index instead of always notifying handle 0.`,
    `static void __tc_ble_capture_val_handles(void) {`,
    `    for (int i = 0; i < static_cast<int>(__TC_BLE_MAX_CHARS + __TC_BLE_MAX_SVCS); i++) {`,
    `        if (__tc_ble_chr_defs[i].uuid == NULL) continue;`,
    `        int c = static_cast<int>(intptr_t)__tc_ble_chr_defs[i].arg;`,
    `        if (c >= 0 && c < __TC_BLE_MAX_CHARS) {`,
    `            __tc_ble.val_handles[c] = __tc_ble_chr_defs[i].val_handle;`,
    `        }`,
    `    }`,
    `}`,
    ``,
    `static inline void __tc_ble_server_begin(const char* name) {`,
    `    __tc_ble_ensure_init();`,
    `    ble_svc_gap_init();`,
    `    ble_svc_gatt_init();`,
    `    ble_svc_gap_device_name_set(name);`,
    `    // If no explicit service was added but characteristics exist, create`,
    `    // a default service (0x180F-like custom) so they appear in the GATT table.`,
    `    if (__tc_ble.svc_count == 0 && __tc_ble_char_count > 0) {`,
    `        for (int c = 0; c < __tc_ble_char_count; c++) {`,
    `            __tc_ble_char_defs[c].svc_index = 0;`,
    `        }`,
    `        __tc_ble_add_service("181A"); // Environmental Sensing (matches demo)`,
    `    }`,
    `    __tc_ble_build_svc_table();`,
    `    ble_gatts_count_cfg(__tc_ble_svcs);`,
    `    ble_gatts_add_svcs(__tc_ble_svcs);`,
    `    // NimBLE has now assigned val_handles into __tc_ble_chr_defs; snapshot them`,
    `    // so notify can resolve a characteristic index to its value handle.`,
    `    __tc_ble_capture_val_handles();`,
    `    // Launch the NimBLE host task AFTER all services are registered.`,
    `    // Starting it earlier (in ensure_init) makes the sync callback fire,`,
    `    // before GATT setup, crashing in ble_hs_id_infer_auto.`,
    `    nimble_port_freertos_init(__tc_ble_host_task);`,
    `}`,
    ``,
    `static void __tc_ble_advertise_start(void) {`,
    `    if (!__tc_ble.inited) return;`,
    `    int rc;`,
    `    const char* n = __tc_ble.name[0] ? __tc_ble.name : "TypeCAD";`,
    `    // Legacy advertising packets are capped at 31 bytes, and each field carries`,
    `    // a 2-byte type+length overhead. Flags (3B) + TX power (3B) + a complete`,
    `    // local name overflow that budget for any name longer than ~20 chars, and`,
    `    // ble_gap_adv_set_fields returns BLE_HS_EMSGSIZE — leaving the device`,
    `    // silently undiscoverable. Keep the adv packet to the small fixed fields`,
    `    // and move the (possibly long) complete name into the scan response, which`,
    `    // has its own 31-byte budget fetched on demand by a scanning central.`,
    `    struct ble_hs_adv_fields adv;`,
    `    memset(&adv, 0, sizeof(adv));`,
    `    adv.flags = BLE_HS_ADV_F_DISC_GEN | BLE_HS_ADV_F_BREDR_UNSUP;`,
    `    adv.tx_pwr_lvl_is_present = 1;`,
    `    rc = ble_gap_adv_set_fields(&adv);`,
    `    if (rc != 0 && rc != BLE_HS_EALREADY && rc != BLE_HS_EBUSY) {`,
    `        ESP_LOGW("tc", "ble: adv_set_fields rc=%d", rc);`,
    `    }`,
    `    struct ble_hs_adv_fields rsp;`,
    `    memset(&rsp, 0, sizeof(rsp));`,
    `    rsp.name = (uint8_t*)n;`,
    `    rsp.name_len = strlen(n);`,
    `    rsp.name_is_complete = 1;`,
    `    rc = ble_gap_adv_rsp_set_fields(&rsp);`,
    `    if (rc != 0 && rc != BLE_HS_EALREADY && rc != BLE_HS_EBUSY) {`,
    `        ESP_LOGW("tc", "ble: adv_rsp_set_fields rc=%d", rc);`,
    `    }`,
    `    struct ble_gap_adv_params advp;`,
    `    memset(&advp, 0, sizeof(advp));`,
    `    advp.conn_mode = BLE_GAP_CONN_MODE_UND;`,
    `    advp.disc_mode = BLE_GAP_DISC_MODE_GEN;`,
    `    rc = ble_gap_adv_start(__tc_ble_own_addr_type, NULL, BLE_HS_FOREVER,`,
    `                           &advp, __tc_ble_gap_event, NULL);`,
    `    if (rc != 0 && rc != BLE_HS_EALREADY && rc != BLE_HS_EBUSY) {`,
    `        ESP_LOGW("tc", "ble: adv_start rc=%d", rc);`,
    `    }`,
    `    __tc_ble.advertising = true;`,
    `}`,
    ``,
    `static inline void __tc_ble_advertise_stop(void) {`,
    `    ble_gap_adv_stop();`,
    `    __tc_ble.advertising = false;`,
    `}`,
    ``,
    `// Push a new value to subscribed clients. Uses ble_gatts_notify_custom, which`,
    `// takes the connection handle, the characteristic's value handle, and an os_mbuf`,
    `// holding the payload. The stack frees the os_mbuf regardless of outcome, so we`,
    `// allocate a fresh one per call. Encodes value per the characteristic's type.`,
    `static inline void __tc_ble_notify(int idx, int16_t value) {`,
    `    if (idx < 0 || idx >= __TC_BLE_MAX_CHARS) return;`,
    `    if (__tc_ble.conn_handle < 0) return;  // no active connection to notify`,
    `    uint16_t vh = __tc_ble.val_handles[idx];`,
    `    if (vh == 0) return;  // characteristic not registered (or not notify-capable)`,
    `    const char* t = __tc_ble_char_defs[idx].type;`,
    `    struct os_mbuf* om = NULL;`,
    `    if (t && strcmp(t, "uint32") == 0) {`,
    `        uint32_t u = static_cast<uint32_t>(value);`,
    `        om = os_msys_get(sizeof(u), 0);`,
    `        if (om) os_mbuf_append(om, &u, sizeof(u));`,
    `    } else if (t && strcmp(t, "float32") == 0) {`,
    `        float f = static_cast<float>(value);`,
    `        om = os_msys_get(sizeof(f), 0);`,
    `        if (om) os_mbuf_append(om, &f, sizeof(f));`,
    `    } else if (t && strcmp(t, "boolean") == 0) {`,
    `        uint8_t b = value ? 1 : 0;`,
    `        om = os_msys_get(sizeof(b), 0);`,
    `        if (om) os_mbuf_append(om, &b, sizeof(b));`,
    `    } else {`,
    `        // uint8/16, int8/16/32 → int16`,
    `        int16_t s = value;`,
    `        om = os_msys_get(sizeof(s), 0);`,
    `        if (om) os_mbuf_append(om, &s, sizeof(s));`,
    `    }`,
    `    if (!om) return;`,
    `    int rc = ble_gatts_notify_custom(__tc_ble.conn_handle, vh, om);`,
    `    if (rc != 0 && rc != BLE_HS_ENOTCONN) {`,
    `        ESP_LOGD("tc", "ble: notify rc=%d", rc);`,
    `    }`,
    `}`,
    ``,
    `static inline bool __tc_ble_until_connected(uint32_t timeout_ms) {`,
    `    __tc_ble_ensure_init();`,
    `    int64_t deadline = esp_timer_get_time() + (int64_t)timeout_ms * 1000;`,
    `    while (!__tc_ble_is_connected()) {`,
    `        if (timeout_ms > 0 && esp_timer_get_time() >= deadline) return false;`,
    `        vTaskDelay(pdMS_TO_TICKS(50));`,
    `    }`,
    `    return true;`,
    `}`,
    ``,
    `static inline void __tc_ble_until_connected_start(void) {`,
    `    __tc_ble_ensure_init();`,
    `}`,
    `// CUTTLEFISH_BLE_END`,
    ``,
  ];
}

/** Render a HAL field: pass through (already rendered by the resolver). */
function s(v: unknown): string {
  return String(v);
}

/** Resolve a HAL ble.* op to native ESP-IDF NimBLE C++. */
export function lowerBle(op: HALOpIR): { code?: string; expression?: string } {
  const o = op as any;
  switch (op.operation) {
    case 'ble.server_begin':
      return { code: `__tc_ble_server_begin(${s(o.name)});` };
    case 'ble.advertise_start':
      return { code: `__tc_ble_advertise_start();` };
    case 'ble.advertise_stop':
      return { code: `__tc_ble_advertise_stop();` };
    case 'ble.add_service':
      return { code: `__tc_ble_add_service(${s(o.uuid)});` };
    case 'ble.add_char':
      return { code: `__tc_ble_add_char(${s(o.index)}, ${s(o.uuid)}, ${s(o.type)}, ${s(o.perms)}, ${s(o.svcIndex ?? 0)});` };
    case 'ble.on_read':
      return { code: `__tc_ble.on_read[__tc_ble.current_char] = (void*)(${s(o.handler)});` };
    case 'ble.on_write':
      return { code: `__tc_ble.on_write[__tc_ble.current_char] = (${s(o.handler)});` };
    case 'ble.on_connect':
      return { code: `__tc_ble.on_connect = (${s(o.handler)});` };
    case 'ble.on_disconnect':
      return { code: `__tc_ble.on_disconnect = (${s(o.handler)});` };
    case 'ble.notify':
      return { expression: `__tc_ble_notify(__tc_ble.current_char, ${s(o.value)})` };
    case 'ble.is_connected':
      return { expression: `__tc_ble_is_connected()` };
    case 'ble.client_count':
      return { expression: `__tc_ble_client_count()` };
    case 'ble.status':
      return { expression: `__tc_ble.status` };
    case 'ble.set_name':
      return { code: `__tc_ble_set_name(${s(o.name)});` };
    case 'ble.set_tx_power':
      return { code: `__tc_ble_set_tx_power(${s(o.dbm)});` };
    case 'ble.until_connected':
      return { expression: `__tc_ble_until_connected(${s(o.timeoutMs)})` };
    case 'ble.until_connected_start':
      return { code: `__tc_ble_until_connected_start();` };
    default:
      throw new Error(`framework-esp32 does not yet support HAL op \`${op.operation}\`.`);
  }
}
