import type { HALOpIR } from '@typecad/cuttlefish/api/shared';

/**
 * Native ESP-IDF NimBLE runtime shim (`__tc_ble_*`). Uses the nimble_host stack
 * (not Bluedroid). GATT peripheral role only.
 *
 * State mirrors the HAL BleStatus enum:
 *   0 Idle, 1 Initializing, 2 Advertising, 3 Connected, 4 Error.
 *
 * All helpers are `static inline` so unused ones don't trip -Wunused-function
 * in the single generated TU.
 */
export function bleInitLines(): string[] {
  return [
    `// CUTTLEFISH_BLE_BEGIN`,
    `#define __TC_BLE_MAX_CHARS 16`,
    `#define __TC_BLE_MAX_SVCS 8`,
    ``,
    `// Forward declarations (advertise_start is called from gap_event + on_sync).`,
    `static void __tc_ble_advertise_start(void);`,
    `static int __tc_ble_gap_event(struct ble_gap_event *event, void *arg);`,
    ``,
    `// Read callback returns the characteristic value; write callback receives it.`,
    `// The access CB bridges NimBLE's ble_gatt_access_ctxt to these typed callbacks.`,
    `typedef int  (*__tc_ble_read_cb_t)(void);`,
    `typedef void (*__tc_ble_write_cb_t)(int value);`,
    ``,
    `// Deferred characteristic definition (populated before __tc_ble_server_begin).`,
    `typedef struct {`,
    `    uint16_t uuid16;      // 16-bit UUID (0 = unused slot)`,
    `    int perms;            // bitmask: READ=1, WRITE=2, NOTIFY=4`,
    `    int svc_index;        // which service this char belongs to`,
    `} __tc_ble_char_def_t;`,
    ``,
    `static struct {`,
    `    int status;                // BleStatus enum`,
    `    bool inited;`,
    `    bool advertising;`,
    `    int connected_clients;`,
    `    int conn_handle;           // active connection handle (-1 = none)`,
    `    uint16_t svc_count;`,
    `    __tc_ble_read_cb_t   on_read[__TC_BLE_MAX_CHARS];`,
    `    __tc_ble_write_cb_t  on_write[__TC_BLE_MAX_CHARS];`,
    `    char name[32];`,
    `} __tc_ble = { 0, false, false, 0, -1, 0, {}, {}, {} };`,
    ``,
    `static __tc_ble_char_def_t __tc_ble_char_defs[__TC_BLE_MAX_CHARS];`,
    `static int __tc_ble_char_count = 0;`,
    `static uint16_t __tc_ble_svc_uuids[__TC_BLE_MAX_SVCS];`,
    ``,
    `// Static pools for the synthesized NimBLE GATT table.`,
    `// ble_uuid16_t objects must persist for the lifetime of the stack.`,
    `static ble_uuid16_t __tc_ble_svc_uuid_objs[__TC_BLE_MAX_SVCS];`,
    `static ble_uuid16_t __tc_ble_chr_uuid_objs[__TC_BLE_MAX_CHARS];`,
    `static struct ble_gatt_chr_def __tc_ble_chr_defs[__TC_BLE_MAX_CHARS + __TC_BLE_MAX_SVCS];`,
    `static struct ble_gatt_svc_def __tc_ble_svcs[__TC_BLE_MAX_SVCS + 1];`,
    ``,
    `// ── GATT access callback: bridges NimBLE → user read/write handlers ──`,
    `static int __tc_ble_gatt_access(uint16_t conn_handle, uint16_t attr_handle,`,
    `                                struct ble_gatt_access_ctxt *ctxt, void *arg) {`,
    `    (void)conn_handle; (void)attr_handle; (void)arg;`,
    `    // Match by char index using attr_handle offset from the first char handle.`,
    `    // For v1, service the first matching read/write handler found.`,
    `    for (int i = 0; i < __tc_ble_char_count; i++) {`,
    `        if (ctxt->op == BLE_GATT_ACCESS_OP_READ_CHR && __tc_ble.on_read[i]) {`,
    `            int val = __tc_ble.on_read[i]();`,
    `            int16_t sval = (int16_t)val;`,
    `            os_mbuf_append(ctxt->om, &sval, sizeof(sval));`,
    `            return 0;`,
    `        }`,
    `        if (ctxt->op == BLE_GATT_ACCESS_OP_WRITE_CHR && __tc_ble.on_write[i]) {`,
    `            int val = 0;`,
    `            if (OS_MBUF_PKTLEN(ctxt->om) >= (int)sizeof(int16_t)) {`,
    `                int16_t sval = 0;`,
    `                memcpy(&sval, ctxt->om->om_data, sizeof(sval));`,
    `                val = sval;`,
    `            }`,
    `            __tc_ble.on_write[i](val);`,
    `            return 0;`,
    `        }`,
    `    }`,
    `    return 0;`,
    `}`,
    ``,
    `// ── GAP event handler ──`,
    `static int __tc_ble_gap_event(struct ble_gap_event *event, void *arg) {`,
    `    (void)arg;`,
    `    switch (event->type) {`,
    `    case BLE_GAP_EVENT_CONNECT:`,
    `        if (event->connect.status == 0) {`,
    `            __tc_ble.connected_clients = __tc_ble.connected_clients + 1;`,
    `            __tc_ble.conn_handle = event->connect.conn_handle;`,
    `            __tc_ble.status = 3; // Connected`,
    `        } else {`,
    `            __tc_ble_advertise_start();`,
    `        }`,
    `        break;`,
    `    case BLE_GAP_EVENT_DISCONNECT:`,
    `        __tc_ble.connected_clients = __tc_ble.connected_clients > 0 ? __tc_ble.connected_clients - 1 : 0;`,
    `        __tc_ble.conn_handle = -1;`,
    `        __tc_ble.status = 2; // Advertising`,
    `        __tc_ble_advertise_start();`,
    `        break;`,
    `    default: break;`,
    `    }`,
    `    return 0;`,
    `}`,
    ``,
    `// ── NimBLE host task (called by nimble_port_freertos_init) ──`,
    `static void __tc_ble_host_task(void *param) {`,
    `    (void)param;`,
    `    nimble_port_run();  // blocks — processes BLE events until stack stops`,
    `    nimble_port_freertos_deinit();`,
    `}`,
    ``,
    `// ── Sync callback: NimBLE stack is ready — start advertising ──`,
    `static uint8_t __tc_ble_own_addr_type;`,
    `static void __tc_ble_on_sync(void) {`,
    `    int rc = ble_hs_id_infer_auto(0, &__tc_ble_own_addr_type);`,
    `    if (rc != 0) {`,
    `        printf("ble: id_infer_auto rc=%d\\n", rc);`,
    `        return;`,
    `    }`,
    `    __tc_ble.status = 2; // Advertising`,
    `    __tc_ble_advertise_start();`,
    `}`,
    ``,
    `static void __tc_ble_ensure_init(void) {`,
    `    if (__tc_ble.inited) return;`,
    `    __tc_ble.conn_handle = -1;`,
    `    // NVS is required by the PHY/BT controller for calibration data.`,
    `    esp_err_t err = nvs_flash_init();`,
    `    if (err == ESP_ERR_NVS_NO_FREE_PAGES || err == ESP_ERR_NVS_NEW_VERSION_FOUND) {`,
    `        nvs_flash_erase();`,
    `        nvs_flash_init();`,
    `    }`,
    `    ESP_ERROR_CHECK(nimble_port_init());`,
    `    ble_hs_cfg.sync_cb = __tc_ble_on_sync;`,
    `    __tc_ble.status = 1; // Initializing`,
    `    __tc_ble.inited = true;`,
    `}`,
    ``,
    `static inline bool __tc_ble_is_connected(void) {`,
    `    return __tc_ble.status == 3 && __tc_ble.connected_clients > 0;`,
    `}`,
    ``,
    `static inline int __tc_ble_client_count(void) {`,
    `    return __tc_ble.connected_clients;`,
    `}`,
    ``,
    `static inline void __tc_ble_set_name(const char* name) {`,
    `    strlcpy(__tc_ble.name, name, sizeof(__tc_ble.name));`,
    `}`,
    ``,
    `// TX power: NimBLE configures this via PHY/controller at init, not runtime.`,
    `static inline void __tc_ble_set_tx_power(int dbm) {`,
    `    (void)dbm;`,
    `}`,
    ``,
    `// ── Deferred service graph ──`,
    `static inline void __tc_ble_add_service(const char* uuid_str) {`,
    `    if (__tc_ble.svc_count < __TC_BLE_MAX_SVCS) {`,
    `        __tc_ble_svc_uuids[__tc_ble.svc_count] = (uint16_t)strtol(uuid_str, NULL, 16);`,
    `        __tc_ble.svc_count++;`,
    `    }`,
    `}`,
    ``,
    `static inline void __tc_ble_add_char(int idx, const char* uuid_str, const char* type, int perms, int svc_index) {`,
    `    (void)type;`,
    `    if (idx >= 0 && idx < __TC_BLE_MAX_CHARS) {`,
    `        __tc_ble_char_defs[idx].uuid16 = (uint16_t)strtol(uuid_str, NULL, 16);`,
    `        __tc_ble_char_defs[idx].perms = perms;`,
    `        __tc_ble_char_defs[idx].svc_index = svc_index;`,
    `        if (idx + 1 > __tc_ble_char_count) __tc_ble_char_count = idx + 1;`,
    `    }`,
    `}`,
    ``,
    `// Build the NimBLE ble_gatt_svc_def[] tree from the deferred graph.`,
    `static void __tc_ble_build_svc_table(void) {`,
    `    for (int s = 0; s < __tc_ble.svc_count; s++) {`,
    `        __tc_ble_svc_uuid_objs[s] = (ble_uuid16_t)BLE_UUID16_INIT(__tc_ble_svc_uuids[s]);`,
    `    }`,
    `    int chr_idx = 0;`,
    `    for (int s = 0; s < __tc_ble.svc_count; s++) {`,
    `        __tc_ble_svcs[s].type = BLE_GATT_SVC_TYPE_PRIMARY;`,
    `        __tc_ble_svcs[s].uuid = &__tc_ble_svc_uuid_objs[s].u;`,
    `        __tc_ble_svcs[s].characteristics = &__tc_ble_chr_defs[chr_idx];`,
    `        for (int c = 0; c < __tc_ble_char_count; c++) {`,
    `            if (__tc_ble_char_defs[c].svc_index == s && __tc_ble_char_defs[c].uuid16 != 0) {`,
    `                __tc_ble_chr_uuid_objs[c] = (ble_uuid16_t)BLE_UUID16_INIT(__tc_ble_char_defs[c].uuid16);`,
    `                __tc_ble_chr_defs[chr_idx].uuid = &__tc_ble_chr_uuid_objs[c].u;`,
    `                __tc_ble_chr_defs[chr_idx].access_cb = __tc_ble_gatt_access;`,
    `                __tc_ble_chr_defs[chr_idx].arg = NULL;`,
    `                int flags = 0;`,
    `                if (__tc_ble_char_defs[c].perms & 1) flags |= BLE_GATT_CHR_F_READ;`,
    `                if (__tc_ble_char_defs[c].perms & 2) flags |= BLE_GATT_CHR_F_WRITE;`,
    `                if (__tc_ble_char_defs[c].perms & 4) flags |= BLE_GATT_CHR_F_NOTIFY;`,
    `                __tc_ble_chr_defs[chr_idx].flags = (ble_gatt_chr_flags)flags;`,
    `                __tc_ble_chr_defs[chr_idx].min_key_size = 0;`,
    `                __tc_ble_chr_defs[chr_idx].descriptors = NULL;`,
    `                __tc_ble_chr_defs[chr_idx].val_handle = 0;`,
    `                chr_idx++;`,
    `            }`,
    `        }`,
    `        __tc_ble_chr_defs[chr_idx].uuid = NULL;`,
    `        chr_idx++;`,
    `    }`,
    `    __tc_ble_svcs[__tc_ble.svc_count].type = 0;`,
    `    __tc_ble_svcs[__tc_ble.svc_count].uuid = NULL;`,
    `    __tc_ble_svcs[__tc_ble.svc_count].characteristics = NULL;`,
    `}`,
    ``,
    `static inline void __tc_ble_server_begin(const char* name) {`,
    `    __tc_ble_ensure_init();`,
    `    ble_svc_gap_init();`,
    `    ble_svc_gatt_init();`,
    `    ble_svc_gap_device_name_set(name);`,
    `    // If no explicit service was added but characteristics exist, create`,
    `    // a default service (0x180F-like custom) so they appear in the GATT table.`,
    `    if (__tc_ble.svc_count == 0 && __tc_ble_char_count > 0) {`,
    `        for (int c = 0; c < __tc_ble_char_count; c++) {`,
    `            __tc_ble_char_defs[c].svc_index = 0;`,
    `        }`,
    `        __tc_ble_add_service("181A"); // Environmental Sensing (matches demo)`,
    `    }`,
    `    __tc_ble_build_svc_table();`,
    `    ble_gatts_count_cfg(__tc_ble_svcs);`,
    `    ble_gatts_add_svcs(__tc_ble_svcs);`,
    `    // Launch the NimBLE host task AFTER all services are registered.`,
    `    // Starting it earlier (in ensure_init) makes the sync callback fire`,
    `    // before GATT setup, crashing in ble_hs_id_infer_auto.`,
    `    nimble_port_freertos_init(__tc_ble_host_task);`,
    `}`,
    ``,
    `static void __tc_ble_advertise_start(void) {`,
    `    if (!__tc_ble.inited) return;`,
    `    struct ble_hs_adv_fields adv;`,
    `    memset(&adv, 0, sizeof(adv));`,
    `    adv.flags = BLE_HS_ADV_F_DISC_GEN | BLE_HS_ADV_F_BREDR_UNSUP;`,
    `    adv.tx_pwr_lvl_is_present = 1;`,
    `    const char* n = __tc_ble.name[0] ? __tc_ble.name : "TypeCAD";`,
    `    adv.name = (uint8_t*)n;`,
    `    adv.name_len = strlen(n);`,
    `    adv.name_is_complete = 1;`,
    `    ble_gap_adv_set_fields(&adv);`,
    `    struct ble_gap_adv_params advp;`,
    `    memset(&advp, 0, sizeof(advp));`,
    `    advp.conn_mode = BLE_GAP_CONN_MODE_UND;`,
    `    advp.disc_mode = BLE_GAP_DISC_MODE_GEN;`,
    `    int rc = ble_gap_adv_start(__tc_ble_own_addr_type, NULL, BLE_HS_FOREVER,`,
    `                               &advp, __tc_ble_gap_event, NULL);`,
    `    if (rc != 0 && rc != BLE_HS_EALREADY && rc != BLE_HS_EBUSY) {`,
    `        printf("ble: adv_start rc=%d\\n", rc);`,
    `    }`,
    `    __tc_ble.advertising = true;`,
    `}`,
    ``,
    `static inline void __tc_ble_advertise_stop(void) {`,
    `    ble_gap_adv_stop();`,
    `    __tc_ble.advertising = false;`,
    `}`,
    ``,
    `static inline void __tc_ble_notify(int idx, int16_t value) {`,
    `    (void)idx; (void)value;`,
    `    // ble_gatts_notify(conn, chr_val_handle) — needs the handle from the`,
    `    // registered GATT table. v1: no-op until handle tracking is wired.`,
    `}`,
    ``,
    `static inline bool __tc_ble_until_connected(uint32_t timeout_ms) {`,
    `    __tc_ble_ensure_init();`,
    `    int64_t deadline = esp_timer_get_time() + (int64_t)timeout_ms * 1000;`,
    `    while (!__tc_ble_is_connected()) {`,
    `        if (timeout_ms > 0 && esp_timer_get_time() >= deadline) return false;`,
    `        vTaskDelay(pdMS_TO_TICKS(50));`,
    `    }`,
    `    return true;`,
    `}`,
    ``,
    `static inline void __tc_ble_until_connected_start(void) {`,
    `    __tc_ble_ensure_init();`,
    `}`,
    `// CUTTLEFISH_BLE_END`,
    ``,
  ];
}

/** Render a HAL field: pass through (already rendered by the resolver). */
function s(v: unknown): string {
  return String(v);
}

/** Resolve a HAL ble.* op to native ESP-IDF NimBLE C++. */
export function lowerBle(op: HALOpIR): { code?: string; expression?: string } {
  const o = op as any;
  switch (op.operation) {
    case 'ble.server_begin':
      return { code: `__tc_ble_server_begin(${s(o.name)});` };
    case 'ble.advertise_start':
      return { code: `__tc_ble_advertise_start();` };
    case 'ble.advertise_stop':
      return { code: `__tc_ble_advertise_stop();` };
    case 'ble.add_service':
      return { code: `__tc_ble_add_service(${s(o.uuid)});` };
    case 'ble.add_char':
      return { code: `__tc_ble_add_char(${s(o.index)}, ${s(o.uuid)}, ${s(o.type)}, ${s(o.perms)}, ${s(o.svcIndex ?? 0)});` };
    case 'ble.on_read':
      return { code: `__tc_ble.on_read[${s(o.index)}] = (${s(o.handler)});` };
    case 'ble.on_write':
      return { code: `__tc_ble.on_write[${s(o.index)}] = (${s(o.handler)});` };
    case 'ble.notify':
      return { expression: `__tc_ble_notify(${s(o.index)}, ${s(o.value)})` };
    case 'ble.is_connected':
      return { expression: `__tc_ble_is_connected()` };
    case 'ble.client_count':
      return { expression: `__tc_ble_client_count()` };
    case 'ble.status':
      return { expression: `__tc_ble.status` };
    case 'ble.set_name':
      return { code: `__tc_ble_set_name(${s(o.name)});` };
    case 'ble.set_tx_power':
      return { code: `__tc_ble_set_tx_power(${s(o.dbm)});` };
    case 'ble.until_connected':
      return { expression: `__tc_ble_until_connected(${s(o.timeoutMs)})` };
    case 'ble.until_connected_start':
      return { code: `__tc_ble_until_connected_start();` };
    default:
      throw new Error(`framework-esp32 does not yet support HAL op \`${op.operation}\`.`);
  }
}
