import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { SpawnSyncOptions } from 'node:child_process';
import { type IdfRoot, discoverIdfRoot } from './discover.js';
import { detectIdfEnv } from './idf-env.js';

const IS_WIN = process.platform === 'win32';

export const WRAPPER_NAME = IS_WIN ? 'cuttlefish-idf-env.bat' : 'cuttlefish-idf-env.sh';

/** Marker comment embedded in the wrapper so we can detect when the wrapper
 *  already targets the desired root (idempotence check). */
/** Marker comment embedded in the wrapper so we can detect when the wrapper
 *  already targets the desired root (idempotence check). Platform-specific
 *  comment prefix — REM in .bat, # in .sh. */
const ROOT_MARKER_PREFIX_POSIX = '# cuttlefish-idf-root:';
const ROOT_MARKER_PREFIX_WIN = 'REM cuttlefish-idf-root:';

export interface ActivationResult {
  /** True if a wrapper was generated or already present for this root.
   *  False if the env was already sourced and no wrapper is needed. */
  activated: boolean;
  /** The IDF root the wrapper sources. */
  root: IdfRoot;
  /** Absolute path to the wrapper file (only meaningful when activated=true). */
  wrapperPath: string;
  /** Human-readable status line for surfacing to the user. */
  message: string;
}

/** Return the absolute path to the wrapper for a given project dir. */
export function wrapperPathFor(projectDir: string): string {
  return join(projectDir, WRAPPER_NAME);
}

/** Build the wrapper script contents that source <root> and forward to idf.py. */
export function buildWrapperContent(root: IdfRoot): string {
  const rootPath = root.path;
  if (IS_WIN) {
    return [
      '@echo off',
      'REM Auto-generated by @typecad/framework-esp32.',
      'REM Activates the ESP-IDF environment, then runs idf.py with all forwarded args.',
      'REM Inspect or edit freely; deleted automatically when the project is regenerated.',
      `${ROOT_MARKER_PREFIX_WIN} ${rootPath}`,
      `call "${rootPath}\\export.bat"`,
      'idf.py %*',
      '',
    ].join('\r\n');
  }
  return [
    '#!/usr/bin/env bash',
    '# Auto-generated by @typecad/framework-esp32.',
    '# Sources the ESP-IDF environment, then runs idf.py with all forwarded args.',
    '# Inspect or edit freely; deleted automatically when the project is regenerated.',
    `${ROOT_MARKER_PREFIX_POSIX} ${rootPath}`,
    `source "${rootPath}/export.sh"`,
    'exec idf.py "$@"',
    '',
  ].join('\n');
}

/** The marker line for a given root, in the current platform's comment syntax. */
function markerLineFor(root: IdfRoot): string {
  const prefix = IS_WIN ? ROOT_MARKER_PREFIX_WIN : ROOT_MARKER_PREFIX_POSIX;
  return `${prefix} ${root.path}`;
}

/** Write the wrapper if missing or stale (root changed). Returns the wrapper path. */
function ensureWrapper(projectDir: string, root: IdfRoot): { wrapperPath: string; wrote: boolean } {
  const wrapperPath = wrapperPathFor(projectDir);
  const desiredContent = buildWrapperContent(root);
  const markerLine = markerLineFor(root);
  if (existsSync(wrapperPath)) {
    try {
      const existing = readFileSync(wrapperPath, 'utf8');
      // Idempotence: if the existing wrapper already references this exact root,
      // don't rewrite (avoids mtime churn on every build).
      if (existing.includes(markerLine)) {
        return { wrapperPath, wrote: false };
      }
    } catch {
      // Fall through and rewrite.
    }
  }
  writeFileSync(wrapperPath, desiredContent);
  return { wrapperPath, wrote: true };
}

/**
 * Ensure the ESP-IDF environment is activated for the given project.
 *
 * - If the env is already sourced in the current shell (detectIdfEnv().available),
 *   returns { activated: false } — no wrapper needed, idf.py can be called directly.
 * - Otherwise discovers the IDF root and generates a wrapper script that sources
 *   export.{sh,bat} and runs idf.py. Subsequent idf.py invocations should go
 *   through this wrapper (see idfSpawn).
 *
 * Throws if the env is not sourced AND discovery fails to find an IDF root.
 */
export function ensureIdfActivated(projectDir: string): ActivationResult {
  const env = detectIdfEnv();
  if (env.available) {
    // Already sourced — no activation needed. We don't have a discovered-root
    // object in this branch (the env's idfPath is the root), but we can
    // synthesize one for the return shape.
    return {
      activated: false,
      root: { path: env.idfPath!, version: undefined, source: 'env' },
      wrapperPath: '',
      message: 'ESP-IDF environment already active in current shell.',
    };
  }

  const root = discoverIdfRoot();
  if (!root) {
    throw new Error(env.message);
  }

  const { wrapperPath } = ensureWrapper(projectDir, root);
  return {
    activated: true,
    root,
    wrapperPath,
    message: `[framework-esp32] Auto-sourced ESP-IDF ${root.version ?? ''} from ${root.path} via ${WRAPPER_NAME} (discovered via ${root.source})`,
  };
}

// ── Per-spawn invocation helper ──────────────────────────────────────────────

export interface IdfInvocation {
  /** The command to spawnSync: 'idf.py' (env already sourced) or the shell
   *  that runs the wrapper ('cmd.exe' on Windows, 'bash' on POSIX). */
  command: string;
  /** Args for the command. */
  args: string[];
  /** The base spawn options (cwd/timeout/encoding/stdio), passed through. */
  options: SpawnSyncOptions;
  /** The activation result, if activation happened. Callers may surface
   *  result.message to the user. */
  activation?: ActivationResult;
}

/**
 * Build a spawn invocation that runs `idf.py <idfArgs>` — either directly
 * (if the env is already sourced) or through the generated wrapper.
 *
 * `baseOptions` carries the cwd/timeout/stdio settings the caller wants;
 * idfSpawn preserves them. The returned object is suitable for direct
 * destructuring into spawnSync: `const inv = idfSpawn(...); spawnSync(inv.command, inv.args, inv.options)`.
 */
export function idfSpawn(projectDir: string, idfArgs: string[], baseOptions: SpawnSyncOptions): IdfInvocation {
  const env = detectIdfEnv();
  if (env.available) {
    // Direct invocation — zero overhead, current behavior.
    return { command: 'idf.py', args: idfArgs, options: baseOptions };
  }

  // Need to activate. ensureIdfActivated throws on discovery failure; let it
  // propagate so callers can surface the actionable error.
  const activation = ensureIdfActivated(projectDir);
  const wrapperPath = activation.wrapperPath;

  if (IS_WIN) {
    // cmd.exe /c "wrapper.bat arg1 arg2 ..." — cmd.exe parses %* in the wrapper.
    // Quote the wrapper path; idf.py args pass through cmd's own parser.
    const cmdLine = `"${wrapperPath}" ${idfArgs.join(' ')}`;
    // export.bat refuses to run when MSYSTEM is set ("for CMD.EXE only"). When
    // cuttlefish is invoked from Git Bash / MSYS, MSYSTEM=MINGW64 leaks into
    // the spawned cmd.exe's env. Strip MSYS markers so export.bat accepts the
    // env. We rebuild the env from process.env without the offending keys.
    const childEnv = { ...process.env };
    for (const k of Object.keys(childEnv)) {
      if (k === 'MSYSTEM' || k === 'MSYSTEM_CHOST' || k === 'MSYSTEM_PREFIX'
          || k === 'MINGW_CHOST' || k === 'MINGW_PREFIX' || k === 'MINGW_PACKAGE_PREFIX') {
        delete childEnv[k];
      }
    }
    return {
      command: 'cmd.exe',
      args: ['/d', '/s', '/c', cmdLine],
      options: { ...baseOptions, env: childEnv },
      activation,
    };
  }
  // bash -c 'wrapper.sh "$@"' bash arg1 arg2 ... — preserves arg boundaries
  // via bash's "$@" expansion (the wrapper's exec idf.py "$@" re-forwards them).
  return {
    command: 'bash',
    args: ['-c', `"${wrapperPath}" "$@"`, 'bash', ...idfArgs],
    options: baseOptions,
    activation,
  };
}
