/**
 * Generators for the ESP32-S3 GDB debug artifacts. All output is deterministic
 * and idempotent — re-running with the same inputs produces byte-identical
 * files, so toggling --debug off and on doesn't churn the working tree.
 *
 * Paths are baked at generation time: VS Code sees no angle-bracket placeholders.
 */

export interface DebugConfigOptions {
  /** ELF base name, e.g. 'demo' → build/demo.elf */
  projectName: string;
  /** Workspace-relative path to the sketch dir, e.g. 'demos/demo' */
  sketchRel: string;
  /** Serial port, from config.port ?? cliPort */
  port: string;
  /** Build target (currently only 'esp32s3' is wired for gdb) */
  target: string;
}

function outRel(opts: DebugConfigOptions): string {
  return `${opts.sketchRel}/src/out-${opts.target}`;
}

export function buildLaunchJson(opts: DebugConfigOptions): string {
  const cfg = {
    version: '0.2.0',
    configurations: [
      {
        type: 'gdbtarget',
        request: 'attach',
        name: 'TypeCAD Debug (ESP32-S3)',
        program: `\${workspaceFolder}/${outRel(opts)}/build/${opts.projectName}.elf`,
        gdbPath: '${command:espIdf.getToolchainGdb}',
        target: { type: 'remote', host: 'localhost', port: '3333' },
        preLaunchTask: 'cuttlefish: debug prep',
        initCommands: [
          'set directories ${workspaceFolder}',
          'set auto-load safe-path ${workspaceFolder}',
          `source \${workspaceFolder}/${outRel(opts)}/.cuttlefish/.cuttlefish-gdb.py`,
          'set remote hardware-watchpoint-limit 2',
        ],
      },
    ],
  };
  return JSON.stringify(cfg, null, 2);
}

export function buildTasksJson(opts: DebugConfigOptions): string {
  const tasks = {
    version: '2.0.0',
    tasks: [
      {
        label: 'cuttlefish: start openocd',
        type: 'shell',
        command: `openocd -f \${workspaceFolder}/${outRel(opts)}/.cuttlefish/openocd.cfg`,
        isBackground: true,
        problemMatcher: {
          owner: 'openocd',
          pattern: { regexp: '^[^N]' },
          background: {
            activeOnStart: true,
            beginsPattern: '^Open On-Chip Debugger',
            endsPattern: '^Info : Listening on port 3333 for gdb connections',
          },
        },
      },
      {
        label: 'cuttlefish: build + flash',
        type: 'shell',
        command: `cuttlefish build --compile --upload --debug --port ${opts.port}`,
        options: { cwd: `\${workspaceFolder}/${opts.sketchRel}` },
      },
      {
        label: 'cuttlefish: debug prep',
        dependsOn: ['cuttlefish: start openocd', 'cuttlefish: build + flash'],
        dependsOrder: 'parallel',
      },
    ],
  };
  return JSON.stringify(tasks, null, 2);
}

export function buildOpenOcdCfg(): string {
  return 'source [find board/esp32s3-builtin.cfg]\n';
}

export function buildSdkconfigDefaultsDebug(): string {
  return [
    '# Auto-generated by cuttlefish for GDB debug builds.',
    '# Applied after sdkconfig.defaults via SDKCONFIG_DEFAULTS chain.',
    "# -Og (not -Os) so #line stepping doesn't jump erratically; LTO off",
    '# so DWARF symbols survive.',
    'CONFIG_COMPILER_OPTIMIZATION_DEBUG=y',
    'CONFIG_COMPILER_OPTIMIZATION_SIZE=',
    'CONFIG_COMPILER_OPTIMIZATION_ASSERTIONS_LEVEL=1',
  ].join('\n') + '\n';
}
