import type { GeneratedSourceMap } from '@typecad/cuttlefish/api';

/**
 * Generate the `.cuttlefish-gdb.py` GDB Python script that rewrites
 * hoisted `_isr_N` frame names in the VS Code call stack.
 *
 * Cuttlefish hoists anonymous lambdas passed as arguments into named free
 * functions `${prefix}_isr_${n}` (see top-level-prep.ts). Their sourceSpan
 * still points at the original lambda site, so #line markers jump to the
 * right TS location when stepping — but the call stack shows the synthetic
 * name. This frame-filter rewrites those names to `<lambda> @ file:line`.
 *
 * The map entries come from the existing .thcppmap.json sidecar, which
 * already records symbolName + tsSpan per generated range.
 */
export function generateGdbScript(map: GeneratedSourceMap): string {
  const isrEntries = map.entries.filter(
    (e) => e.symbolName && /_isr_\d+$/.test(e.symbolName),
  );

  const mapLines = isrEntries.length === 0
    ? '_ISR_MAP = {}'
    : '_ISR_MAP = {\n' +
      isrEntries
        .map((e) => `  "${e.symbolName}": "<lambda> @ ${e.tsSpan.filePath}:${e.tsSpan.startLine + 1}"`)
        .join(',\n') +
      '\n}';

  return `# Auto-generated by cuttlefish. Rewrites hoisted _isr_N frames.
# Do not edit — regenerated on every debug build.
import gdb
from gdb.FrameDecorator import FrameDecorator

${mapLines}

class _CuttlefishDecorator(FrameDecorator):
    def __init__(self, f):
        super().__init__(f)

    def function(self):
        name = super().function()
        return _ISR_MAP.get(name, name)

class _CuttlefishFrameFilter:
    def __init__(self):
        self.priority = 100
        self.enabled = True

    def filter(self, frame_iter):
        return (_CuttlefishDecorator(f) for f in frame_iter)

gdb.frame_filters["_cuttlefish_isr"] = _CuttlefishFrameFilter()
`;
}
