import { writeFileSync, existsSync, mkdirSync, readFileSync, rmSync } from 'node:fs';
import { join, basename, relative } from 'node:path';
import { sdkconfigDefaultsForTarget } from '../project/sdkconfig-defaults.js';
import type { ScaffoldComponents } from '../components/types.js';

/** Write a file only if the content differs from the existing file.
 *  Avoids mtime churn that invalidates cmake/ninja incremental builds. */
function writeIfChanged(filePath: string, content: string): void {
  if (existsSync(filePath)) {
    try {
      if (readFileSync(filePath, 'utf8') === content) return;
    } catch {
      // Read failed — fall through to write.
    }
  }
  writeFileSync(filePath, content);
}

/** Render `main/idf_component.yml` from managed deps. */
function renderComponentYml(managed: Record<string, string>): string {
  const lines = [
    '# Auto-generated by @typecad/framework-esp32 from cuttlefish.config.ts.',
    '# Edit deps in cuttlefish.config.ts (frameworkData.components.managed), not here.',
    'dependencies:',
  ];
  for (const [name, version] of Object.entries(managed)) {
    lines.push(`  ${name}: ${JSON.stringify(version)}`);
  }
  return lines.join('\n') + '\n';
}

/**
 * Emit the ESP-IDF project skeleton around the generated main.cc.
 * Idempotent: overwrites CMakeLists + sdkconfig.defaults + .gitignore,
 * materializes main/idf_component.yml from managed deps, leaves
 * main/main.cc alone (cuttlefish's emit pipeline owns that file).
 * Spec §3.2 + components design §Layer 2.
 */
export function scaffoldEspIdfProject(
  projectDir: string,
  target: string,
  components?: ScaffoldComponents,
): void {
  const mainDir = join(projectDir, 'main');
  if (!existsSync(mainDir)) mkdirSync(mainDir, { recursive: true });

  // ── Root CMakeLists.txt ────────────────────────────────────────────────
  // local paths are already resolved (absolute) by resolveComponents; emit
  // them relative to projectDir when they live inside the project so the
  // project stays machine-portable. Absolute paths outside the project are
  // emitted verbatim — that's the user's explicit choice.
  const absLocal = components?.local ?? [];
  const extraDirs = absLocal.map((abs) => {
    const rel = relative(projectDir, abs).replace(/\\/g, '/');
    const portable = rel.startsWith('..') || rel === '' ? abs.replace(/\\/g, '/') : rel;
    return `\${CMAKE_CURRENT_LIST_DIR}/${portable}`;
  });
  const extraDirsLines =
    extraDirs.length > 0
      ? ['', 'set(EXTRA_COMPONENT_DIRS', ...extraDirs.map((d) => `    ${d}`), ')', '']
      : [];

  writeIfChanged(
    join(projectDir, 'CMakeLists.txt'),
    [
      '# Auto-generated by @typecad/framework-esp32. Edit freely.',
      'cmake_minimum_required(VERSION 3.16)',
      ...extraDirsLines,
      'include($ENV{IDF_PATH}/tools/cmake/project.cmake)',
      '',
      `project(${JSON.stringify(basename(projectDir))})`,
      '',
    ].join('\n'),
  );

  // Always REQUIRE the IDF components the framework entrypoint / shims use.
  // Without this, IDF v5+/v6 can still link via main's special status on some
  // installs, but WiFi/NVS init then fails at runtime with an opaque reboot.
  // HTTP/TLS are always listed too: usesHttp gates the #includes/shim, but the
  // component must be on REQUIRES or esp_http_client.h / esp_crt_bundle.h are
  // invisible (IDF does not expose transitive include dirs to main).
  // bt is always listed so NimBLE headers (nimble_port.h, ble_hs.h, etc.) are
  // visible when the BLE shim is emitted (gated by usesBle in the strategy).
  const builtin = components?.builtin ?? [];
  const requires = Array.from(
    new Set([
      'nvs_flash',
      'esp_wifi',
      'esp_netif',
      'esp_event',
      'esp_timer',
      'esp_driver_uart',
      'esp_driver_gpio',
      'esp_driver_i2c',
      'esp_driver_spi',
      'esp_http_client',
      'esp-tls',
      'mbedtls',
      'bt',
      ...builtin,
    ]),
  );
  writeIfChanged(
    join(mainDir, 'CMakeLists.txt'),
    [
      '# Auto-generated by @typecad/framework-esp32.',
      'idf_component_register(SRCS "main.cc"',
      '                       INCLUDE_DIRS "."',
      `                       REQUIRES ${requires.join(' ')})`,
      '',
      '# ESP-IDF v6 / GCC 13+ enables -Werror for many warnings that the',
      '# cuttlefish runtime header (ported from Arduino) triggers. We demote only',
      '# the three known offenders so genuine warnings still fail the build:',
      '#   - multichar: touch-keyboard uses int-sized char constants like \'OK\'',
      '#   - overflow: same multichar constants truncated to char slots',
      '#   - missing-field-initializers: static tables with designated initializers',
      '# These are pre-existing patterns in the runtime header, not bugs.',
      'target_compile_options(${COMPONENT_LIB} PRIVATE',
      '    -Wno-error=multichar',
      '    -Wno-error=overflow',
      '    -Wno-error=missing-field-initializers',
      ')',
      '',
    ].join('\n'),
  );

  // ── main/idf_component.yml ─────────────────────────────────────────────
  const ymlPath = join(mainDir, 'idf_component.yml');
  const managed = components?.managed ?? {};
  if (Object.keys(managed).length > 0) {
    writeIfChanged(ymlPath, renderComponentYml(managed));
  } else if (existsSync(ymlPath)) {
    // Deps were removed since last scaffold — drop the file so reconfigure
    // doesn't keep fetching stale deps.
    rmSync(ymlPath, { force: true });
  }

  writeIfChanged(
    join(projectDir, 'sdkconfig.defaults'),
    sdkconfigDefaultsForTarget(target, components?.psram ?? false),
  );

  writeIfChanged(
    join(projectDir, '.gitignore'),
    [
      'build/',
      'sdkconfig',
      'managed_components/',
      'dependencies.lock',
      '# Auto-generated ESP-IDF env wrapper (per-machine; not portable)',
      'cuttlefish-idf-env.sh',
      'cuttlefish-idf-env.bat',
      '',
    ].join('\n'),
  );
}
