import { writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join, basename } from 'node:path';
import { sdkconfigDefaultsForTarget } from '../project/sdkconfig-defaults.js';

/**
 * Emit the ESP-IDF project skeleton around the generated main.cc.
 * Idempotent: overwrites CMakeLists + sdkconfig.defaults + .gitignore,
 * leaves main/main.cc alone (cuttlefish's emit pipeline owns that file).
 * Spec §3.2.
 */
export function scaffoldEspIdfProject(projectDir: string, target: string): void {
  const mainDir = join(projectDir, 'main');
  if (!existsSync(mainDir)) mkdirSync(mainDir, { recursive: true });

  writeFileSync(
    join(projectDir, 'CMakeLists.txt'),
    [
      '# Auto-generated by @typecad/framework-esp32. Edit freely.',
      'cmake_minimum_required(VERSION 3.16)',
      '',
      'include($ENV{IDF_PATH}/tools/cmake/project.cmake)',
      '',
      `project(${JSON.stringify(basename(projectDir))})`,
      '',
    ].join('\n'),
  );

  writeFileSync(
    join(mainDir, 'CMakeLists.txt'),
    [
      '# Auto-generated by @typecad/framework-esp32.',
      'idf_component_register(SRCS "main.cc"',
      '                       INCLUDE_DIRS ".")',
      '',
    ].join('\n'),
  );

  writeFileSync(
    join(projectDir, 'sdkconfig.defaults'),
    sdkconfigDefaultsForTarget(target),
  );

  writeFileSync(
    join(projectDir, '.gitignore'),
    [
      'build/',
      'sdkconfig',
      'managed_components/',
      'dependencies.lock',
      '# Auto-generated ESP-IDF env wrapper (per-machine; not portable)',
      'cuttlefish-idf-env.sh',
      'cuttlefish-idf-env.bat',
      '',
    ].join('\n'),
  );
}
