// ---------------------------------------------------------------------------
// cuttlefish.config.ts — Project configuration
//
// Auto-generated by 'cuttlefish create'. Edit to customise your build.
// ---------------------------------------------------------------------------

import type { CuttlefishConfig } from '@typecad/cuttlefish/api';

const config: CuttlefishConfig = {
  // Entry point — the main TypeScript file to transpile
  entry: './src/main.ts',

  // Target architecture
  // MCU package — provides silicon-level pin definitions

  // Board package — provides pin definitions and board constants
  board: 'esp32s3_devkitc/esp32s3/procpu',

  // Framework package — controls code generation strategy
  framework: '@typecad/framework-zephyr',
  // Framework data
  // Output / build options
  output: {
    outDir: './out',
  },

  // Toolchain configuration

  // Hardware test runner (@typecad/expect / `npm run test:hw`)
  test: {
    // Serial port for the test board. Override with --port on the CLI or the
    // CUTTLEFISH_PORT env var (e.g. CUTTLEFISH_PORT=/dev/ttyUSB0 npm run test:hw).
    port: 'COM4',
    baudRate: 115200,
    timeout: 30000,
    include: ['tests/**/*.test.ts'],
  },
  display: {
    profile: 'st7796-zephyr',
    cs: 5,
    dc: 17,
    rst: 16,
    // Hz — lower this if the panel glitches
    spiFrequency: 80000000,
    rotation: 1,
    antialias: true,
    colorOrder: 'bgr',
    invertDisplay: false,
    touch: { library: 'FT6336U', i2cAddress: 0x38, i2cFrequency: 400000, sda: 8, scl: 9, calibration: { xMin: 0, xMax: 320, yMin: 0, yMax: 480 } },
  },
};

export default config;
