// ---------------------------------------------------------------------------
// cuttlefish.config.ts — Project configuration
//
// Auto-generated by 'cuttlefish create'. Edit to customise your build.
// ---------------------------------------------------------------------------

import type { CuttlefishConfig } from '@typecad/cuttlefish/api';

const config: CuttlefishConfig = {
  // Entry point — the main TypeScript file to transpile
  entry: './src/main.ts',

  // Target architecture
  target: 'esp32s3',
  // MCU package — provides silicon-level pin definitions
  mcu: '@typecad/mcu-esp32s3',

  // Board package — provides pin definitions and board constants
  board: '@typecad/board-esp32s3',

  // Framework package — controls code generation strategy
  framework: '@typecad/framework-zephyr',
  // Framework data
  frameworkData: {
    buildTarget: 'esp32s3_devkitc/esp32s3/procpu',
  },

  // Output / build options
  output: {
    framework: 'zephyr',
    outDir: './out',
  },

  // Toolchain configuration
  toolchain: {
    type: 'west',
  },

  // Console polyfill configuration
  console: {
    baudRate: 115200,
    // Serial port for upload/monitor. Override with --port on the CLI.
    port: 'COM5',
  },

  // Hardware test runner (@typecad/expect / `npm run test:hw`)
  test: {
    // Serial port for the test board. Override with --port on the CLI or the
    // CUTTLEFISH_PORT env var (e.g. CUTTLEFISH_PORT=/dev/ttyUSB0 npm run test:hw).
    port: 'COM4',
    baudRate: 115200,
    timeout: 30000,
    include: ['tests/**/*.test.ts'],
  },
};

export default config;
