import type { InitProjectOptions } from "./init-templates";

export function generateEslintRules(_options: InitProjectOptions): string {
  return `// ---------------------------------------------------------------------------
// ESLint Custom Rules - Cuttlefish transpiler compatibility
//
// Context-sensitive checks that cannot be expressed as no-restricted-syntax
// selectors.  These rules use AST analysis to detect patterns that the
// transpiler cannot handle or only approximates.
//
// Auto-generated by 'cuttlefish create'.  Do not edit manually.
// ---------------------------------------------------------------------------

const MAP_LIKE_RE = /^[A-Z]/;

export default {
  rules: {
    "no-delete-non-map": {
      meta: {
        type: "problem",
        docs: {
          description:
            "[transpiler] delete on non-map types is unsupported in C++.",
        },
      },
      create(context) {
        return {
          "UnaryExpression[operator='delete']"(node) {
            const arg = node.argument;
            if (arg.type === "MemberExpression" && arg.computed) {
              if (
                arg.object.type === "Identifier" &&
                (MAP_LIKE_RE.test(arg.object.name) ||
                  arg.object.name === "this")
              ) {
                return;
              }
            }
            context.report({
              node,
              message:
                "[transpiler] delete on non-map types is unsupported in C++. Use a Map and its .delete() method.",
            });
          },
        };
      },
    },

    "no-object-static-non-map": {
      meta: {
        type: "problem",
        docs: {
          description:
            "[transpiler] Object.keys/values/entries on non-map types is unsupported.",
        },
      },
      create(context) {
        const METHODS = new Set(["keys", "values", "entries"]);
        return {
          CallExpression(node) {
            const callee = node.callee;
            if (
              callee.type === "MemberExpression" &&
              !callee.computed &&
              callee.object.type === "Identifier" &&
              callee.object.name === "Object" &&
              callee.property.type === "Identifier" &&
              METHODS.has(callee.property.name)
            ) {
              if (node.arguments.length > 0) {
                const arg = node.arguments[0];
                if (
                  arg.type === "Identifier" &&
                  MAP_LIKE_RE.test(arg.name) &&
                  arg.name !== "Object"
                ) {
                  return;
                }
              }
              context.report({
                node,
                message:
                  "[transpiler] Object." +
                  callee.property.name +
                  " on non-map types is unsupported. Use a Map and iterate with .keys(), .values(), or .entries().",
              });
            }
          },
        };
      },
    },

    "no-super-outside-method": {
      meta: {
        type: "problem",
        docs: {
          description:
            "[transpiler] super keyword outside class method context has no valid C++ translation.",
        },
      },
      create(context) {
        return {
          Super(node) {
            let foundValid = false;
            let current = node.parent;
            while (current) {
              if (
                current.type === "MethodDefinition" ||
                current.type === "FunctionExpression" ||
                current.type === "StaticBlock"
              ) {
                let classBody = current.parent;
                if (classBody && classBody.type === "MethodDefinition") {
                  classBody = classBody.parent;
                }
                if (classBody && classBody.type === "ClassBody") {
                  const classDecl = classBody.parent;
                  if (
                    classDecl &&
                    (classDecl.type === "ClassDeclaration" ||
                      classDecl.type === "ClassExpression") &&
                    classDecl.superClass
                  ) {
                    foundValid = true;
                  }
                }
                break;
              }
              if (
                current.type === "ClassBody" ||
                current.type === "ClassDeclaration" ||
                current.type === "ClassExpression"
              ) {
                break;
              }
              current = current.parent;
            }
            if (!foundValid) {
              context.report({
                node,
                message:
                  "[transpiler] super keyword outside of class method context has no valid C++ translation.",
              });
            }
          },
        };
      },
    },

    "no-typeof-non-primitive": {
      meta: {
        type: "problem",
        docs: {
          description:
            "[transpiler] typeof on non-primitive types returns an approximate type name in C++.",
        },
      },
      create(context) {
        return {
          "UnaryExpression[operator='typeof']"(node) {
            const arg = node.argument;
            if (
              arg.type === "MemberExpression" ||
              arg.type === "CallExpression" ||
              arg.type === "ObjectExpression"
            ) {
              context.report({
                node,
                message:
                  "[transpiler] typeof on non-primitive types returns an approximate type name in C++. Use type guards or instanceof instead.",
              });
            }
          },
        };
      },
    },

    "no-destructured-without-init": {
      meta: {
        type: "problem",
        docs: {
          description:
            "[transpiler] Destructuring declarations without initializers are unsupported.",
        },
      },
      create(context) {
        return {
          VariableDeclarator(node) {
            if (
              (node.id.type === "ObjectPattern" ||
                node.id.type === "ArrayPattern") &&
              !node.init
            ) {
              context.report({
                node,
                message:
                  "[transpiler] Destructuring declaration without an initializer is unsupported in C++. Provide a default value or initializer.",
              });
            }
          },
        };
      },
    },
  },
};
`;
}
