import type { ArchitectureIdentifier } from '../api';

export interface InitProjectOptions {
  projectName: string;
  targetId: string;
  targetDisplayName: string;
  isNative: boolean;
  architecture?: ArchitectureIdentifier;
  boardPackage?: string;
  frameworkPackage: string;
  framework: string;
  buildTarget?: string;
  mcu?: string;
  baudRate?: number;
  includeSketch: boolean;
  toolchainType?: string;
}

export function generateProjectPackageJson(options: InitProjectOptions): string {
  const { projectName, frameworkPackage, boardPackage } = options;

  const deps: Record<string, string> = {
    "@typecad/cuttlefish": "^0.1.0",
    [frameworkPackage]: "^0.1.0",
  };
  if (boardPackage) {
    deps[boardPackage] = "^0.1.0";
  }

  const depsJson = Object.entries(deps)
    .map(([k, v]) => `    "${k}": "${v}"`)
    .join(',\n');

  if (options.isNative) {
    return `{
  "name": "${projectName}",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "build": "cuttlefish build",
    "compile": "cuttlefish build --compile"
  },
  "dependencies": {
${depsJson}
  }
}
`;
  }

  const portHint = process.platform === 'win32' ? 'COM4' : '/dev/ttyACM0';

  return `{
  "name": "${projectName}",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "build": "cuttlefish build",
    "compile": "cuttlefish build --compile",
    "upload": "cuttlefish build --compile --upload --port ${portHint}",
    "monitor": "cuttlefish build --compile --upload --monitor --port ${portHint}"
  },
  "dependencies": {
${depsJson}
  }
}
`;
}

export function generateProjectTsconfig(options: InitProjectOptions): string {
  const paths = options.boardPackage
    ? `,
    "paths": {
      "@typecad": ["./.cuttlefish/board.ts"]
    }`
    : '';

  return `{
  "compilerOptions": {
    "target": "ES2021",
    "module": "nodenext",
    "moduleResolution": "nodenext",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true${paths}
  },
  "include": ["src/**/*.ts", "cuttlefish.config.ts"${options.boardPackage ? ', "cuttlefish-env.d.ts"' : ''}]
}
`;
}

export function generateProjectConfig(options: InitProjectOptions): string {
  if (options.isNative) {
    return `// ---------------------------------------------------------------------------
// cuttlefish.config.ts — Project configuration
//
// Auto-generated by 'cuttlefish create'. Edit to customise your build.
// ---------------------------------------------------------------------------

const config = {
  // Entry point — the main TypeScript file to transpile
  entry: './src/main.ts',

  // Framework package — controls code generation strategy
  framework: '${options.frameworkPackage}',

  // Output options
  output: {
    optimize: 'speed',
    outDir: './out',
  },
};

export default config;
`;
  }

  const buildTarget = options.buildTarget;
  const resolvedToolchain = options.toolchainType ?? 'arduino-cli';
  const buildTargetLine = buildTarget ? `\n  // Framework data\n  frameworkData: {\n    buildTarget: '${buildTarget}',\n  },` : '';

  const mcuLine = options.mcu
    ? `\n  // MCU package — provides silicon-level pin definitions\n  mcu: '${options.mcu.startsWith('@') ? options.mcu : `@typecad/mcu-${options.mcu}`}',\n`
    : '';

  const boardLine = options.boardPackage
    ? `\n  // Board package — provides pin definitions and board constants\n  board: '${options.boardPackage}',`
    : '';

  const baudLine = options.baudRate ? `\n\n  // Console polyfill configuration\n  console: {\n    baudRate: ${options.baudRate},\n  },` : '';

  return `// ---------------------------------------------------------------------------
// cuttlefish.config.ts — Project configuration
//
// Auto-generated by 'cuttlefish create'. Edit to customise your build.
// ---------------------------------------------------------------------------

import type { CuttlefishConfig } from '@typecad/cuttlefish/api';

const config: CuttlefishConfig = {
  // Entry point — the main TypeScript file to transpile
  entry: './src/sketch.ts',

  // Target architecture
  target: '${options.architecture}',${mcuLine}${boardLine}

  // Framework package — controls code generation strategy
  framework: '${options.frameworkPackage}',${buildTargetLine}

  // Output / build options
  output: {
    framework: '${options.framework}',
    optimize: 'size',
    outDir: './out',
  },

  // Toolchain configuration
  toolchain: {
    type: '${resolvedToolchain}',
  },${baudLine}
};

export default config;
`;
}

export function generateProjectEnvDts(options: InitProjectOptions): string {
  if (!options.boardPackage) {
    return `// ---------------------------------------------------------------------------
// cuttlefish-env.d.ts — Global type declarations
//
// Auto-generated by 'cuttlefish create'. Do not edit manually.
// ---------------------------------------------------------------------------

declare global {
  type Owned<T = any> = T;
  type Shared<T = any> = T;
  type Mutable<T = any> = T;

  type uint8_t = number;
  type int8_t = number;
  type uint16_t = number;
  type int16_t = number;
  type uint32_t = number;
  type int32_t = number;
  type size_t = number;
  type float = number;
  type double = number;
}

export {};
`;
  }

  return `// ---------------------------------------------------------------------------
// cuttlefish-env.d.ts — Virtual module declaration for '@typecad'
//
// Auto-generated by 'cuttlefish create'. Do not edit manually.
// To change the board, update cuttlefish.config.ts and re-run the transpiler.
//
// Board: ${options.targetDisplayName}
// ---------------------------------------------------------------------------

declare global {
  type Owned<T = any> = T;
  type Shared<T = any> = T;
  type Mutable<T = any> = T;

  type uint8_t = number;
  type int8_t = number;
  type uint16_t = number;
  type int16_t = number;
  type uint32_t = number;
  type int32_t = number;
  type size_t = number;
  type float = number;
  type double = number;
}

declare module '@typecad' {
  export * from './.cuttlefish/board';
}

export {};
`;
}

export function generateStarterSketch(options: InitProjectOptions): string {
  if (options.isNative) {
    return `// ---------------------------------------------------------------------------
// Hello World — Native desktop application
//
// Compiles to a native executable via g++/clang++.
// ---------------------------------------------------------------------------

function fibonacci(n: number): number {
  if (n <= 1) return n;
  return fibonacci(n - 1) + fibonacci(n - 2);
}

console.log("Hello from Cuttlefish!");
console.log("Fibonacci(10) =", fibonacci(10));
`;
  }

  return `// ---------------------------------------------------------------------------
// Blink — The classic "Hello World" of embedded
//
// Toggles the onboard LED every second using the recommended GPIO pattern.
// ---------------------------------------------------------------------------

import { LED, delay } from '@typecad';

const led = LED.asOutput(false);

while (true) {
  led.toggle();
  delay(1000);
}
`;
}

export function generateBoardForwardingFile(boardPackage: string): string {
  return `// ---------------------------------------------------------------------------
// .cuttlefish/board.ts — Dynamically generated forwarding board package
// ---------------------------------------------------------------------------

export * from '${boardPackage}';
`;
}

export function generateGitignore(_options: InitProjectOptions): string {
  return `node_modules/
out/
dist/
*.thcppmap.json
.cuttlefish-cache.json
`;
}
