import type { ArchitectureIdentifier } from '../api';

export interface InitProjectOptions {
  projectName: string;
  targetId: string;
  targetDisplayName: string;
  isNative: boolean;
  architecture?: ArchitectureIdentifier;
  boardPackage?: string;
  frameworkPackage: string;
  framework: string;
  buildTarget?: string;
  mcu?: string;
  baudRate?: number;
  includeSketch: boolean;
  toolchainType?: string;
}

export function generateProjectPackageJson(options: InitProjectOptions): string {
  const { projectName, frameworkPackage, boardPackage } = options;

  const deps: Record<string, string> = {
    "@typecad/cuttlefish": "^0.1.0",
    [frameworkPackage]: "^0.1.0",
  };
  if (boardPackage) {
    deps[boardPackage] = "^0.1.0";
  }

  const depsJson = Object.entries(deps)
    .map(([k, v]) => `    "${k}": "${v}"`)
    .join(',\n');

  if (options.isNative) {
    return `{
  "name": "${projectName}",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "build": "cuttlefish build",
    "compile": "cuttlefish build --compile"
  },
  "dependencies": {
${depsJson}
  }
}
`;
  }

  const portHint = process.platform === 'win32' ? 'COM4' : '/dev/ttyACM0';

  return `{
  "name": "${projectName}",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "build": "cuttlefish build",
    "compile": "cuttlefish build --compile",
    "upload": "cuttlefish build --compile --upload --port ${portHint}",
    "monitor": "cuttlefish build --compile --upload --monitor --port ${portHint}"
  },
  "dependencies": {
${depsJson}
  }
}
`;
}

export function generateProjectTsconfig(options: InitProjectOptions): string {
  const paths = options.boardPackage
    ? `,
    "paths": {
      "@typecad": ["./.cuttlefish/board.ts"]
    }`
    : '';

  return `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ES2022",
    "moduleResolution": "bundler",
    "lib": ["ES2022", "dom"],
    "strict": true,
    "strictNullChecks": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "noUncheckedIndexedAccess": true,
    "noImplicitOverride": true,
    "exactOptionalPropertyTypes": true,
    "noPropertyAccessFromIndexSignature": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "resolveJsonModule": true${paths}
  },
  "include": ["src/**/*.ts", "cuttlefish.config.ts"${options.boardPackage ? ', "cuttlefish-env.d.ts"' : ''}]
}
`;
}

export function generateProjectConfig(options: InitProjectOptions): string {
  if (options.isNative) {
    return `// ---------------------------------------------------------------------------
// cuttlefish.config.ts — Project configuration
//
// Auto-generated by 'cuttlefish create'. Edit to customise your build.
// ---------------------------------------------------------------------------

const config = {
  // Entry point — the main TypeScript file to transpile
  entry: './src/main.ts',

  // Framework package — controls code generation strategy
  framework: '${options.frameworkPackage}',

  // Output options
  output: {
    optimize: 'speed',
    outDir: './out',
  },
};

export default config;
`;
  }

  const buildTarget = options.buildTarget;
  const resolvedToolchain = options.toolchainType ?? 'arduino-cli';
  const buildTargetLine = buildTarget ? `\n  // Framework data\n  frameworkData: {\n    buildTarget: '${buildTarget}',\n  },` : '';

  const mcuLine = options.mcu
    ? `\n  // MCU package — provides silicon-level pin definitions\n  mcu: '${options.mcu.startsWith('@') ? options.mcu : `@typecad/mcu-${options.mcu}`}',\n`
    : '';

  const boardLine = options.boardPackage
    ? `\n  // Board package — provides pin definitions and board constants\n  board: '${options.boardPackage}',`
    : '';

  const baudLine = options.baudRate ? `\n\n  // Console polyfill configuration\n  console: {\n    baudRate: ${options.baudRate},\n  },` : '';

  return `// ---------------------------------------------------------------------------
// cuttlefish.config.ts — Project configuration
//
// Auto-generated by 'cuttlefish create'. Edit to customise your build.
// ---------------------------------------------------------------------------

import type { CuttlefishConfig } from '@typecad/cuttlefish/api';

const config: CuttlefishConfig = {
  // Entry point — the main TypeScript file to transpile
  entry: './src/sketch.ts',

  // Target architecture
  target: '${options.architecture}',${mcuLine}${boardLine}

  // Framework package — controls code generation strategy
  framework: '${options.frameworkPackage}',${buildTargetLine}

  // Output / build options
  output: {
    framework: '${options.framework}',
    optimize: 'size',
    outDir: './out',
  },

  // Toolchain configuration
  toolchain: {
    type: '${resolvedToolchain}',
  },${baudLine}
};

export default config;
`;
}

export function generateProjectEnvDts(options: InitProjectOptions): string {
  if (!options.boardPackage) {
    return `// ---------------------------------------------------------------------------
// cuttlefish-env.d.ts — Global type declarations
//
// Auto-generated by 'cuttlefish create'. Do not edit manually.
// ---------------------------------------------------------------------------

declare global {
  type Owned<T = any> = T;
  type Shared<T = any> = T;
  type Mutable<T = any> = T;

  type uint8_t = number;
  type int8_t = number;
  type uint16_t = number;
  type int16_t = number;
  type uint32_t = number;
  type int32_t = number;
  type size_t = number;
  type float = number;
  type double = number;
}

export {};
`;
  }

  return `// ---------------------------------------------------------------------------
// cuttlefish-env.d.ts — Virtual module declaration for '@typecad'
//
// Auto-generated by 'cuttlefish create'. Do not edit manually.
// To change the board, update cuttlefish.config.ts and re-run the transpiler.
//
// Board: ${options.targetDisplayName}
// ---------------------------------------------------------------------------

declare global {
  type Owned<T = any> = T;
  type Shared<T = any> = T;
  type Mutable<T = any> = T;

  type uint8_t = number;
  type int8_t = number;
  type uint16_t = number;
  type int16_t = number;
  type uint32_t = number;
  type int32_t = number;
  type size_t = number;
  type float = number;
  type double = number;
}

declare module '@typecad' {
  export * from './.cuttlefish/board';
}

export {};
`;
}

export function generateStarterSketch(options: InitProjectOptions): string {
  if (options.isNative) {
    return `// ---------------------------------------------------------------------------
// Hello World — Native desktop application
//
// Compiles to a native executable via g++/clang++.
// ---------------------------------------------------------------------------

function fibonacci(n: number): number {
  if (n <= 1) return n;
  return fibonacci(n - 1) + fibonacci(n - 2);
}

console.log("Hello from Cuttlefish!");
console.log("Fibonacci(10) =", fibonacci(10));
`;
  }

  return `// ---------------------------------------------------------------------------
// Blink — The classic "Hello World" of embedded
//
// Toggles the onboard LED every second using the recommended GPIO pattern.
// ---------------------------------------------------------------------------

import { LED, delay } from '@typecad';

const led = LED.asOutput(false);

while (true) {
  led.toggle();
  delay(1000);
}
`;
}

export function generateBoardForwardingFile(boardPackage: string): string {
  return `// ---------------------------------------------------------------------------
// .cuttlefish/board.ts — Dynamically generated forwarding board package
// ---------------------------------------------------------------------------

export * from '${boardPackage}';
`;
}

export function generateGitignore(_options: InitProjectOptions): string {
  return `node_modules/
out/
dist/
*.thcppmap.json
.cuttlefish-cache.json
`;
}

export function generateEslintConfig(_options: InitProjectOptions): string {
  return `import tsparser from "@typescript-eslint/parser";
import transpilerPlugin from "./eslint-transpiler-rules.mjs";

// no-restricted-syntax selectors sourced from SUPPORT_MATRIX ❌/🚫 rows.
const transpilerRules = [
  {
    selector: "TaggedTemplateExpression",
    message:
      "[transpiler] Tagged template expressions have no C++ equivalent. Use regular template literals or string concatenation.",
  },
  {
    selector: "MetaProperty",
    message:
      "[transpiler] import.meta and new.target have no C++ equivalent.",
  },
  {
    selector: "TSEnumBody TSEnumMember Literal[raw=/[^0-9.]/]",
    message:
      "[transpiler] String-valued enum members have no C++ equivalent (C++ enums are integer-only). Use integer values or a Map.",
  },
  {
    selector: "VariableDeclaration[kind='var']",
    message:
      "[transpiler] var declarations have no C++ equivalent. Use let or const instead.",
  },
  {
    selector: "TSTypeAliasDeclaration > TSTypeReference[typeParameters]",
    message:
      "[transpiler] Type aliases to generic types (e.g. type X = Map<K,V>, Set<T>) are not emitted as C++ typedefs and vanish at the use site. Inline the concrete generic form (Map<K,V>) at each use site, or use a named interface.",
  },
  {
    selector: "TSTypeAliasDeclaration > TSFunctionType",
    message:
      "[transpiler] Function-type aliases (type Fn = (...) => T) are not emitted as C++ typedefs. Inline the function signature at each use site, or use a named interface with a call signature.",
  },
  {
    selector: "ObjectExpression > Property[computed=true]",
    message:
      "[transpiler] Computed property names ({ [expr]: value }) have no C++ equivalent. Use fixed property names, or a Map<string, T> with .set().",
  },
  // Matrix-derived ❌/🚫 patterns (SUPPORT_MATRIX §1.2, §1.12, §2.2, §2.6, §5.1, §5.4, §6.2, §7, §1.10).
  { selector: "TSBigIntKeyword", message: "[transpiler] bigint is not supported (no C++ equivalent for embedded targets). Use number with an explicit fixed-width type." },
  { selector: "TSNeverKeyword", message: "[transpiler] the \`never\` type has no meaningful C++ lowering. Avoid it." },
  { selector: "ForOfStatement[await=true]", message: "[transpiler] for await...of is unsupported (requires an async runtime absent on bare metal)." },
  { selector: "Identifier[name='Promise']", message: "[transpiler] Promise is not supported (no promise runtime on bare metal)." },
  { selector: "CallExpression > MemberExpression.callee[property.name='then']", message: "[transpiler] .then() on a Promise is not supported (no promise runtime)." },
  { selector: "FunctionDeclaration[async=true]", message: "[transpiler] async functions cannot produce correct embedded behavior (no event loop)." },
  { selector: "FunctionExpression[async=true]", message: "[transpiler] async function expressions cannot produce correct embedded behavior (no event loop)." },
  { selector: "ArrowFunctionExpression[async=true]", message: "[transpiler] async arrow functions cannot produce correct embedded behavior (no event loop)." },
  { selector: "AwaitExpression", message: "[transpiler] await semantics are approximate; no event loop on bare metal. Avoid." },
  { selector: "FunctionDeclaration[generator=true]", message: "[transpiler] generator functions (function*) have no coroutine runtime on bare metal. Avoid." },
  { selector: "FunctionExpression[generator=true]", message: "[transpiler] generator expressions (function*) have no coroutine runtime on bare metal. Avoid." },
  { selector: "YieldExpression", message: "[transpiler] yield lowers to co_yield but no coroutine runtime is wired. Avoid." },
  { selector: "BinaryExpression[operator='**']", message: "[transpiler] the ** operator is not a first-class emit. Use Math.pow()." },
  { selector: "MemberExpression[object.name='JSON']", message: "[transpiler] JSON.* is not supported (no JSON runtime on bare metal)." },
  { selector: "CallExpression > MemberExpression.callee[object.name='Object'][property.name=/^(assign|freeze|fromEntries)$/]", message: "[transpiler] Object.assign/freeze/fromEntries are not lowered to C++." },
  { selector: "ImportExpression", message: "[transpiler] dynamic import() is unsupported (no runtime loader on bare metal). Use a static top-level import." },
  { selector: "CallExpression[callee.name='require']", message: "[transpiler] require() is unsupported. Use ES \`import\`." },
  { selector: "BinaryExpression[operator='instanceof']", message: "[transpiler] instanceof has no RTTI lowering and is treated loosely. Avoid it for user-class hierarchies." },
  { selector: "TSEnumDeclaration[const!=true]", message: "[transpiler] only 'const enum' is supported. Add the \`const\` keyword." },
];

export default [
  {
    ignores: ["**/dist/**", "**/node_modules/**", "**/*.d.ts", "out/**"],
  },
  {
    files: ["src/**/*.ts"],
    languageOptions: {
      parser: tsparser,
    },
    plugins: {
      cuttlefish: transpilerPlugin,
    },
    rules: {
      "no-restricted-syntax": ["error", ...transpilerRules],
      // Core ESLint + @typescript-eslint AOT-safety rules.
      "@typescript-eslint/no-explicit-any": "error",
      "no-delete-var": "error",
      "no-eval": "error",
      "no-sparse-arrays": "error",
      "no-restricted-globals": [
        "error",
        { "name": "Proxy", "message": "[transpiler] Proxy is not supported (no AOT lowering). Avoid." },
        { "name": "Reflect", "message": "[transpiler] Reflect is not supported (no AOT lowering). Avoid." },
      ],
      // Cuttlefish transpiler-compatibility plugin rules.
      "cuttlefish/no-delete-non-map": "error",
      "cuttlefish/no-object-static-non-map": "error",
      "cuttlefish/no-super-outside-method": "error",
      "cuttlefish/no-typeof-non-primitive": "error",
      "cuttlefish/no-destructured-without-init": "error",
      "cuttlefish/no-fractional-to-number-type": "error",
      "cuttlefish/no-array-param-content-mutation": "error",
      "cuttlefish/no-container-functional-methods": "error",
      "cuttlefish/no-undefined-compare-on-get": "error",
      "cuttlefish/no-typed-array-param-length": "error",
      "cuttlefish/no-typed-array-return": "error",
      "cuttlefish/no-dynamic-property-access": "error",
    },
  },
];
`;
}
