import type { ArchitectureIdentifier } from '../api';
import { LINT_RULES } from '../ir/feature-registry';

export interface InitProjectOptions {
  projectName: string;
  targetId: string;
  targetDisplayName: string;
  isNative: boolean;
  architecture?: ArchitectureIdentifier;
  boardPackage?: string;
  frameworkPackage: string;
  framework: string;
  buildTarget?: string;
  mcu?: string;
  baudRate?: number;
  includeSketch: boolean;
  toolchainType?: string;
}

export function generateProjectPackageJson(options: InitProjectOptions): string {
  const { projectName, frameworkPackage, boardPackage } = options;

  const deps: Record<string, string> = {
    "@typecad/cuttlefish": "^0.1.0",
    [frameworkPackage]: "^0.1.0",
  };
  if (boardPackage) {
    deps[boardPackage] = "^0.1.0";
  }

  const depsJson = Object.entries(deps)
    .map(([k, v]) => `    "${k}": "${v}"`)
    .join(',\n');

  // The scaffolded eslint.config.mjs imports @typescript-eslint/parser and the
  // eslint-transpiler-rules plugin (which is plain JS, no dep). Without these
  // devDependencies `npm run lint` fails to resolve the parser/plugin in a
  // freshly created project. Versions mirror the repo demo's package.json.
  const devDepsJson = [
    '    "eslint": "^10.4.1"',
    '    "@typescript-eslint/parser": "^8.61.0"',
    '    "@typescript-eslint/eslint-plugin": "^8.61.0"',
  ].join(',\n');

  if (options.isNative) {
    return `{
  "name": "${projectName}",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "build": "cuttlefish build",
    "compile": "cuttlefish build --compile",
    "lint": "eslint src/"
  },
  "dependencies": {
${depsJson}
  },
  "devDependencies": {
${devDepsJson}
  }
}
`;
  }

  const portHint = process.platform === 'win32' ? 'COM4' : '/dev/ttyACM0';

  return `{
  "name": "${projectName}",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "build": "cuttlefish build",
    "compile": "cuttlefish build --compile",
    "upload": "cuttlefish build --compile --upload --port ${portHint}",
    "monitor": "cuttlefish build --compile --upload --monitor --port ${portHint}",
    "lint": "eslint src/"
  },
  "dependencies": {
${depsJson}
  },
  "devDependencies": {
${devDepsJson}
  }
}
`;
}

export function generateProjectTsconfig(options: InitProjectOptions): string {
  const paths = options.boardPackage
    ? `,
    "paths": {
      "@typecad": ["./.cuttlefish/board.ts"]
    }`
    : '';

  return `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ES2022",
    "moduleResolution": "bundler",
    "lib": ["ES2022", "dom"],
    "strict": true,
    "strictNullChecks": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "noUncheckedIndexedAccess": true,
    "noImplicitOverride": true,
    "exactOptionalPropertyTypes": true,
    "noPropertyAccessFromIndexSignature": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "resolveJsonModule": true${paths}
  },
  "include": ["src/**/*.ts", "cuttlefish.config.ts"${options.boardPackage ? ', "cuttlefish-env.d.ts"' : ''}]
}
`;
}

export function generateProjectConfig(options: InitProjectOptions): string {
  if (options.isNative) {
    return `// ---------------------------------------------------------------------------
// cuttlefish.config.ts — Project configuration
//
// Auto-generated by 'cuttlefish create'. Edit to customise your build.
// ---------------------------------------------------------------------------

const config = {
  // Entry point — the main TypeScript file to transpile
  entry: './src/main.ts',

  // Framework package — controls code generation strategy
  framework: '${options.frameworkPackage}',

  // Output options
  output: {
    optimize: 'speed',
    outDir: './out',
  },
};

export default config;
`;
  }

  const buildTarget = options.buildTarget;
  const resolvedToolchain = options.toolchainType ?? 'arduino-cli';
  const buildTargetLine = buildTarget ? `\n  // Framework data\n  frameworkData: {\n    buildTarget: '${buildTarget}',\n  },` : '';

  const mcuLine = options.mcu
    ? `\n  // MCU package — provides silicon-level pin definitions\n  mcu: '${options.mcu.startsWith('@') ? options.mcu : `@typecad/mcu-${options.mcu}`}',\n`
    : '';

  const boardLine = options.boardPackage
    ? `\n  // Board package — provides pin definitions and board constants\n  board: '${options.boardPackage}',`
    : '';

  const baudLine = options.baudRate ? `\n\n  // Console polyfill configuration\n  console: {\n    baudRate: ${options.baudRate},\n  },` : '';

  return `// ---------------------------------------------------------------------------
// cuttlefish.config.ts — Project configuration
//
// Auto-generated by 'cuttlefish create'. Edit to customise your build.
// ---------------------------------------------------------------------------

import type { CuttlefishConfig } from '@typecad/cuttlefish/api';

const config: CuttlefishConfig = {
  // Entry point — the main TypeScript file to transpile
  entry: './src/sketch.ts',

  // Target architecture
  target: '${options.architecture}',${mcuLine}${boardLine}

  // Framework package — controls code generation strategy
  framework: '${options.frameworkPackage}',${buildTargetLine}

  // Output / build options
  output: {
    framework: '${options.framework}',
    optimize: 'size',
    outDir: './out',
  },

  // Toolchain configuration
  toolchain: {
    type: '${resolvedToolchain}',
  },${baudLine}
};

export default config;
`;
}

export function generateProjectEnvDts(options: InitProjectOptions): string {
  if (!options.boardPackage) {
    return `// ---------------------------------------------------------------------------
// cuttlefish-env.d.ts — Global type declarations
//
// Auto-generated by 'cuttlefish create'. Do not edit manually.
// ---------------------------------------------------------------------------

declare global {
  type Owned<T = unknown> = T;
  type Shared<T = unknown> = T;
  type Mutable<T = unknown> = T;

  type uint8_t = number;
  type int8_t = number;
  type uint16_t = number;
  type int16_t = number;
  type uint32_t = number;
  type int32_t = number;
  type size_t = number;
  type float = number;
  type double = number;
}

export {};
`;
  }

  return `// ---------------------------------------------------------------------------
// cuttlefish-env.d.ts — Virtual module declaration for '@typecad'
//
// Auto-generated by 'cuttlefish create'. Do not edit manually.
// To change the board, update cuttlefish.config.ts and re-run the transpiler.
//
// Board: ${options.targetDisplayName}
// ---------------------------------------------------------------------------

declare global {
  type Owned<T = unknown> = T;
  type Shared<T = unknown> = T;
  type Mutable<T = unknown> = T;

  type uint8_t = number;
  type int8_t = number;
  type uint16_t = number;
  type int16_t = number;
  type uint32_t = number;
  type int32_t = number;
  type size_t = number;
  type float = number;
  type double = number;
}

declare module '@typecad' {
  export * from './.cuttlefish/board';
}

export {};
`;
}

export function generateStarterSketch(options: InitProjectOptions): string {
  if (options.isNative) {
    return `// ---------------------------------------------------------------------------
// Hello World — Native desktop application
//
// Compiles to a native executable via g++/clang++.
// ---------------------------------------------------------------------------

function fibonacci(n: number): number {
  if (n <= 1) return n;
  return fibonacci(n - 1) + fibonacci(n - 2);
}

console.log("Hello from Cuttlefish!");
console.log("Fibonacci(10) =", fibonacci(10));
`;
  }

  return `// ---------------------------------------------------------------------------
// Blink — The classic "Hello World" of embedded
//
// Toggles the onboard LED every second using the recommended GPIO pattern.
// ---------------------------------------------------------------------------

import { LED, delay } from '@typecad';

const led = LED.asOutput(false);

while (true) {
  led.toggle();
  delay(1000);
}
`;
}

export function generateBoardForwardingFile(boardPackage: string): string {
  return `// ---------------------------------------------------------------------------
// .cuttlefish/board.ts — Dynamically generated forwarding board package
// ---------------------------------------------------------------------------

export * from '${boardPackage}';
`;
}

export function generateGitignore(_options: InitProjectOptions): string {
  return `node_modules/
out/
dist/
*.thcppmap.json
.cuttlefish-cache.json
`;
}

export function generateEslintConfig(_options: InitProjectOptions): string {
  // `no-restricted-syntax` selectors are generated from LINT_RULES
  // (packages/cuttlefish/src/ir/feature-registry.ts), the single source of
  // truth shared with build-time prescan diagnostics. See SUPPORT_MATRIX for
  // the per-pattern ❌/🚫 rationale. Do not hand-edit the array below.
  const transpilerRulesJson = JSON.stringify(
    LINT_RULES.map(({ selector, message }) => ({ selector, message })),
    null,
    2,
  ).replace(/\n/g, "\n  ");

  return `import tsparser from "@typescript-eslint/parser";
import tseslint from "@typescript-eslint/eslint-plugin";
import transpilerPlugin from "./eslint-transpiler-rules.mjs";

// Auto-generated from feature-registry.ts LINT_RULES — do not edit by hand.
const transpilerRules = ${transpilerRulesJson};

export default [
  {
    ignores: ["**/dist/**", "**/node_modules/**", "**/*.d.ts", "out/**"],
  },
  {
    files: ["src/**/*.ts"],
    languageOptions: {
      parser: tsparser,
      parserOptions: {
        // Type-aware parsing so @typescript-eslint/no-explicit-any resolves
        // imported bindings to their real types instead of defaulting to any.
        project: "./tsconfig.json",
      },
    },
    plugins: {
      "@typescript-eslint": tseslint,
      cuttlefish: transpilerPlugin,
    },
    rules: {
      "no-restricted-syntax": ["error", ...transpilerRules],
      // Core ESLint + @typescript-eslint AOT-safety rules.
      "@typescript-eslint/no-explicit-any": "error",
      "no-delete-var": "error",
      "no-eval": "error",
      "no-sparse-arrays": "error",
      "no-restricted-globals": [
        "error",
        { "name": "Proxy", "message": "[transpiler] Proxy is not supported (no AOT lowering). Avoid." },
        { "name": "Reflect", "message": "[transpiler] Reflect is not supported (no AOT lowering). Avoid." },
        { "name": "WeakRef", "message": "[transpiler] WeakRef depends on the GC schedule — bare metal has no GC. Avoid." },
        { "name": "FinalizationRegistry", "message": "[transpiler] FinalizationRegistry depends on the GC schedule — bare metal has no GC. Avoid." },
        { "name": "Symbol", "message": "[transpiler] Symbol depends on runtime symbol lookup / the iterator protocol, which has no AOT lowering. Avoid." },
      ],
      // Cuttlefish transpiler-compatibility plugin rules.
      "cuttlefish/no-delete-non-map": "error",
      "cuttlefish/no-object-static-non-map": "error",
      "cuttlefish/no-super-outside-method": "error",
      "cuttlefish/no-typeof-non-primitive": "error",
      "cuttlefish/no-destructured-without-init": "error",
      "cuttlefish/no-fractional-to-number-type": "error",
      "cuttlefish/no-array-param-content-mutation": "error",
      "cuttlefish/no-container-functional-methods": "error",
      "cuttlefish/no-undefined-compare-on-get": "error",
      "cuttlefish/no-map-struct-mutation": "error",
      "cuttlefish/no-mutating-method-on-const-collection": "warn",
      "cuttlefish/no-readonly-loop-variable-mutation": "warn",
      "cuttlefish/no-undefined-compare-on-struct-field": "error",
      "cuttlefish/no-typed-array-param-length": "error",
      "cuttlefish/no-typed-array-return": "error",
      "cuttlefish/no-typed-array-field": "error",
      "cuttlefish/no-dynamic-property-access": "error",
      "cuttlefish/no-this-in-free-function": "error",
    },
  },
];
`;
}
