// Auto-generated by cuttlefish (UI lowering). Do not edit.
import type { TextElement, ButtonElement, ViewElement, CheckElement, SelectElement, RadioElement, ProgressElement, RangeElement, InputElement, CanvasElement } from "@typecad/ui";
interface HomeScreenGroup {
  homeHeader: ViewElement;
  homeTitle: TextElement;
  homeSubtitle: TextElement;
  homeNav: ViewElement;
}
interface ButtonsScreenGroup {
  btnPrimary: ButtonElement;
  btnSecondary: ButtonElement;
  btnOutline: ButtonElement;
  btnGhost: ButtonElement;
  btnDestructive: ButtonElement;
  btnSmall: ButtonElement;
  btnLarge: ButtonElement;
  tapBadge: TextElement;
  btnBlock: ButtonElement;
}
interface FormsScreenGroup {
  demoName: InputElement;
  nameEcho: TextElement;
  demoSwitch: CheckElement;
  switchState: TextElement;
  demoSelect: SelectElement;
  selectEcho: TextElement;
  demoCheck: CheckElement;
  checkEcho: TextElement;
  radioCalm: RadioElement;
  radioFast: RadioElement;
  radioEcho: TextElement;
  demoRange: RangeElement;
  rangeEcho: TextElement;
  formValidName: InputElement;
  nameError: TextElement;
  nameSaved: TextElement;
  formValidSave: ButtonElement;
}
interface FeedbackScreenGroup {
  demoProgress: ProgressElement;
  demoAvatar: TextElement;
}
interface LayoutScreenGroup {
  layerBack: ViewElement;
  layerMid: ViewElement;
  layerFront: ViewElement;
}
interface EffectsScreenGroup {
  fxSlide: ViewElement;
  fxTurn: ViewElement;
  fxPulse: ViewElement;
  fxColor: ViewElement;
}
interface MediaScreenGroup {
  imgContain: TextElement;
  imgCover: TextElement;
  imgFill: TextElement;
  demoCanvas: CanvasElement;
}
interface ListsScreenGroup {
  demoList: TextElement;
  listTapEcho: TextElement;
}
interface KeyboardScreenGroup {
  kbInput: InputElement;
}
interface StateScreenGroup {
  bumpBtn: ButtonElement;
  clickBadge: TextElement;
  stateCheck: CheckElement;
  lamp: ViewElement;
  boundRange: RangeElement;
  volEcho: TextElement;
  clockText: TextElement;
  demoMeter: ProgressElement;
  lockedInput: InputElement;
  lockedBtn: ButtonElement;
}
interface DrawerScreenGroup {
  drawerScreen: ViewElement;
  openDrawerBtn: ButtonElement;
  drawerTapEcho: TextElement;
  demoDrawer: TextElement;
  drawerActionBtn: ButtonElement;
  closeDrawerBtn: ButtonElement;
}
interface DialogScreenGroup {
  dialogScreen: ViewElement;
  openDialogBtn: ButtonElement;
  toastBtn: ButtonElement;
  toastEcho: TextElement;
  demoDialog: TextElement;
  dialogCancel: ButtonElement;
  dialogOk: ButtonElement;
  demoToast: TextElement;
}
interface TabsScreenGroup {
  tabBtn0: ButtonElement;
  tabBtn1: ButtonElement;
  tabBtn2: ButtonElement;
  tabPane0: ViewElement;
  tabName: InputElement;
  tabPane1: ViewElement;
  tabSlider: RangeElement;
  tabSliderEcho: TextElement;
  tabPane2: ViewElement;
}
interface AccordionScreenGroup {
  accTrig0: ButtonElement;
  accChev0: TextElement;
  accPane0: ViewElement;
  accTrig1: ButtonElement;
  accChev1: TextElement;
  accPane1: ViewElement;
  accRange: RangeElement;
  accTrig2: ButtonElement;
  accChev2: TextElement;
  accPane2: ViewElement;
  accCheck: CheckElement;
  accCheckEcho: TextElement;
}
interface ScreenGroups {
  home: HomeScreenGroup;
  buttons: ButtonsScreenGroup;
  forms: FormsScreenGroup;
  feedback: FeedbackScreenGroup;
  layout: LayoutScreenGroup;
  effects: EffectsScreenGroup;
  media: MediaScreenGroup;
  lists: ListsScreenGroup;
  keyboard: KeyboardScreenGroup;
  state: StateScreenGroup;
  drawer: DrawerScreenGroup;
  dialog: DialogScreenGroup;
  tabs: TabsScreenGroup;
  accordion: AccordionScreenGroup;
}
export interface ScreenTree {
  home: ViewElement;
  homeHeader: ViewElement;
  homeTitle: TextElement;
  homeSubtitle: TextElement;
  homeNav: ViewElement;
  buttons: ViewElement;
  btnPrimary: ButtonElement;
  btnSecondary: ButtonElement;
  btnOutline: ButtonElement;
  btnGhost: ButtonElement;
  btnDestructive: ButtonElement;
  btnSmall: ButtonElement;
  btnLarge: ButtonElement;
  tapBadge: TextElement;
  btnBlock: ButtonElement;
  badges: ViewElement;
  cards: ViewElement;
  forms: ViewElement;
  demoName: InputElement;
  nameEcho: TextElement;
  demoSwitch: CheckElement;
  switchState: TextElement;
  demoSelect: SelectElement;
  selectEcho: TextElement;
  demoCheck: CheckElement;
  checkEcho: TextElement;
  radioCalm: RadioElement;
  radioFast: RadioElement;
  radioEcho: TextElement;
  demoRange: RangeElement;
  rangeEcho: TextElement;
  formValidName: InputElement;
  nameError: TextElement;
  nameSaved: TextElement;
  formValidSave: ButtonElement;
  alerts: ViewElement;
  feedback: ViewElement;
  demoProgress: ProgressElement;
  demoAvatar: TextElement;
  table: ViewElement;
  typography: ViewElement;
  richtext: ViewElement;
  layout: ViewElement;
  layerBack: ViewElement;
  layerMid: ViewElement;
  layerFront: ViewElement;
  effects: ViewElement;
  fxSlide: ViewElement;
  fxTurn: ViewElement;
  fxPulse: ViewElement;
  fxColor: ViewElement;
  media: ViewElement;
  imgContain: TextElement;
  imgCover: TextElement;
  imgFill: TextElement;
  demoCanvas: CanvasElement;
  lists: ViewElement;
  demoList: TextElement;
  listTapEcho: TextElement;
  keyboard: ViewElement;
  kbInput: InputElement;
  state: ViewElement;
  bumpBtn: ButtonElement;
  clickBadge: TextElement;
  stateCheck: CheckElement;
  lamp: ViewElement;
  boundRange: RangeElement;
  volEcho: TextElement;
  clockText: TextElement;
  demoMeter: ProgressElement;
  lockedInput: InputElement;
  lockedBtn: ButtonElement;
  drawer: ViewElement;
  drawerScreen: ViewElement;
  openDrawerBtn: ButtonElement;
  drawerTapEcho: TextElement;
  demoDrawer: TextElement;
  drawerActionBtn: ButtonElement;
  closeDrawerBtn: ButtonElement;
  dialog: ViewElement;
  dialogScreen: ViewElement;
  openDialogBtn: ButtonElement;
  toastBtn: ButtonElement;
  toastEcho: TextElement;
  demoDialog: TextElement;
  dialogCancel: ButtonElement;
  dialogOk: ButtonElement;
  demoToast: TextElement;
  tabs: ViewElement;
  tabBtn0: ButtonElement;
  tabBtn1: ButtonElement;
  tabBtn2: ButtonElement;
  tabPane0: ViewElement;
  tabName: InputElement;
  tabPane1: ViewElement;
  tabSlider: RangeElement;
  tabSliderEcho: TextElement;
  tabPane2: ViewElement;
  accordion: ViewElement;
  accTrig0: ButtonElement;
  accChev0: TextElement;
  accPane0: ViewElement;
  accTrig1: ButtonElement;
  accChev1: TextElement;
  accPane1: ViewElement;
  accRange: RangeElement;
  accTrig2: ButtonElement;
  accChev2: TextElement;
  accPane2: ViewElement;
  accCheck: CheckElement;
  accCheckEcho: TextElement;
  groups: ScreenGroups;
}
export const screen: ScreenTree;