// ---------------------------------------------------------------------------
// Board generator — emits the narrowed `.cuttlefish/board.ts` for a contract
//
// Given the MCU package name plus the matched pin and peripheral names, writes
// a board.ts that:
//   - re-exports the full HAL surface from @typecad/hal (constants, functions,
//     timing, math, GPIO/Pin helpers, buses) so firmware has the complete
//     runtime vocabulary; and
//   - re-exports ONLY the connected pins and selected peripherals from the MCU
//     package, so any pin the PCB did not wire is absent from `@typecad/board`
//     and using it becomes a compile error.
//
// The emitted file is consumed via cuttlefish-env.d.ts, which emits
// `declare module '@typecad/board' { export * from './board.js'; ... }`
// for contract-based configs (see config-loader.ts). The './board.js' relative
// specifier resolves to this file in the same `.cuttlefish/` directory.
// ---------------------------------------------------------------------------

import fs from 'node:fs';
import path from 'node:path';

/** The directory (relative to the project root) where board.ts is generated. */
export const CUTTLEFISH_DIR = '.cuttlefish';

export interface GenerateBoardOptions {
  /** Absolute project root dir (where .cuttlefish/ lives). */
  projectDir: string;
  /** MCU package specifier, e.g. '@typecad/mcu-atmega328p'. */
  mcuPackage: string;
  /** Matched MCU pin names to re-export (e.g. ['PB5','PC4']). */
  connectedPins: string[];
  /** Selected peripheral instance names to re-export (e.g. ['I2C0']). */
  peripherals: string[];
}

/**
 * Writes the narrowed `.cuttlefish/board.ts`.
 * @returns the absolute path to the generated file.
 */
export function generateBoardFile(opts: GenerateBoardOptions): string {
  const { projectDir, mcuPackage, connectedPins, peripherals } = opts;

  const cuttlefishDir = path.join(projectDir, CUTTLEFISH_DIR);
  if (!fs.existsSync(cuttlefishDir)) {
    fs.mkdirSync(cuttlefishDir, { recursive: true });
  }

  const lines: string[] = [
    '// Auto-generated by the cuttlefish transpiler from a TypeCAD contract.',
    '// Do not edit manually — regenerate by re-running cuttlefish.',
    '//',
    '// This board exposes only the pins and peripherals that the source contract',
    `// (${mcuPackage}) declares as connected on the PCB. Pins the board did not wire`,
    '// are intentionally absent: using one is a compile error.',
    '',
    '// Full HAL runtime surface (constants, timing, math, GPIO/bus helpers).',
    "export * from '@typecad/hal';",
    '',
    '// Narrowed pin set — only pins the contract declares connected.',
  ];

  if (connectedPins.length > 0) {
    lines.push(`export { ${connectedPins.join(', ')} } from '${mcuPackage}';`);
  }

  if (peripherals.length > 0) {
    lines.push('');
    lines.push('// Narrowed peripheral set — only buses whose pins are wired on the PCB.');
    lines.push(`export { ${peripherals.join(', ')} } from '${mcuPackage}';`);
  }

  lines.push(''); // trailing newline

  const outPath = path.join(cuttlefishDir, 'board.ts');
  fs.writeFileSync(outPath, lines.join('\n'), 'utf-8');
  return outPath;
}
