// ---------------------------------------------------------------------------
// Board generator — emits the narrowed `.typecad-hal/board.ts` for a contract
//
// Given the MCU package name plus the matched pin and peripheral names, writes
// a board.ts that:
//   - re-exports the ungated HAL surface from @typecad/hal/core (constants,
//     functions, timing, math, GPIO/Pin helpers, buses) so firmware has the
//     complete runtime vocabulary; and
//   - re-exports ONLY the connected pins and selected peripherals from the MCU
//     package, so any pin the PCB did not wire is absent from the module and
//     using it becomes a compile error.
//
// The emitted file is what the user's '@typecad/hal' import resolves to (the
// project tsconfig maps that specifier onto it.
// which is why it references the implementation package via the
// './core' subpath — the one specifier the mapping does not capture. The
// typecad-hal-env.d.ts ambient declaration covers the legacy specifier for the
// language server (see config-loader.ts). The './board.js' relative
// specifier resolves to this file in the same `.typecad-hal/` directory.
// ---------------------------------------------------------------------------

import fs from 'node:fs';
import path from 'node:path';
import { getBoardGateData } from '../board-gate.js';

const BS_DOT = /\./g;

/** The directory (relative to the project root) where board.ts is generated. */
export const CUTTLEFISH_DIR = '.typecad-hal';

export interface GenerateBoardOptions {
  /** Absolute project root dir (where .typecad-hal/ lives). */
  projectDir: string;
  /** The Zephyr SoC name the contract narrows (e.g. 'stm32f411xe'). */
  soc: string;
  /** Matched pin names to export (e.g. ['PB5','PC4']). */
  connectedPins: string[];
  /** Selected peripheral instance names to export (e.g. ['I2C0']). */
  peripherals: string[];
}

/**
 * Writes the narrowed `.typecad-hal/board.ts`.
 * @returns the absolute path to the generated file.
 */
export function generateBoardFile(opts: GenerateBoardOptions): string {
  const { projectDir, soc, connectedPins, peripherals } = opts;

  // The ungated surface is derived from the project's own hal copy (same
  // resolution as HAL source parsing).
  const { ungated: BOARD_UNGATED_EXPORTS, ungatedTypes: BOARD_UNGATED_TYPE_EXPORTS } =
    getBoardGateData(projectDir);

  const cuttlefishDir = path.join(projectDir, CUTTLEFISH_DIR);
  if (!fs.existsSync(cuttlefishDir)) {
    fs.mkdirSync(cuttlefishDir, { recursive: true });
  }

  const lines: string[] = [
    '// Auto-generated by the typecad-hal transpiler from a TypeCAD contract.',
    '// Do not edit manually — regenerate by re-running cuttlefish.',
    '//',
    '// This board exposes only the pins and peripherals that the source contract',
    `// (soc ${soc}) declares as connected on the PCB. Pins the board did not wire`,
    '// are intentionally absent: using one is a compile error.',
    '',
    '// Full HAL runtime surface (constants, timing, math, GPIO/bus helpers) via',
    "// the './core' subpath — '@typecad/hal' in user code maps to THIS module.",
    "import { Pin, I2CBus, SPIBus, UART } from '@typecad/hal/core';",
    '',
    '// Always-available HAL surface (not gated on board facts).',
    `export { ${BOARD_UNGATED_EXPORTS.join(', ')} } from '@typecad/hal/core';`,
    `export type { ${BOARD_UNGATED_TYPE_EXPORTS.join(', ')} } from '@typecad/hal/core';`,
    '',
    '// Narrowed pin set — only pins the contract declares connected.',
  ];

  if (connectedPins.length > 0) {
    for (const pin of connectedPins) {
      const ident = pin.replace(BS_DOT, '_');
      lines.push(`export const ${ident} = Pin.fromPort('${pin}');`);
    }
  }

  if (peripherals.length > 0) {
    lines.push('');
    lines.push('// Narrowed peripheral set — only buses whose pins are wired on the PCB.');
    for (const p of peripherals) {
      if (p.startsWith('I2C')) lines.push(`export const ${p} = new I2CBus('${p}');`);
      else if (p.startsWith('SPI')) lines.push(`export const ${p} = new SPIBus('${p}');`);
      else if (p.startsWith('UART')) lines.push(`export const ${p} = new UART('${p}');`);
    }
  }

  lines.push(''); // trailing newline

  const outPath = path.join(cuttlefishDir, 'board.ts');
  fs.writeFileSync(outPath, lines.join('\n'), 'utf-8');
  return outPath;
}
